index.html, navbar.css, tools/sip.html
Fixes #1813 
Dropdown while hovering in the tools of the navbar and linking the different section of page i.e different tools in the page so that user do not have to scroll the all the way down for specific tool and can easily be redirect in that tool section by clicking
=> Added the dropdown while hovering in tools of navbar to easily navigate through tools

index.html
issue number: #1830 
remove extra space from footer
=> remove extra space from footer

about.html, blog.html, careers.html, contact.html, faq.html, index.html, navbar.css, quiz.html, tools/sip.html, trends.html
#1820 fixed
The navbar layout has become completely unstructured across all pages, causing elements such as the login button and other menu items to appear misaligned. This disrupts the overall user experience and affects navigation clarity. This commit restructures the navbar to ensure proper alignment and consistent behavior across all pages, improving both functionality and design.
https://github.com/user-attachments/assets/686cea3d-3cb2-4c21-946a-96d46342b33e
=> Fix Navbar Layout Issue Across All Pages

index.html
issue_number: #1802 
enhanced the ui of placeholder and buttom of home page suscribe to news letter section
https://github.com/user-attachments/assets/47044a78-ef24-4558-90a0-d598c89d1e56
=> Enhanced th UI of placeholder and button in home page of News letter section

careers.html, index.html
Hello, PR
Issue - #1848 #1868
Navbar Issue Fixed in both Home & Career page - 
Before -
After -
=> Fixed Navbar issue ! #1848 #1868

blogs/privacy-policy.html, blogs/terms-of-service.html
now ui of the terms and condition and privacy policy is enhanced.
additionally this section is responsive for all devices
=> enhanced the ui of privacy policy and terms and condition

loginPage.css, loginPage.html
Added up button animation, focus effect on the input and trailing cursor
https://github.com/user-attachments/assets/dae6fba9-55ab-453b-ab2b-7875a7a725a6
=> editing button, input and cursor (conflict resolved)

about.html, index.html
#1864  
[Alignment issue resolved in the footer of about page]
Before:
After:
=> Resolved alignment issue in about page

careers.html
issue_number: #1866 
remove duplicate text from home page footer
=> remove duplicate text feom footer of carrier page

quiz.html
#1890
[Resolve alignment issue in quiz page]
Before
After
=> Resolve alignment issue in quiz page

index.html
#1893 
Changed the text color to white and increased its size.
BEFORE:
AFTER:
=> Changed the text color to white and increased its size.

faq.html
This pull request introduces several enhancements to the original code, focusing on improving the user experience, particularly in the FAQ section, form fields, and the scroll-based progress bar. The key modifications include hover effects, size adjustments, and script improvements for better functionality.
1. **Enhanced Hover Effects**:
- Implemented smoother hover effects for FAQ questions and form fields.
- Adjusted the size of elements on hover for a more interactive feel.
2. **Form Fields Improvements**:
- Applied hover effects to input fields in the feedback form, ensuring they provide visual feedback during user interaction.
3. **Progress Bar Functionality**:
- Updated the JavaScript for the progress bar to ensure it correctly calculates the scroll percentage without starting from …
=> Updated FAQs: CSS Styling and JavaScript Progress Bar Fixes

blogs/terms-of-service.html
This PR introduces several enhancements to the Terms and Conditions page of the FinVeda website, aimed at improving the user interface (UI) and overall user experience (UX). The changes focus on accessibility, visual organization, and readability.
1. **Addition of Unique IDs**:
- Each section of the Terms and Conditions has been assigned a unique ID. This improves accessibility by allowing users to easily navigate to specific sections using links. It also aids in search engine optimization (SEO) by providing clearer structure to the content.
2. **Enclosing Sections in Cards**:
- Each section of the Terms and Conditions is now enclosed within a card layout. This design choice enhances visual separation between different sections, making it easier for users to digest the information. The …
=> Refactor Terms and Conditions UI: Added Card Structure and Hover Effects

about.html, assets/css/about.css
Hovering effects added, enhanced the look of the contributors container
https://github.com/user-attachments/assets/110ef035-9fe1-4bbd-ad73-fecdba61b4d8
=> Contributors area enhanced

footer.html, index.html
#1898 
[Removal of unwanted text from homescreen]
Before:
After:
=> Removal of unwanted text from homescreen

index.html
issue_number: #1892 
remove extra text from home page footer and extra space
Aftter:
=> Remove extra text and space from home page footer

quiz.html
#1906
Aligned items properly in footer of quiz page
Before:
After:
=> Aligned items properly in footer of quiz page

quiz.html
#1917 
The text in Quiz page was not matching with the UI of the page so I changed it to white.
BEFORE: 
AFTER:
=> Improved the UI of quiz page.

quiz.html
Animation is added in quiz page.
Before
https://github.com/user-attachments/assets/6aff5c08-938d-4587-8c84-13fc72e832dc
After
https://github.com/user-attachments/assets/533a116e-8cd3-4511-b8c9-a7a1def93a12
=> Animation added in quiz page.

quiz.html
Reverts ayush-that/FinVeda#1918
=> Revert "Animation added in quiz page."

index.html
#1915 fixed
The navigation bar on the home page is different from other pages, with the Tool and Help buttons missing. This inconsistency affects the user experience and functionality across the site. The commit restores the missing buttons, ensuring uniformity in the navbar across all pages. Please review and merge this fix to prevent further issues with navigation.
=> Fix missing Tool and Help buttons in the Navbar on Home page

index.html
Reverts ayush-that/FinVeda#1928
=> Revert "Fix missing Tool and Help buttons in the Navbar on Home page"

index.html
Fixes:  #(#1838)
so basically i just recreate the  "FEEDBACK FORM " SECTION   which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- redesign the  whole section
- change the size of feedback form to look bulky and intercative
- ADD FOCUS EFFECTS
- and also unessential white color div …
=> UI IMPROVEMENT OF FEEDBACK FORM #1838

contact.html, index.html, quiz.html
=> Animation added in quiz and contact page

Finveda/Finveda/package-lock.json, Finveda/Finveda/package.json, index.html
[style]: Alignment of the social media icons #1921
Fixed the margin in the left side of the icons in the home page.
=> Fixed icons alignment in the home page

ContactUs.html, assets/css/style.css, index.html, navbar.css
None
In the Contact Us page the navbar items has too much space in between causing the home item to stick with logo also there is no space between navbar and content section in Contact page .  I fixed the contact us page alignment
Fixed issue no #1912 
Fixed issue no #1909
Before= no space between navbar and hero content section
Before= the navbar overlaps with the logo and too much space between them
After
=> Fixing contact page alignment 

tools/pension.js, tools/sip.html
created pension calculator
created pension calculator
https://github.com/user-attachments/assets/65a9b7f3-fa1f-4507-992a-57918665af64
=> solved #1803 created pension calculator

about.html
Fixes:  #(#1843)
so basically i just MANIPULATE the  "BLOG-CONTENT " SECTION   IN ABOUT US PAGE which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- GIVE GOLDEN BORDER
- ADD BUTTON FOR LEARN MORE
- change the size CARDS AND ALO GIVE MARGIN-PADDING WHICH GIVE INTERACTIVE INTERFACE
- and …
=> UI IMPROVEMENT IN ABOUT US PAGE #1843

contact.html
Fixes:  #(#1844)
so basically i just MANIPULATE the  "CONTAC T PAGE " SECTION   IN ABOUT US PAGE which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- redesign the page
- looks interactive
- change the size CARDS AND ALO GIVE MARGIN-PADDING WHICH GIVE INTERACTIVE INTERFACE
- and also …
=> UI IMPROVEMENT IN CONTAC T PAGE #1844

index.html
#1955 fixed
This pull request addresses the footer layout problem where extra text was appearing below the social media icons, disrupting the design and alignment. Adjustments have been made to the CSS and HTML structure to eliminate the unwanted text and ensure a clean, consistent appearance across the footer. This change improves the overall aesthetic and usability of the page. Please review the changes for approval.
Before:
After:
=>  Resolved the issue of extra text visibility below the social icons in the footer layout.

index.html
#1914 solved
This pull request resolves the layout inconsistency of the Contact page. Previously, the Contact page displayed differently than the Home page and other pages, which could confuse users. The necessary adjustments have been made to ensure that the layout aligns with the overall design and functionality of the site. This change enhances the user experience by maintaining a consistent look and feel across all pages. Please review the changes and let me know if any further modifications are needed.
https://github.com/user-attachments/assets/c19bc698-b39c-4e0d-b3cc-d04cbe147e16
=> Fix Contact Page Layout to Ensure Consistency Across All Pages

about.html
[style]: Fixing about page containers #1922
Updated margins and padding in the container of about page , fixing image ratios.
=> Fixing about page , made it more visible and better

about.html
issue_number: #1966 
Abour page footer alignment fix
Before:
After:
=> About page footer alinment fix

blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/Types-of-Stock-Investments-A-Quick-Guide.html, blogs/economic-trends-and-analysis.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/real-estate-economics.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
now ui of the blog content is enhanced
additionally i make the all blog content responsive for all devices
my issue no. is #1896
=> change the ui of the blog content

quiz.html
issue_number: #1967
quize page footer items alignment fix
Before:
After:
=> quize page footer alignment fiz

index.html
Reverts ayush-that/FinVeda#1960
=> Revert " Resolved the issue of extra text visibility below the social icons in the footer layout."

index.html, tools/sip.html
Issue_number: #1887 
alignment fix and extra text fix of footer of tool page
https://github.com/user-attachments/assets/d2f916cb-741a-4fe7-afa2-140f5c51cee8
=> Alignment fix and extra text fix in footer of tool page

README.md
resolves isssue #1938 
added hacktoberfest banner to the readme file.
none
updated readme file by adding the hacktoberfest banner under the heading "this project is now officially accepted for."
=> Update README added hacktoberfest banner. #1938

Finveda/Finveda/package-lock.json, Finveda/Finveda/package.json, about.html
[style]: Fixing section in about page #1975
Fixed the padding in the section for better visibility.
=> fixed margin and padding

careers.html
issue_number: #1968 
Carrier page alignment fix and extra text remove from bottom
Before:
After:
=> Carrier page alignment fix and extra text remove from bottom

index.html
Updated the contact logo..........which was looking irrelevant 
Before
After
=> Updated Contact symbol

Licensing.html, blogs/refund-policy.html
now ui of the refund policy and license section is improved
additionally i make it responsive for all device users
my issue no. is #1972
=> enhance the ui of refund policy + license section

about.html, trends.html
#1930 
1. added mouse trail to trends section
2. changed the trail type and colours in the about us section
=> Added trail to trends section. made the colours uniform

index.html
This feature embeds a **TradingView widget** into the web page along with a **finance-related image**. The widget dynamically fetches stock data and displays it, while the image is displayed alongside it in a fixed size (540px by 372px).
- **Improved User Experience:** Users will be able to see live stock data through the TradingView widget, providing them with up-to-date financial information.
- **Visual Enhancement:** A relevant image representing financial concepts has been added to enhance the visual appeal of the page.
- **Dynamic Content:** The widget automatically adapts to the container, providing responsive content.
- **Finance Learning Modules:** The widget helps learners track live market updates, aiding in financial education.
- **Financial Dashboards:** This widget can be …
=> Embed TradingView widget and image

index.html
issue_number: #2000 
home page footer extra text fix
Before:
After:
=> home page footer extra text fix

ContactUs.html, index.html
issue_number: #1970 
Contact page footer fix alignment and 3d hover effect in social media icons
https://github.com/user-attachments/assets/07021567-afa3-48c6-b37c-fcfda73e8b48
=> Contact page footer fix alignment and 3d hover effect in social media icons

assets/css/quiz.css, quiz.html
Fixed quiz bar unnecesarry color gradient
https://github.com/user-attachments/assets/deae46c1-cc35-4ce5-b241-4474d9616202
=> Quiz page enhanced

assets/css/index.css
created issue:
#1989 
fixed issue :
#1989
enhance subscribe container ui to match the homepage ui similarly
before update : 
after update :
=> updated subscribe container 

tools/sip.html
issue_number: #1965 
Added multiple language support  system in tool page
Before:
After:
=> Added multiple language support to tool page

about.html, index.html
issue_number: #2014 
i am added some style to to scroll up button
Before:
After:
https://github.com/user-attachments/assets/a9c7b324-bb06-42dd-87b9-19072ba9a6fa
=> Scroll up button style Enhanced

ContactUs.html
Resizing the subscribe button in newsletter section which was overlapping with text area in the form.
None
[The subscription box in the project’s newsletter section needed adjustments to improve its visual presentation and responsiveness. Originally, the box was relatively narrow, limiting its usability and aesthetic appeal, particularly on larger screens. To enhance the user experience, I expanded the subscription box’s width by adjusting the column proportions, allocating a larger portion to the content and form sections. Additionally, I updated the container’s maximum width in the CSS to allow the subscription area to span more horizontally across the page. These changes ensure a more user-friendly design, giving the subscription box a balanced and visually engaging look on both …
=> Fixed the subscribe button in newsletter section which  was overlapping with text area in the form. 

index.html, visi.css
Hello, PR
Fixed issue - #2047
Add new feature - Translation Tool all language done
=> Add a Translation Tool all language done ! #2047

public/sitemap.xml
=> addition of sitemap

careers.html, index.html
=> Navbar  and link problem solved

index.html
@Sampadatiwari please review andd merge it
before
after
=> Fixed Footer in Homepage

about.html, assets/css/about.css
#2037 
Changed About us page background according to theme.
Before: 
After: 
=> Change About Us Page Background on dark theme

assets/js/quiz_modify.js, quiz.html
This pull request addresses the button input behavior on the quiz page. It implements a distinct "chosen" state for the answer buttons to improve user experience and visual feedback when an answer is selected.
- **Added Chosen State**: Implemented a new CSS class `.chosen` that applies a different gradient to the button when it is selected.
- **Updated JavaScript**: Adjusted the button selection logic to add the `.chosen` class to the selected button.
https://github.com/user-attachments/assets/1aa742fb-33ad-43c8-bf27-9982a3460a96
- Closes #1957
=> [FIX] Button Input behaviour Fixed on Quiz Page

assets/css/index.css, tools/sip.html
Subscribe area of All the pages are fixed , extra footer text removed
Before
After
=> Subscribe area fixed

ContactUs.html, about.html, assets/css/index.css, blog.html, careers.html, contact.html, index.html, quiz.html, tools/sip.html
fixing issue : #2092 
closes issus : #2092 
change theme of subscribe container according to website theme
=> change theme of subscribe container

tools/sip.html
Closes #2069
Enhanced version of income tax calculator is embedded
Really happy to merge this pull request.
=> Enhanced Income taxt Calculator

tools/sip.html
now ui is enhanced while keep the design same 
make the tool bar responsive for mobile,mac's and ipad
bugs:- solve the overlapping issue in the tool section's calculator
=> enhanced ui of tool section and make it responsive and solve some overlapping bugs

faq.html
Solved #2080
Improved the functionality of submit Feedback button , now on clicking submit feedback button an alert stating the your feedback has been submitted successfully pop out and input fields got cleared.
https://github.com/user-attachments/assets/ba344edb-e179-4074-a2a2-46f4a40c297a
=> solved issue #2080

tools/sip.html
issue_number: #2100
extra text fix in tools page
Before:
After:
=> Extra text fix in tools page

footer.html, index.html
[None]
I have changed the following to improve the alignment in the footer section:
1. added the row css
2. changed the justify-content-center to justify-content-left
3. added the missing ul tag
Before:
After:
=> Alignment in footer section

blog.html, index.html
issue_number: #2119
blog page image fix
Before:
After:
=> Blog image fix

careers.html
Fixes:  #(#2073 )
so basically i just MANIPULATE the  "CAREER ROADMAP" SECTION   IN CARRERS PAGE which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- content is also visible now which is not  visible before my designing.
- add border for interactive user interface
- redesign the whole section
- change the size CARDS AND ALO GIVE MARGIN-PADDING WHICH GIVE INTERACTIVE INTERFACE
- ADD …
=>  UI IMPROVEMENT IN CAREER ROADMAP #2073

contact.html
fixes: https://github.com/ayush-that/FinVeda/issues/2012
Corrected!
=> Removed the overlapping.

careers.html
Fixes:  #(#1507)
so basically i just MANIPULATE the  "Jobs in Finance" SECTION   IN CARRERS PAGE which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- give the colors which is in the support of website theme
- resize the header size
- add colorful border for interactive user interface
- redesign the whole section
--BEFORE:- …
=>  UI IMPROVEMENT IN Jobs in Finance SECTION #1507

blogs/refund-policy.html
- **Card Layout**: Organized the content into cards for better readability and structure.
- **Hover Effect**: Added hover effects to the cards for an improved user experience.
- **Text Color Correction**: Corrected the text color to ensure visibility against the background, addressing the issue of white text not being visible.
fixes: #2005 
Kindly assign me to Level 2 for this task; I would be grateful for the opportunity.
=> Refund Policy Page Updates

blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html
**Title:** Add Card Format for Strategies to Handle Unknown Risks
This pull request introduces a card format to highlight each strategy for dealing with unknown risks in life and investing. The following changes were made:
- Added a card layout for each strategy point to improve readability and visual appeal.
- Implemented a hover effect on the cards for an interactive user experience.
- Updated the overall styling to maintain a clean and modern look.
**Changes:**
- Modified HTML structure to encapsulate each strategy in a card.
- Added CSS styles for card layout, hover effects, and overall aesthetics.
**Reason for Change:**
The changes aim to enhance the user experience by making the content more engaging and easier to digest. This format allows readers to focus on each …
=> Add Card Format for Strategies to Handle Unknown Risks

Licensing.html, blogs/terms-of-service.html
In this update, I have enclosed the content of both the Licensing and Terms of Service pages in visually appealing cards with a hover effect, improving the overall user experience compared to the previous plain text format.
These enhancements not only make the information more engaging but also provide a clearer structure for users.
- Created a new card layout for each section.
- Set a consistent background color for cards.
- Adjusted border-radius for a smoother appearance.
- Implemented a hover scale effect for interactivity.
- Added transition duration for smoother hover effects.
- Increased font size for better readability.
- Aligned text within cards to the center.
- Defined padding for cards to improve spacing.
- Updated link styles within cards for better visibility.
- Removed …
=> Enhancements to Licensing and Terms of Service Pages

faq.html
Fixes:  #(#1733)
so basically i just MANIPULATE the  "FEEDBACK" SECTION IN HELP PAGE  which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- give the colors which is in the support of website theme
- resize the feedback size
- add colorful border for interactive user interface
- redesign the whole section
--BEFORE:-
---AFTER:-
=> UI IMPROVEMENT IN "FEEDBACK" SECTION IN HELP PAGE #1733

index.html, resources/resources.html, resources/script.js, resources/styles.css
Fixes: #1778 
Create a Resource Library that allows both user contributions and admin curation, providing a diverse collection of educational materials, career guides, and skill-building resources for users.
1. User Authentication and Role-Based Access
- User login functionality
- Display of logged-in user information
- Role-based access control (admin vs. regular user)
2. Resource Management System
- Display of approved resources in a responsive grid layout
- Resource submission form for users to add new resources
- Categories for resources (Educational Materials, Career Guides, Skill-Building Resources)
- Local storage for saving and loading resources
3. Search and Filter Functionality
- Real-time search functionality for resources
- Category-based filtering of resources
- Infinite …
=> Created Collaborative Resource Library with Contributor System

assets/css/index.css, assets/css/trends.css, index.html, trends.html
fixing issue:  #2170 
fixing issue : #2095                       
closes issues: #2170 
closes issues : #2095 
footer widget is not properly covered screen width 
theme change on trend page black and white
before update the footer :
after the update :
Uploading Screen Recording 2024-10-27 102416.mp4…
for theme : 
Uploading Screen Recording 2024-10-27 123425.mp4…
=> fixing footer

index.html, reviews.html
Fixes: #1776 
Implemented a system for user-generated content and reviews to enhance user engagement and provide valuable information to our community.
1. Navigation & Header
- Responsive navbar with navigation links
- Company logo/icon
- Login/Register button
- Dark/Light theme toggle
- Progress bar showing scroll position
2. Authentication System
- Login Modal:
- Username/password fields
- Remember me checkbox
- Forgot password link
- Social media login (Google, Facebook, Twitter)
- Registration Modal:
- Email, username, password fields
- Password strength meter
- Password visibility toggle
- Social media signup options
3. Financial Success Stories Section
- Story submission form with:
- Success story title
- Category selection
- Journey description
- Image upload
- Story gallery …
=> Implement User-Generated Content and Reviews 

blog.html
Fixes #2140
This PR resolves the issue of inconsistent size and alignment of the heading image in the blog post section. It ensures that the images are uniformly styled and aligned correctly with the blog post headings, providing a consistent user experience.
The fix enhances the visual presentation of blog post heading by ensuring the heading image is consistently sized and aligned across different posts.
@ayush-that @sampadatiwari30  please consider assigning me label of gssoc-ext level2 and hacktoberfest-accepted, once the PR gets successfully merged.
=> Fix Inconsistent UI of Heading Image in Blog Post

about.html
Fixes #2144
This PR addresses the inconsistent size and alignment of the image in the "Our Contributors" section on the About Us page. The update ensures that the images are uniformly sized and aligned properly, providing a consistent and cohesive user experience.
The bug fix ensures a consistent visual presentation across different screen sizes, improving the overall layout of the about us section by fixing the image alignment.
@ayush-that @sampadatiwari30  please consider assigning me label of gssoc-ext level2 and hacktoberfest-accepted, once the PR gets successfully merged.
=> Fix Inconsistent UI of Our Contributors Image in About Us Page

assets/css/style.css, trends.html
now issue darkMode btn issue resolved for mobile and mac's
https://github.com/user-attachments/assets/253d1142-0d77-49bc-b9c5-543eee1aa8b2
my issue no. is #2129
=> trends section darkMode for mobile and mac's resolved

assets/css/cookiepopup.css, assets/css/preloader.css
Reverts ayush-that/FinVeda#2178
Removing the Cookies option as it is fixed and no button is working
=> Revert "[Feature] Implement Cookie Consent Banner on Homepage"

README.md
I've implemented a star history graph in the README file that will automatically update. This addition provides a visual representation of the project's popularity over time, enhancing the documentation.
Kindly review and merge this update. Thank you!
fixes: #2199
=> Added STAR HISTORY GRAPH to README

blog.html
This PR implements scroll-triggered animations on the blog page, enhancing user engagement and adding a dynamic feel to the browsing experience. By utilizing the AOS (Animate on Scroll) library, various elements now animate as the user scrolls down, providing a smooth and visually appealing transition between sections. These animations improve the page's visual hierarchy and draw attention to key content areas, creating a more interactive and immersive reading experience.
issue  #2186  fixed 
https://github.com/user-attachments/assets/91ffc990-82e5-4b39-a821-82276d6a1863
=> Animation on scroll  on blog page

finance.html
#2174 fixed
This pull request resolves the footer layout issues on the Course page, where elements were previously unstructured and misaligned. The updated layout aligns with the styling of other pages for a consistent and polished user experience. **Additionally, a progress bar has been added to enhance navigation and provide a visual indicator of user progress on the page.** This update ensures that users have a cohesive and improved experience across all sections.
Before :
After : 
https://github.com/user-attachments/assets/b20a354a-de1a-4cd2-8539-3087c3215a8f
=> Fix misaligned footer layout on course page for consistent design

tools/sip.html
now footer link is working for tools section 
https://github.com/user-attachments/assets/a82ef278-13b9-4540-953d-84f145445708
my issue no. is #2217
=> now footer link is working for tools section

faq.html
Fixes:  #(#2185)
so basically i just MANIPULATE the  Recommended Books on Finance" IN CARRERS PAGE   which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- give the colors which is in the support of website theme
- resize the CONTAINER size
- add colorful border for interactive user interface
- redesign the whole section …
=>  UI IMPROVEMENT IN "Frequently Asked Questions" in FAQ page. #2185

index.html
- Fix: Add placeholder text to the name field in the feedback form
- This pull request addresses a minor usability issue in the feedback form located on the main page of the FinVeda application.
**Changes Made :**
- Added Placeholder Text: Introduced placeholder text in the name input field of the feedback form. The placeholder now prompts users with a clear indication of what information is expected (e.g., "Enter your name").
**Rationale :**
- Visual Improvement: The addition of placeholder text enhances the visual appeal of the form by providing a clearer context for users.
- Usability Enhancement: By guiding users on what to input, the placeholder text improves the overall user experience, reducing confusion and potential input errors.
- Before solving issues : -
- After solving the …
=>  Fix: Add placeholder text to the name field in the feedback form.

finance.html
issue #2218 solved
This PR implements scroll-triggered animations on the courses page, enhancing user engagement and adding a dynamic feel to the browsing experience. By utilizing the AOS (Animate on Scroll) library, various elements now animate as the user scrolls down, providing a smooth and visually appealing transition between sections. These animations improve the page's visual hierarchy and draw attention to key content areas, creating a more interactive and immersive reading experience.
https://github.com/user-attachments/assets/686f1d50-f1c4-4110-8266-6444cf3e8189
=> Animation on scroll on courses

loginPage.css, loginPage.html, passwordRecovery.html
#2128
This PR introduces the password recovery feature, enabling users to reset their passwords via an OTP sent to their registered email. It includes:
A "Forgot Password" option on the login page.
https://github.com/user-attachments/assets/5cdf9103-d66b-4d57-9aff-c642f3883795
- [X ] I have read and followed the Contribution Guidelines.
- [ X] …
=> Integrating the password recovery

index.html
now darkMode btn is show and working for small screen and medium screen.
https://github.com/user-attachments/assets/c9a0e133-4122-4c64-930e-53a9cc8cfe04
my issue no. is #2224
=> added the darkMode in navbar for small and medium screen on home page

index.html
This pull request improves the SEO and meta tags in the `<head>` section of the FinVeda project. The changes include:
- Removed duplicate `<meta>` tags for `viewport` and `description`.
- Added `og:image` and `twitter:image` meta tags for better social sharing visuals.
- Ensured consistency in the use of forward slashes for file paths.
- Verified and corrected the URL for the logo in the structured data.
- Organized CSS file links for clarity and potential performance improvement.
These enhancements aim to improve search engine visibility and user experience when sharing the site on social media platforms.
- Updated meta tags for SEO.
- Added structured data for better indexing.
- Cleaned up the `<head>` section for consistency.
Kindly assign this PR level 2. 
Thank you!! 
fixes: #2197
=> Improve Meta and SEO Tags in FinVeda

assets/css/sip.css, tools/sip.html, tools/sipcalculator.css
fixing : #2093 
closes : #2093 
improve the theme on tools page for the website
=> fixing theme on tool page

careers.html
**Issue Fixed:**
The text in the search bar was blending with the background, making it difficult for users to see and use effectively.
**What Changed:**
- Adjusted the text color in the search bar to ensure clear visibility against the background.
**Expected Outcome:**
Users can now easily identify and use the search functionality without any visibility issues.
Please let me know if any further changes are needed. Thank you!
fixes: #2193
=> Fix Search Bar Text Visibility

finance.css, finance.html
issue #2221 fixed
Mouse cursor trail effect was not working on the courses page
This PR addresses an issue where the mouse cursor trail effect was not working as expected on the 'Courses' page. The effect was designed to create a trailing animation following the mouse cursor, adding a dynamic visual element to the page.
https://github.com/user-attachments/assets/cf154812-8d85-425e-b6bf-8a724e5d7137
=>  added Mouse cursor trail effect on courses

faq.html
I have implemented a dark theme for the FAQ section of the Finveda app. The following changes have been made:
- Updated the overall layout with a dark background and light text for improved readability.
- Changed label text to white for better visibility against the dark theme.
- Enhanced input fields and buttons with a consistent dark style.
- Adjusted the styling of the accordion items to match the new theme.
Please review the changes, and let me know if any further modifications are needed. I would appreciate it if you could assign this task to Level 2 or Level 3 based on its complexity.
Thank you!
fixes: #2196
=> Implemented Dark Theme for FAQ Section

index.html, navbar.css
=> Done with the changes 

index.html
issue_number: #2244 
in home page blog section one img is not visible
https://github.com/user-attachments/assets/d76ed1e4-c230-45aa-86e5-09732a70ee2e
=> Home page blog section img fix

finance.html
Fixes:  #(#2200)
so basically i just do  the UI ENHANCEMENT IN COURSES PAGE   which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
-  redesign cards
- give new background colors
- eye comfort background colors
- add hover effects
- add transitions for smooth user interface(UI)
--BEFORE:-
---AFTER:-
=> UI ENHANCEMENT IN COURSES PAGE #2200

index.html
Fixes:  #(#2190)
so basically i just do  the UI ENHANCEMENT IN COURSES PAGE   which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
-  redesign feedback form
- try to match color with blog section 
- decrease padding and margin so that form looks handy and interactive.
- give new background colors
- eye comfort background colors
- add hover effects
- add transitions for smooth user interface(UI)
--BEFORE:-
---AFTER:-
=> UI IMPROVEMENT IN FEEDBACK FORM OF HOME PAGE #2190

blog.html
now darMode btn is showing and workking for small and medium screen in blog section.
https://github.com/user-attachments/assets/60a8f449-ce4d-4baa-b68b-283e4b0d36e3
my issue no. is #2264
=> added darkMode btn in blog section for small and medium  screen

about.html
#2248 
IT LOOKS LIKE I DON'T ADD MUCH THINGS IN THIS SECTION BUT IF YOU FOCUS AGAIN YOU WILL KNOW THAT I WILL ADD:-
- NEW BACKGROUND COLORS
- CARDS LOOKS MORE SMOOTHER THAN OLDER ONES (BECAUSE OF TRANSITIONS )
- NEW HOVER EFFECTS (ON CARDS and ONE BUTTONS )
- ADD BORDER WHICH HELPS TO IMPROVE USER INTERFACE(UI).
KINDLY GIVE "LEVEL2" LABELAS KNOW THIS SECTION LOOKS SMOOTHER THAN THE OLDER ONE.
BEFORE:-
AFTER:-
=>  UI ENHANCEMENT IN "OUR CONTRIBUTORS SECTION" #2248

tools/sip.html
issuse_number: #2273 
Fix the button styled in tool
Before:
After:
=> Fix Button styled in tool

quiz.html
Closes #2215 
I have well aligned the below quiz section(in picture) for the mobile version...added screenshots below..
Before:
After:
@ayush-that @sampadatiwari30 Kindly review the PR and add hacktoberfest, gssoc and level labels..
- [+ ] Bug fix
- [ +] I have performed a self-review of my code
- [+ ] I have read and followed the Contribution Guidelines.
- [ +] I have tested the changes thoroughly before submitting this pull request.
- [+ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [+ ] I have commented my code, particularly in hard-to-understand areas.
=> Updated quiz section for mobile version

tools/sip.html
Closes #2210
Changed the alignment of newsletter section in the tools page..
Before:
After:
@ayush-that @sampadatiwari30 Kindly review the PR and add hacktoberfest, gssoc and level labels..
=> Updated tools newsletter alignment

contact.html
issue_number: #2276 
i have added missing logo in footer of `Contact` page
Before:
https://github.com/user-attachments/assets/47367835-887c-45b0-9f88-50ba7d0d7c7d
After;
https://github.com/user-attachments/assets/ca592386-9e58-4d21-9e44-db0d25689fba
=> Logo added missing footer

reviews.html
navbar is added  for small and medium screen for review section
my issue no. is #2268
=> added navbar for medium and small screen in review section

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/pull_request_template.md
Closes #2223
- I have enhanced the GitHub issue template by adding distinct sections for features, bug fixes, and documentation updates. 
This provides contributors with clear guidance on how to categorize their contributions, ensuring better organization and 
clarity in project management.
- The pull request template has also been refined to align with the new issue structure. This includes prompts for contributors 
to summarize their changes effectively, highlight major enhancements, and confirm adherence to project guidelines.
- These modifications streamline the contribution process, making it easier for maintainers to review submissions and for 
contributors to present their work comprehensively. This ultimately enhances collaboration and the overall quality of the 
project.
- Chore …
=> Changed the ISSUE TEMPLATES and Pull request template !!!

quiz.html
Fixes:  #(#2250)
so i redesign the whole section and try to give it a designing according to our website theme i which i manipulate html and css files 
AS I ADDED:-
-  background theme color
- add borders for better ui
- change image positions
- -redesign whole section
-  add transitions
--BEFORE:-
---AFTER:-
=> UI IMPROVEMENT IN QUIZ PAGE #2250

blog.html
Fixes:  #2253
so i redesign the whole section and try to give it a designing according to our website theme in which i manipulate html and css files 
AS I ADDED:-
- new designing approach
-  background theme color
- add borders for better ui
- change image positions
- -redesign whole section
-  add transitions
--BEFORE:-
---AFTER:-
=> UI ENHANCEMENT IN BLOG CARDS #2253

assets/css/bootstrap.min.css, assets/css/style.css
Hello, PR
fixed issue - #2258
before-
=> Fixed tools page issue ! #2258

Licensing.html, about.html, careers.html, contributors.html, finance.html, index.html, reviews.html
now navbar misalign for small and medium screen is resloved.
additionally i add the darkMode btn for small and medium screen for some pages.
https://github.com/user-attachments/assets/a35e389a-fb58-46e3-ba1a-4c854b1d3f8b
my issue no. is #2280
=> solve the navbar misalign for small and medium screen for all pages

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html
Fixes:  #2292 #2294 #2295 
Basically i enhance the designing of the privacy , refund and licensing page 
AS I ADDED:-
- new designing approach
- add new font style
- add shadow effects
- add new gradient colors
- bold font where needed
- enhance designing of headers
--BEFORE:-
---AFTER:-
=> ENHANCE PRIVACY POLICY,LICENSING PAGE,REFUND POLICY

tools/sip.html
Fixes: #2282
- Aligned nav Bar to the top ensuring all elements to stay within the  nav bar.
- elements are now at center of nav bar
@deepeshmlgupta @sampadatiwari30
=> Updated Nav Bar Of `Tool` Section

about.html
Fixes:  #2291
so i redesign the whole section and try to give it a designing according to our website theme in which i manipulate html and css files 
AS I ADDED:-
- new designing approach
- ADD BOUNCING EFFECTS
- ADD CARDS HEADING
- ADD MORE LITTLE THINGS WHICH ARE NOT MAKE HUGE IMPACT BUT IT IMPROVES INTERFACE HOWEVER A LITTLE BIT.
--BEFORE:-
---AFTER:-
=> UI IMPROVEMENT IN A SECTION WHICH PRESENT IN ABOUT PAGE #2291

about.html
Fixes: #2323 
in About Us page in bottom of footer restoe styled of a footer items links to looks the footer similar to other page
Before:
After:
=> Added styled in footer items

Licensing.html, about.html, blog.html, careers.html, contributors.html, finance.html, index.html, quiz.html, reviews.html, trends.html
darkMode icon issue in large screen is now solved for all pages.
https://github.com/user-attachments/assets/a09f9f13-f26b-49b8-ba6c-2fd5bc322744
my issue no. is #2318
=> solve darkMode icon issue for large screen in all page

quiz.html
Fixes: #2342 
in the quiz page the quiz box the button option of questions are not aligned properly in hover effect they are going outside the box in this pr i am fix this and make the quiz box more decorated.
=> Quiz box alignment Fix

blog.html
Fixes: #2338 
In blogs page overlapping fix of blog-pic with blog cards it will enhanced the visiblity of your blog page
Before:
https://github.com/user-attachments/assets/590ec740-1dcb-48d3-a2d8-feabed68afda
After:
https://github.com/user-attachments/assets/0921ffa6-b88c-4f32-bdb8-a03b9d41e2e7
=> blog-pic overlapping fix with blog cards

tools/sip.html
Fixes: #2335 
Multiple footer fix in tool page
Before:
After:
=> Multiple footer fix in tool page

tools/sip.html
Fixes: #2333 
Updated the Navbar logo in tool page with new one which i provided all over the pages 
Before:
After:
=> Logo updated with new one in tool page navbar

tools/sip.html
Fixes: #2331 
Remove extra text from tool page 
Before:
After:
=> Extra text remove from tool page

loginPage.css
This pull request introduces enhancements to the input fields and buttons in the existing project. The changes aim to improve user experience and visual feedback during interactions.
- Added a subtle size increase effect to the entire input field, including the associated icon, on hover.
- Enhanced focus styling for input fields with new border color and box shadow.
- Increased the size of the **Login** and **Sign Up** buttons on hover to enhance interactivity.
- Implemented a hover effect on social media icons, slightly increasing their size for better visibility and engagement.
I would like to request this task to be assigned a **Level 2**  due to its significant impact on user experience and interface interactivity.
---
Thank you for considering this pull request!
fixes: #2195 
Output: …
=> Enhance Input Fields and Button Interactions

finance.css, finance.html, finance.js
Fixes: #2341 
- Implemented a circular "Scroll to Top" button with a centered and bold arrow for improved usability and aesthetics.
- Enhancements to the button's responsiveness and hover effects, making it visually appealing across different screen sizes.
- The changes enhance user experience by providing a clear and attractive way to navigate back to the top of the page.
- [] Bug fix (non-breaking change which fixes an issue)
- [] I am a participant of GSSoC-ext.
- [] This PR is submitted under the GSSoC program.
- [] I have taken prior approval for this feature/fix.
=> added scroll button to courses page

contact.html
Fixes: #2325 
Enhanced the style of the feedback button on the contact page to make it more reliable and adjustable to the feedback form, ensuring it looks professional.
Before:
https://github.com/user-attachments/assets/4d6bd1a2-d54c-41b2-ac5e-2a0fe63e1f9a
After:
https://github.com/user-attachments/assets/f08fe6ec-eb88-4582-b91e-be39cbb3250a
=> Button styled enhnaced in feedback form of Contact page

blogs/terms-of-service.html
Fixes: #2364 
in terms and condition page in navbar the logo should be updated one i will updated this logo in this pr also i  implement the functionality of clicking the logo it will return the home page
Before:
https://github.com/user-attachments/assets/5fb32f5f-f049-41ff-8cd1-b20dbd72be77
After:
https://github.com/user-attachments/assets/1e931ba4-7cc4-412d-a78b-e8941f70f61a
=> terms and condition page navbar logo update

blogs/sitemap.html
Fixes: #2362 
in site map page in footer section the logo should be added i am added this logo to this page footer
Before:
https://github.com/user-attachments/assets/4dc1c324-c26d-43d6-b6c6-3c9a8c32fe82
After:
https://github.com/user-attachments/assets/a06bc639-27cc-45c8-9fdf-51496ff88edd
=> Logo added in footer of site map page

about.html, blog.html, careers.html, contact.html, finance.html, index.html, quiz.html, trends.html
Fixes: #2348
as i provide "MAPS" option in navbar which help user to easily navigate to the maps page with ease , "I WILL DO THIS ON ALL PAGES INCLUDING:- HOME,ABOUT,TRENS,TOOLS,BLOG,QUIZ ,CONTACT,COURSES,HELP"
CURRENT DESIGNING:-
=> NO OPTION TO NAVIGATE ON "MAP" THROUGH NAVBAR #2348

blogs/privacy-policy.html
Fixes: #2368 
in your privacy policy page in navbar the logo should be updated one i am updated this logo with a clickable functionality
Before:
https://github.com/user-attachments/assets/1859be22-6099-41f8-b3ed-6a5d1f7b88a9
After:
https://github.com/user-attachments/assets/f36be3b2-43db-4794-beec-e1b81f3dea38
=> privacy policy page in navbar logo update

blogs/refund-policy.html
Fixes: #2366 
in refund policy page in navabr the logo should be updated one i will updated this logo also add funcnitionlity to retun home page
Before:
https://github.com/user-attachments/assets/219bf937-8eeb-4b7d-8927-301a7aefa2a6
After:
https://github.com/user-attachments/assets/a7fbc950-8067-4532-affa-cb2990553199
=> refund policy page logo update

index.html
Fixes: #2287 
This update addresses an issue where the scroll-triggered animations in the blog section do not activate when the blog page is displayed as a section on the home page. Users expect engaging animations to trigger as they scroll through the content, but the animations were previously static and unresponsive, leading to a lack of visual interest and interactivity.
the scroll-triggered animations now function correctly, providing a dynamic and engaging experience for users as they interact with the blog section on the home page. 
https://github.com/user-attachments/assets/9b71b1a2-b00c-4ea6-9254-66aba726b546
=> Fix Scroll-Triggered Animations in Blog Section on Home Page

blogs/sitemap.html
Fixes: #2357 
in Site Map page i am updated the logoi n navbar also i implement the functionality that when we click on logo it will give you home page 
Before:
https://github.com/user-attachments/assets/a465fa9d-80ce-47f4-b484-6c558b63630a
After:
https://github.com/user-attachments/assets/8c5aeec0-51fd-4567-b0bc-fa2c02cd7fd6
=> Site map page navbar fix

assets/css/slick.css, tools/sip.html
Fixes: #2091 
Changes layout and design of Tools page design.
=> Enhance the Tools Page Section

assets/css/index.css, finance.js, index.html
Fixes: #2337 
Added a discussion forum for Increased User Engagement
Advantages of a Discussion Forum for FinVeda:
Increased User Engagement: Fosters community and interaction.
Improved Brand Loyalty: Builds trust and strengthens the brand.
Valuable User Insights: Gathers feedback for product improvement.
please assign under level 2
=> Added a discussion forum

index.html
Fixes: #2370 
in your website in home page footer multiple links fix 
Before:
After:
=> Multiple links fix in home page footer

index.html
Fixes: #2379 
in home page at the very bottom there is extra text occur i w am fix in this pr
Before:
After:
=> Extra text remove from bottom of footer in home page

about.html
Fixes: #2269  
This PR resolves the overflow and misalignment issues within the "About Us" card by containing and aligning the content appropriately. The layout has been adjusted to prevent text and elements from extending beyond the card’s boundaries, enhancing the visual consistency and readability of the "About Us" section.
@ayush-that @sampadatiwari30 Please consider assigning me label of gssoc-ext level2 and hacktoberfest-accepted, once the PR gets merged.
=> Resolved Overflow and Misalignment in "About Us" Card Layout

about.html, assets/css/about.css
Contributors section fixed with smoother animation
https://github.com/user-attachments/assets/c3bab9fe-a530-4a71-98c9-82be1ed78c1c
=> Contributors page fixed

index.html
@Sampadatiwari @deepeshmlgupta please review and merge it
before 
after
=> Fixed Disscusion Form in Home Page

maps.html
Fixes:  #2350
AS I ADD NEW SECTIONS LIKE  "WHY EVERY STATE HAVE DIFFERENT LITERACY RATES"  AND AFTER THAT FEEDBACK FORM AND AFTER THAT QUIZ SECTION.
SECTION IMAGES:-
=> ENHANCEMENT IN MAP PAGE #2350

maps.html
Fixes:  #2349
as i resolve the bug which is belongs to absence of navbar in maps page.
BUG RESOLVED:-
=> NAVBAR IS NOT PRESENT AT MAP PAGE #2349

quiz.html
Fixes: #2263
- Removes the hero section from the quiz page to ensure that it only appears on the homepage.
- Enhances the user experience on the quiz page by removing irrelevant content, keeping the page focused on quiz functionality.
@ayush-that @sampadatiwari30 Please consider assigning me label of gssoc-ext level2 and hacktoberfest-accepted, once the PR gets merged.
=> Removed Unnecessary Hero Section from Quiz Page

index.html
Fixes: #2267  
This PR updates the description text color in the hero section to white, enhancing readability and improving the user experience. The previous black text was hard to read against the dark blue background, and changing it to white creates better contrast and visual appeal.
@ayush-that @sampadatiwari30 Please consider assigning me label of gssoc-ext level2 and hacktoberfest-accepted, once the PR gets merged.
=> Updated hero section text color

loginPage.html
issue no. #2135
https://github.com/user-attachments/assets/2933a211-5d52-471b-b725-fa9f13e954b6
=> added show/hide feature for password at sign-in page.

Licensing.html, about.html, assets/css/index.css, assets/css/style.css, contact.html, contributors.html, finance.html, index.html, maps.html, trends.html
Home page layout fixed
https://github.com/user-attachments/assets/ca218fa5-66e2-466c-837f-ac9b577b9a4c
=> Home page fixed

faq.html
Fixes: #2393 
Changed the background to white and fixed css so the text looks visible in FAQ page.
BEFORE: 
AFTER:
=> Changed the background to white in FAQ page.

tools/sip.html
Fixes: #2247 
#2386 Updated the UI of the each calculator
**_ADD tag of HACKTOBERFEST and GSSOC-EXTD_**
previous one
Updated SS
- [No] I have taken help from some online resources.
- [No] I have added documentation to explain my changes.
=> Feature/tools UI

.vscode/settings.json, about.html, index.html
Fixes: #2414 
in home page the footer is missing i am added exactly same footer with same functionality
https://github.com/user-attachments/assets/ab42c5c9-eec2-46c9-8207-6f86a7a72169
https://github.com/user-attachments/assets/d5c9dab9-aefc-414e-b339-1679ecf06d7b
=> Missing footer added in home page

tools/sip.html
Fixes: #2416 
in tools page there is multiple footer occur i am fix this multiple footer i am not only fix this also keep their functionality same 
https://github.com/user-attachments/assets/e0fd6c23-2f8a-44d9-9d33-0df5b5525799
https://github.com/user-attachments/assets/d0c10a21-a802-4674-9dfc-c882b3f0ea76
=> Multiple footer fix in tools page

loginPage.css
Hello, PR
Fixed Issue - #2434
Done -
=> Fixed Login & Signup page issue ! #2434

contact.html
**Title:** Improve Visibility of Contact Info Text
**Description:**  
This PR enhances the visibility of the contact information section by updating the text color of `<strong>` elements. The text is now set to navy blue, improving contrast against the background and ensuring it stands out for better readability.
**Changes:**
- Updated the color of `<strong>` elements to navy blue (#001f3f) for better visibility.
- Applied a smooth transition effect for hover states, enhancing user interaction.
**Reason for Change:**  
Previously, the text blended into the background, making it difficult to read. This change significantly improves the clarity and accessibility of the contact information, making it more user-friendly.
fixes: #2192
=> Improve Visibility of Contact Info Text

finance.html
**Title:** Add Hover Effect to Course Cards
This PR implements a hover effect for the course cards in the application. The following changes have been made:
- Enhanced the `.course` class to include a growth effect on hover, increasing the card size by 10% and adding a slight upward lift.
- Added a box shadow to create a floating effect when hovering over the cards.
- Improved the button hover state with a light gray background and a slight scaling effect for better user interaction.
These changes aim to enhance the visual appeal and interactivity of the course cards, providing a better user experience.
**Preview:**
- Hovering over a course card will now cause it to grow in size and elevate slightly, along with a change in the button style.
fixes: #2329
=> Courses card Enhancement

index.html, tools/smoothScroll.js
Fix #2388
- Sets the initial visibility of the scrollTop button to hidden, improving the overall user interface by reducing clutter.
- The button becomes visible only after scrolling down more than 100 pixels, enhancing usability and encouraging seamless navigation back to the top.
@sampadatiwari30  
Pls assign me, give me labels like gssoc-extd, hacktoberfest-accepted, and level.
=> Enhanced ScrollTop Button Functionality

loginPage.html
Hello, PR
Fixed Issue - #2440 
Done -
Before -
=> Fixed password section issue in Login page ! #2440

about.html, assets/css/about.css, assets/js/about.js, faq.html
Fixes: #2398 
- Implemented infinite card scroll 
- Update color of next/prev button
=> Update Card-Carousel and Next/Prev Button in Dark Theme

contact.html
Fixes: #2430 
I have changed the UI of the get in touch section of contact page
=> changed get in touch ui

assets/css/about.css
This PR introduces responsive design enhancements to the webpage, ensuring a better user experience across various screen sizes.
- **Added Media Queries**: Implemented CSS media queries to adjust the layout and font sizes for different screen widths:
- **For screens up to 1200px**: 
- Reduced font size in the footer.
- Made contributor cards full width for better layout.
- **For screens up to 768px**: 
- Further reduced font size in the footer.
- Adjusted margins for contributor cards for improved spacing.
- **Back to Top Button**: 
- Ensured the button is fixed in position and responsive in size and padding.
- Added hover effects for improved user interaction.
- Improved readability and usability on smaller screens.
- Enhanced visual layout for contributor cards.
- Increased …
=> Enhance Responsiveness of Webpage

Testimonials.html, about.html, faq.html, tools/sip.html
Fixes: #2312
- Feature: Implements a successful redirection feature that directs users to the intended page or resource based on specific conditions or inputs.
- Major Changes: Adds routing logic and validation to ensure users are redirected accurately and securely to the desired endpoint.
- Impact: Enhances user experience by improving navigation flow and reducing friction during transitions between pages or features.
=> Redirection is successfull !!!

Testimonials.html, about.html, faq.html, tools/sip.html
Fixes: #2310 
This PR introduces an icon enhancement across all pages of the project.
- **Feature Addition**: An icon has been added to enhance the visual appeal and user experience on all pages.
- **Major Changes**: The addition of the icon not only beautifies the interface but also helps in better navigation and brand recognition.
- **Project Enhancement**: This change contributes to a more polished and professional look for the project, improving overall usability and aesthetic appeal.
The motivation behind this change is to improve user engagement and provide a cohesive design across the application. 
No new dependencies are introduced with this change.
=> Added icon in the title for all pages !!!

Testimonials.html, about.html, faq.html, tools/sip.html
Fixes: #2311
- Feature/Bug Fix: Briefly describe the feature or fix you implemented.
- Major Changes: Highlight any substantial updates or added functionality.
- Impact: Explain how it enhances or impacts the project, including benefits or potential limitations.
#AFTER:
=> Improving the UI of cards !!

a_loginPage.html
Fixes: #2424
make the sign up page responsive 
the sign up page wasn't responding even after filling the credentials so this PR make the page responsive.
Before: 
After:
=> a_loginPage.html added

tools/sip.html
Fixes: #2464
The redirection functionality for all pages under the Tools section has been successfully implemented. Users can now navigate seamlessly to their desired tools without any issues, enhancing the overall user experience.
https://github.com/user-attachments/assets/5d841b1c-186f-48bd-92d4-a7889f1154b4
Uploading 123.mp4…
=> Successful Page Redirection for Tools Section!

faq.html
=> Fixed text misalignment issue in help page ! #2447

index.html
Fixes: #2455
Improved the color of the text under the "Explore" menu, Adjusting the text color to create a higher contrast with the background will enhance readability, ensuring users can easily find and interact with the menu items.
Initially the explore options textcolour was not visible.I highlighted the text colour to blue mapping with the theme of the webpage
https://github.com/user-attachments/assets/20180594-fdba-4bcc-9104-d604ca6c00c9
- [ X] I am a participant of GSSoC-ext.
- [X ] My code follows the style guidelines of this project.
- [X ] I have …
=> changed the text colour of explore option

tools/sip.html
Fixes: #2473 
currently there in the tool page there is multiple home section showing i am fix this
=> Tool page multiple Home navitems fix

tools/sip.html
Fixes: #2468 
in tool page multiple footer occurance i  am fix this
Before: 
After:
https://github.com/user-attachments/assets/4d75c5d4-9932-4fe7-9b13-da57c1594c85
=> In tool page multiple footer fix

maps.html
Fixes:  #2389
as i add footer in maps page
FOOTER ABSENT IN MAPS PAGE #2389
SECTION IMAGES:-
=> FOOTER ABSENT IN MAPS PAGE #2389

assets/css/style.css, maps.html
Hello, PR
Fixed issue - #2485 
done -
before -
=> Fixed subscriber our newsletter section issue in maps page ! #2485

quiz.html
The quiz page was messed up randomly.
It fixes the quiz page 
Before
https://github.com/user-attachments/assets/1edf715c-a52f-478b-8301-029ac288cb8e
After
https://github.com/user-attachments/assets/11102dfa-7fa3-4647-b4b1-d41c3fe356ba
=> Quiz page fixed

about.html
Fixes: #2497 
- Fix the bug in dark mode.
- Modify the UI of the cards.
- Auto slider in both modes
- Responsive section
- Add hover effect
- [No] Breaking change (fix or feature that would cause existing functionality to not work as expected)
**Previous - light and dark mode**
**Now - light and dark mode**
- [No] I have taken help from some online resources.
=> Bug Fixing in dark mode

assets/css/style.css
Hello, PR
fixed issue - #2495 
Before -
=> Fixed Navbar buttons misalignment issue in Licensing page ! #2495

faq.html
Fixes: #2483
the text here in the boxes is invisible both in light and dark modes....I've changed the color of the text enabling the visibility in both modes
this enhancement make user easier to view and reduced errors in the website
- [ X] Bug fix (non-breaking change which fixes an issue)
before
after
- [X ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [X ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
- [X ] …
=> The text is invisible in the FAQ section(fixes #2483)

assets/css/style.css, blogs/sitemap.html
The site map page was broken and i fixed the entire page.
Before
After
https://github.com/user-attachments/assets/59c1ae0e-4cc6-49bf-b5f1-f611d20ee3c4
=> Entire Sitemap page fixed

maps.html
This PR introduces significant enhancements to the **Financial Literacy** page, focusing on user engagement and visual appeal. The following changes have been implemented:
1. **Hover Effects on Header:**
- Added a smooth hover effect to the **Financial Literacy Rates** heading, changing the background to orange and text to white for better visibility.
2. **Center Alignment for Cards:**
- Centered the state resource cards on the screen for improved layout and focus.
3. **Card Hover Effects:**
- Implemented lift and shadow effects on state resource cards for a more interactive experience.
4. **Button Hover Effects:**
- Added hover effects to buttons in forms and quizzes, changing colors and slightly lifting the button on hover.
5. **Form Field Styles:**
- Enhanced form fields with hover …
=> Enhance UI for Financial Literacy Page

about.html
@Sampadatiwari @deepeshmlgupta please review and merge it in higher level
before
https://github.com/user-attachments/assets/483a801f-978c-4e0a-a381-cb8866cb477d
after
https://github.com/user-attachments/assets/57589f85-0e53-4a54-8987-9156c6a8dd69
=> Fixed About us page

careers.html
Fixes: #2527 
closes : #2527 
fixing footer quick links, resources , contact us links proper format  
https://github.com/user-attachments/assets/8c033f09-59d9-4e85-b047-c196c7529416
=> fixing footer links alignment

blog.html
This PR addresses the issue of insufficient text contrast by updating text colors across the site for better readability and accessibility.
- Adjusted text colors to provide improved contrast with background elements
- Reviewed and updated CSS styles in affected areas for consistency
These enhancements aim to create a more user-friendly experience, especially for users with visual impairments or those in low-light environments.
fixes: #2444 
Cards have better contrast colors.
=>  Improve Text Color for Enhanced Contrast and Accessibility

news/backend/app.py, news/backend/news_api.py, news/backend/requirements.txt, news/frontend/index.html, news/frontend/script.js, news/frontend/styles.css, news/readme.md
Fixes #2471
This PR introduces a new feature to the FinVeda application that provides users with real-time financial news and analysis. The integration consists of a Flask backend that fetches news articles from a reliable news API and a frontend that dynamically displays these articles on the website.
Key Changes:
1. Backend Implementation:
- Created a Flask API endpoint (/news-feed) in app.py to fetch financial news articles from the NewsAPI.
- Added error handling for API requests to ensure robust performance.
- Configured the application to use an API key securely.
2. Frontend Development:
- Developed an HTML structure in index.html to display the news articles.
- Implemented JavaScript functionality in script.js to fetch and render news articles dynamically.
- Added basic styling in …
=> FEATURE: Real-Time News and Analysis Feed

about.html, contact.html, finance.html, index.html, maps.html, quiz.html, tools/sip.html, tools/sipcalculator.css, trends.html
Fixes: #2538 
The navbar layout varies across different pages, leading to a disjointed user experience. This PR standardizes the navbar design, ensuring that all elements, including links and icons, are consistent on every page. Adjustments have been made to the styling and positioning of navbar components to maintain uniformity. This fix will improve the overall look and feel of the website, making navigation smoother and more visually cohesive for users.
https://github.com/user-attachments/assets/498214d8-69ee-407a-84d4-6bc7737708f9
=> Fix inconsistent navbar layout across different pages

loginPage.html
Fixes: #2535 
There was already a view passwords option then I didn't add eye icon i added hover effect to that button when user hover on that icon text will appear as click to view passwords 
https://github.com/user-attachments/assets/4aeaa1f6-246b-49dd-b887-166f372edd25
=> Hover text added to view password 

assets/css/quiz.css, faq.html, quiz.html
Fixes: #2540 
closes: #2540 
problem :  on help page by default theme is black when i tap the toggle button but not changes reflecting on screen
i solved this problem now currently proper work toggle button of theme
Uploading Screen Recording 2024-11-01 005259.mp4…
https://github.com/user-attachments/assets/4428bcbf-6521-4cf1-b922-71302d419fa7
=>  fixing theme on help page

assets/css/quiz.css, quiz.html
Fixes: #2539 
Fixes : #2542 
closes: #2539 
closes: #2542 
apply some css property and box shadow property and some changes in container widget
update favicon path
=> updated subscribe container

about.html
This PR addresses two main updates to enhance the overall user experience on the website:
1. **Favicon Addition**
- **Feature:** Added a favicon to the website.
- **Implementation:** Included the favicon link from the specified GitHub repository to ensure consistent branding and improve user recognition in browser tabs.
2. **Fix Display Errors on About Us Page**
- **Issue:** Resolved errors that were causing display issues on the About Us page.
- **Implementation:** Investigated the source of the errors and implemented necessary fixes to ensure proper rendering of content.
**Impact:**
These changes will improve the visual appeal of the website by incorporating a favicon, while also ensuring that the About Us page functions correctly, providing a seamless experience for …
=> Add Favicon and Fix Display Errors on About Us Page

faq.html
Fixes issue: #2557 
Closes issue: #2557 
improve Ui of FAQ page Container like FAQ form Contaiener , FAQ search Container  and submit feedback Container apply background color according website theme
=> update ui of FAQ page

assets/css/style.css, index.html, profile.html, testp.css, textp.js
Hello, PR
Add new feature -  #2562
Add a normal user profile page and a profile icon in the home page navbar that redirects to the profile page done -
https://github.com/user-attachments/assets/b137fa39-0bfc-4501-839d-a250380fab33
=> Add a User Profiles page done ! #2562

assets/css/faq.css, faq.html, maps.html
Fixes: #2569 
closes: #2569 
fixing navbar on map page according to another pages
before changes:
after changes:
=> Update with dipak

assets/css/faq.css, faq.html
Fixes: #2568 
closes: #2568 
fix the alignment of scroll button bottom right side position 
before changes: 
=> set scroll button

index.html, navbar.css
Fixes:  #2522 
Redesign the theme toggle
change the style of navbar for theme toggle now its looks great 
aFTER---
BEFORE---
- [] I have taken help from some online resources.
=> Redesign the theme toggle

maps.html
Fixes: #2575
as i reset the hover effect because this hover effects the visibility of text in this div.
BEFORE:-
AFTER:-
!
=> NEED TO IMPROVE HOVER EFFECT IN "SUBSCRIBE OUR NEWSLETTER" #2575

assets/css/index.css, assets/css/style.css
=> Fixed text color issue for both dark and light mode ! 

assets/css/index.css, assets/css/quiz.css, assets/css/style.css, index.html
i have done changes in the navbar #2532 
**Before**
**After**
=> updating navbar changes

tools/sip.html
There was no button for sliding hizontally in the tools page, fixing this i added two buttons for the same.
Before
https://github.com/user-attachments/assets/9e2fc9a1-f9c8-45c1-bcd4-add72844bca3
After
https://github.com/user-attachments/assets/c07a678d-2b75-47d6-bf57-d0cf5d504c2f
=> Horizontal sliding buttons added in tools page.

Finveda/index.html, index.html
Fixes: #2518
This PR resolves the issue of incorrect links for the Privacy Policy and Terms of Service in the "Subscribe to Newsletter" modal. It updates the links to ensure they redirect users to the correct pages, enhancing both the credibility and functionality of the modal.
- Fixes **404 redirection issue** by providing correct URLs for Privacy Policy and Terms of Service.
=> Fix: Correct Links for Privacy Policy and Terms of Service in "Subscribe to Newsletter" Modal

assets/css/trends.css, trends.html
Fixes: #2603 
Closes: #2603 
fixing toggle button of theme on Trend page
https://github.com/user-attachments/assets/c530fca4-dac3-4731-9e49-ec537aba7cc5
=> theme button update

careers.html
This pull request introduces several improvements to the dark theme and overall user experience:
1. **Dark Theme for Jobs Table:**
- Adjusted background colors and text colors for better readability in dark mode.
- Implemented a hover effect for table rows to highlight selected rows.
2. **Dark Theme for Search Bar:**
- Modified the background color and text color of the search bar.
- Added a subtle border to the search bar.
3. **Main Heading Styling:**
- Adjusted the font color of the main heading to match the dark theme.
4. **Modal Improvements:**
- Added a close button to the modal.
- Changed the background color of the modal to match the dark theme.
5. **Accessibility:**
- Added alt text to all images.
- Improved color contrast for better readability.
6. **Performance …
=> Enhance Dark Theme and User Experience

assets/js/quiz.js
Closes #2600 
_**I'm expecting gssoc-ext with level1 labels**_ @Sampadatiwari @sampadatiwari30 
**1. Update Popup Message Duration Comment for Consistency:**
- The current code shows the popup message for 3 seconds, but the comment states 10 seconds. Update the comment to accurately reflect the current timeout duration (3 seconds) or adjust the timeout to 10 seconds if desired.
**2. Optimize Circle Animation Logic:**
- Modify the mousemove event listener to update coords.x and coords.y only if the mouse position changes. This reduces unnecessary DOM manipulation, which can improve performance when the mouse is stationary.
**3. Add Event Listener Cleanup for Animation:**
- Since the animation runs continuously with requestAnimationFrame, consider adding a way to stop or pause it when the …
=> Improve `quiz.js` for Optimized Animation and Consistent Timing

profile.html
Fixes: #2580
As i enhance the designing of the  PROFILE PAGE 
AS I ADDED :- 
- give new shapes to div
- NEW DESIGNING APPROACH
- NEW BACKGROUND COLORS
- TRANSITIONS
- YOU NEED TO CHECK IT OUT
BEFORE:-
AFTER:-
=> NEED TO ENHANCE DESIGNING OF PROFILE PAGE #2580

assets/css/register.css, loginPage.css, loginPage.html, registerpage.html
Fixes: #2616 
clsoes: #2616 
improve the Ui of Signup page like color combination to achieve the best visiblity and some other css properties changes.
https://github.com/user-attachments/assets/e0ec0a46-b931-4b50-af7e-185af3162fba
=> improve Sign in page

profile.html
Fixes: #2579 
I ADD NAVBER IN PROFILE PAGE WHICH HELPS TO NAVIGATE ON OTHER PAGES EASILY.
=> NAVBAR ADDED IN PROFILE PAGE

assets/css/contributors.css, contributors.html
Fixes: #2609
This PR enhaces the entire contributors page page
Before
https://github.com/user-attachments/assets/fc57d7f7-1cd2-44a4-85a5-381756c831ca
After
https://github.com/user-attachments/assets/709e3a17-1a64-49d6-b092-0f6cb0fa91e4
=> Contributors page redesigned

assets/css/contributors.css, contributors.html
https://github.com/user-attachments/assets/87e2fc9e-cc55-4abe-9ed8-d190b7ba3515
=> Contributors animation fixed

faq.html
Hello, PR
Text box width Issue fixed -
Before -
=> Fixed Help page text box width issue !

assets/css/index.css, index.html
fixes: #2443 
writing..............
=> Enhance Discussion Forum

reviews.html
**Description**:
This pull request introduces a significant overhaul of the user interface, focusing on improving usability and aesthetics. Below is a summary of the key changes made:
1. **Form Resizing**: Reduced the width of the form for better alignment and visual appeal.
2. **Darker Color Palette**: Implemented darker shades of blue and green to enhance readability and visual contrast.
3. **Border Adjustments**: Changed border colors to `Steel Blue` for better definition and clarity.
4. **Gradient Backgrounds**: Updated gradient backgrounds for buttons and sections to use deeper shades for a more cohesive look.
5. **Hover Effects**: Enhanced hover effects for buttons and input fields to improve user interaction feedback.
6. **Font Styling**: Adjusted font colors for better legibility …
=> Financial Success Story- UI Enhancements and Color Palette Update

blog.html
Fixes: #2597 
https://github.com/user-attachments/assets/02e42a9c-985c-4263-9c64-2620dc04c752
i make blog rendering effeciently and remove the retendent work of copy pasting 
efficient search bar 
modular code 
easy to add new blog more efficient to handle 
- [ X] Make sure you have self-reviewed …
=> Added search bar and make code more modular and maintainable

Finveda/quiz.html, Finveda/tools/sip.html, about.html, blog.html, contact.html, faq.html, finance.html, index.html, maps.html, quiz.html, tools/sip.html, trends.html
Hello, PR
Add profile icon in all page done -
https://github.com/user-attachments/assets/e8e1a016-c05a-4066-b153-963112c1ca2b
=> Add profile icon in all page done ! 

index.html
=> Enhanced Feedback section

tools/sip.html
Fixes: #2604
This pull request addresses visibility and functional issues with the progress bar on the website.
It ensures Ensured smooth animation and consistent tracking behavior.
https://github.com/user-attachments/assets/985153fb-97ec-4623-b3c1-b73d9092c906
=> Corrected progress bar

contact.html, server/.env.example, server/.gitignore, server/app.js, server/controllers/contactController.js, server/model/contact.js, server/package.json, server/routes/contactRoutes.js, server/utils/db.js
Fixes: #2593 
Added fully working backend for contact form with proper folder structure 
everything working fine 
data get saved on mongodb successfully 
use this command to initilize backend
cd server > npm i > nodemon app.js
create a env file and copy the code of .env.example to that env 
backend run smoothly !!
- …
=> Added backend for contact form with proper folder structure

profile.html
Hello, PR
Add Cursor Tail Effector in Profile page done -
https://github.com/user-attachments/assets/dd4fd70d-c678-41bd-acd0-af8de49ecb4b
Before -
https://github.com/user-attachments/assets/af75036b-b387-45c4-89e9-aaa538271ffd
=> Add Cursor Tail Effector in Profile page done ! 

tools/sip.html
Fixes: #2479 
On the tool page, there are two toolboxes whose UI is not good enough. I have fixed this UI by adding hover and animation effects to the heading, as well as adding space between the labels and fixing the button alignment.
https://github.com/user-attachments/assets/45c72b9d-5a01-49cd-9603-0ea3f2292a38
https://github.com/user-attachments/assets/d967f369-f640-4c00-89cb-c52c016b2506
=> In tool page ui fix of two tool box

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html
Fixes: #2475 
i am added multiple language support systems for some importance pages that's make the website more engaging and beautiful
=> Added multiple lanuguage support  Privacy Policy , Refun Policy , Licensing, Terms of Service pages

Finveda/assets/css/contributors.css, assets/css/bootstrap.min.css, assets/css/contributors.css, contributors.html, navbar.css
I added a border animation over contributor cards
https://github.com/user-attachments/assets/7c10cc56-bd02-4878-b3fe-a1ddf9c1cac7
=> Animation added on contributors card

tools/EPFCalculator.js, tools/FDCalculator.js, tools/GSTcalc.js, tools/RDCalculator.js, tools/SavingsGoalCalculator.js
Closes #2643 
_**This PR deserves level3.. Kindly review it and Add it. and assign me!!**_ @sampadatiwari30 @Sampadatiwari 
**1. `EPFcalculator.js`:**
- Input Validation: Added comprehensive checks for salary, age, contribution percentage, salary increase, and interest rate.
- Error Messaging: Improved error handling with user-friendly alerts.
- Currency Formatting: Implemented currency formatting for displaying the total EPF amount.
- Clear Functionality: Enhanced the clear button functionality to reset all fields effectively.
**2. `FDCalculator.js`:**
- Input Validation: Improved validation to ensure valid inputs for principal, rate of interest, and years.
- Error Messaging: Displayed alert messages for invalid inputs.
- Formatting: Used fixed decimal formatting for maturity amount and …
=> Enhance Calculator Functionality and User Experience

maps.html
Fixes: #2684 
Maps page footer extra space fix and scroll-up button styled fix
=> Maps page footer extra space fix and scroll-up button fix

blogs/privacy-policy.html
Fixes: #2682 
in your privacy policy page in hero section img url fix
=> Img url fix of privacy policy page hero section

server/.env.example, server/controllers/contactController.js, server/package.json, server/utils/sendMail.js
Fixes: #2592 
i have added send mail feature to contact form for instant resolving the user querry
in the formated way you will get mail to your mail account
clean and clear UI of mail
fill this env info for using this mail feature
admin mail where you want to send the user info
mail by this mail you will receive mail
passkey you have to generate one from
application password on mail !!
- [ X] I am a participant of GSSoC-ext.
- [ X] I have added …
=> Added mail to admin feature for instant reply

faq.html, new.css
Hello, PR
Issue fixed -
Before -
https://github.com/user-attachments/assets/49e68bf2-f146-4056-ad7e-8b20574a6bef
=> Fixed input text color blends issue in feedback section !

careers.html
This PR introduces a fully functional dark theme for the Career Roadmap section with improved visual aesthetics and readability adjustments.
1. **Dark Mode Background**: Applied a dark gradient background (`#243b55` to `#2e4053`) to the roadmap container.
2. **Text Color Adjustments**: Updated body text color to `#f5f5f5` for better contrast in dark mode.
3. **Roadmap Header Styling**: Styled the `<h2>` header text with a white-to-grey gradient to enhance visibility.
4. **Header Text Shadow**: Added a subtle shadow to the header text for improved readability on dark backgrounds.
5. **Interactive Gradient Background for Steps**: Adjusted the background gradient on roadmap steps to a dark scheme (`#2e4053` to `#1b1b2f`).
6. **Hover Effect**: Added a slightly lighter gradient on hover …
=> Dark Theme Implementation for Career Roadmap Section

.vscode/settings.json, blogs/sitemap.html
Fixes: #2678 
in your website in site page there is some bug i see i want to fix this:
1. there is no logo in footer
2. the icons is missing before the footer items
3. social media icons is missing
4. the order is wrong among the contributors and sitemap items
=>  site map page footer fix

blogs/sitemap.html
Fixes: #2675 
in your website in site page there is some bug i see i want to fix this:
1. there is no logo in footer
2. the icons is missing before the footer items
3. social media icons is missing
4. the order is wrong among the contributors and sitemap items
=>  UI fix of refund policy footer

calculators/calculators.js
**Closes** #2695 
**_Kindly add level2 with gssoc-ext. and assign me!_** @Sampadatiwari @sampadatiwari30 
**Enhance readability and functionality:**
**1. Error Handling:** Add basic input validation to handle cases where users might leave fields empty or enter invalid numbers.
**2. Modularity:** Consider refactoring some common functionality, like fetching element values and formatting currency, to reusable functions to reduce repetition.
**3. Enhance Animation Flexibility:** Make the currency symbol and the animation duration configurable.
4. **Chart Data Improvement:** Consider dynamically setting chart labels for better readability if the investment duration varies.
=> Enhanced calculator

about.html, assets/css/index.css, assets/css/quiz.css, assets/css/style.css, blog.html, contact.html, faq.html, finance.html, index.html, maps.html, quiz.html, tools/sip.html, trends.html
Fixes: #2613 
This pull request addresses the inconsistency in the "Subscribe to Our Newsletter" section across multiple pages and aligns its design with the homepage for uniformity. Additionally, the following adjustments were made:
- Corrected the footer layout on the Help page.
- Resolved footer alignment issues on the Trend page.
Before :
https://github.com/user-attachments/assets/f755e6f8-5467-4d45-920e-791872dfc9f2
After : 
https://github.com/user-attachments/assets/08c60891-1685-4041-9533-2ec6f22c3b9b
=> Fix inconsistency in 'Subscribe to Our Newsletter' section across pages

login.html, loginPage.html
Fixes: #2654 
"remember me" added to the signup and signin page connecting it to the local storage database
saves the user's email in localStorage if the checkbox is checked.
Uploading Register & Login - Brave 2024-11-04 12-44-38.mp4…
=> "remember me" added to the signup and signin page connecting it to the local storage database for user authentication.

about.html, index.html
Fixes: #2633
I have corrected the text and button margin of the home page content, and also corrected dark theme change bug of about us page.
Hi @sampadatiwari30, My Issue is already done by someone, which was assigned to me 2 days before, So in this PR, I corrected the bug of the home and about us pages.
=> Correct Home page bug and About us page

blog.html
Fixes: #2656 
i have write modular code and enhance the UI/UX of blog post 
also change the naming convention according to our backend data 
so its get easier to align the blog post according to our backend data of blog post 
clean clear UI !!!
- [ X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
- [ …
=> Enhance the designing and UI/UX of blog post

ContactUs.html, about.html, index.html
Fixes: #2651 
Enhanced scroll back button with timeline on it for smoother functioning.
https://github.com/user-attachments/assets/87022860-209e-4fdc-889c-f2afcafd2085
=> Enhanced scroll back button with timeline on it for smoother functioning. (Issue #2651)

index.html
Fixes: #2652 
Made css styling changes on "feedback section" making it more elegant and responsive.
https://github.com/user-attachments/assets/1466c37a-84d1-40ec-bfb1-1d3b105a5f47
=> Made css styling changes on "feedback section" making it more elegant and responsive.

finance.css
Fixes: #2676 is solved
Text showing issue is solved, Now text is showing in the courses page.
Thank you!
=> issue number #2676 is solved

contributors.html
https://github.com/user-attachments/assets/cc2dbdca-d4ab-44c6-ad75-02bc4c9c3401
=> Animation colours changed

index.html
Before
https://github.com/user-attachments/assets/c3ddefed-39c5-48d6-9cd4-bb0473b62871
After
https://github.com/user-attachments/assets/90b9b08d-05fa-44b2-a0af-9835a90233a5
=> Broken Home page animation and footer fixed

faq.html, finance.html
Fixes: #2702 
-  watch now button now working for below three cards
- also they are now aligned in same line
- items now aligned in center
@sampadatiwari30 @deepeshmlgupta
=>  Minor Bug Fixes And Enhancement  In Some Pages

quiz.html
Hello, PR
Add Cursor Tail Effector in Quiz page done -
https://github.com/user-attachments/assets/8dec51a0-3dfb-400a-99a1-544ddb6b98d5
Before -
https://github.com/user-attachments/assets/b532014f-9f36-4a8c-a480-51280f859483
=> Add Cursor Tail Effector in Quiz page done !

blog.html, server/controllers/addBlogController.js, server/routes/addBlogRoutes.js
Fixes: #2700 
https://github.com/user-attachments/assets/dbfac291-e666-463b-a69c-3e4a02583de7
Now blog data will be render dynamically on blog page 
user get real data to read
enhance user experience 
You can add more blog dynamically !!
Maked code more clean and easy to maintain ....
Remove repeated work 
- [ X] Make sure you have self-reviewed the …
=> Added dynamic data of blog form the database with image

index.html
Fixes: #2720 
Added a new section for Market News and Insights to Provide up-to-date news.
https://github.com/user-attachments/assets/194c7c41-4b84-48e6-9d0e-0b10920fa9b1
=> Added a new section for Market News and Insights to Provide up-to-date news #2720

faq.html
Fixes: #2628
I enhance the FAQ Page as before:-
- header is not visible 
- search bar text not visible 
- accordian colors are not interactive 
- parent box is not visible properly 
- allignment problem
BEFORE:-
AFTER:-
=> ENHANCEMENT IN FAQ PAGE #2628

finance.html
Fixes: #2727 
closes: #2727 
on the course page added the scroll button bottom to top scroll for visitor easier purpose 
after changes:
Uploading Screen Recording 2024-11-05 074153.mp4…
Screen shots:
=> update scroll  button  on course page

assets/js/contributors.js, contributors.html
Hello, PR
Create a Responsive Project Statistics section done !
I have created a new Project Statistics section. This Project Statistics section  is fully responsive, Now its values ​​are dynamically updating, also I made it according to the theme..
Before -
Now -
=> Create a Responsive Project Statistics section done !

finance.html, finance.js
Fixes: #2726 
closes: #2726 
fixing footer issue and set the footer according to screen width 
https://github.com/user-attachments/assets/359c2c70-6df4-4df9-a998-16b5f0db3b48
https://github.com/user-attachments/assets/83c86914-5ec2-4f30-b366-6cae23c99857
=> update footer properly according to screen width

addBlog.html, blog.html, demo.html, new.css, profile.html
Fixes: #2736 
The blogs page was unmodfied as before
BEFORE : 
NOW : 
The blogs page is modified now,
=> Blogs page modified

addBlog.html, blog.html, demo.html, new.css
Fixes: #2770 
Blogs page was not working as we add blog or delete
Now blog page is modified using JavaScript that it is workign functionalyy
here's the output as folllows
deleting blogs allso modified
blog deleted
=> Blogs page working functionalyy

addBlog.html, blog.html, demo.html, new.css, profile.html
Fixes: #2737 
The profile option of editing was not working but now it started functioning with the help of javaScript.
=> Profile page working

blogs/privacy-policy.html
Closes : #2764 
This PR resolves layout and alignment issues in the navbar that caused disorientation on both desktop and mobile views. The updated navbar now provides a consistent and responsive experience across different screen sizes.
- Desktop
=> Fixed navbar disorientation on privacy page

about.html, blog.html, contact.html, finance.html, footer.html, index.html, quiz.html, termsOfUse.html
Fixes: #2757 
Description
This PR introduces a new "Terms of Use" page to the application, outlining the terms and conditions that govern the use of our services. The document includes various sections that define user obligations, intellectual property rights, limitation of liability, dispute resolution, and more, providing a comprehensive legal framework for users.
Changes Made
Created a new page named TermsOfUse.
Structured the content into relevant sections for clarity:
Acceptance of Terms
User Obligations
Intellectual Property Rights
Limitation of Liability
Indemnification
Termination Clause
Governing Law
Modification of Terms
Legal Compliance
Dispute Resolution
- [ X] Documentation update (adds or updates related documentation)
- [ X] I have …
=> Added terms of use page in full website

blogs/privacy-policy.html
Fixed the broken privacy policy page
Before
https://github.com/user-attachments/assets/dc189838-1482-4523-a01c-e6e640568f28
After
https://github.com/user-attachments/assets/d4660757-17b5-4796-b92a-ac5d79b60f6f
=> Broken Privacy policy page fixed

contributors.html, index.html, loginPage.css, loginPage.html
Fixes: #2745
This update adds the missing "Explore More" button to the navbar on the home page. The button is now aligned with the other navigation elements, ensuring a cohesive look and improving accessibility to additional sections from the home page. This enhancement helps streamline user navigation, allowing quicker access to key areas of the site.
https://github.com/user-attachments/assets/4bd3cf10-2e00-419f-abbd-5c9b6af491ba
=> Add 'Explore More' Button to Navbar on Home Page

contributors.html
Fixes: #2742 
This update addresses the navbar inconsistency specifically on the Contributor page, aligning it with the style and functionality seen across other pages. The Contributor page previously displayed a different navbar layout, which impacted the visual cohesion of the site. This fix standardizes the navbar, ensuring that all pages, including the Contributor page, share a consistent and user-friendly navigation experience.
=> Fix Navbar Inconsistency on Contributor Page

contributors.html, loginPage.css, loginPage.html
Fixes: #2747 
This update resolves UI inconsistencies between the login and sign-up pages to ensure a cohesive user experience. Adjustments were made to align elements such as fonts, button styles, colors, and layout, making both pages visually consistent and easier to navigate. This enhancement aims to improve the overall user experience by providing a more unified design across these entry pages.
Before : 
https://github.com/user-attachments/assets/90264ef5-b7ac-457e-b1d7-bb45d139c4f8
After : 
https://github.com/user-attachments/assets/cc9ccb4a-e8fb-4eda-a4b2-cf3685574a5c
=>  Fix UI Inconsistency in Login and Sign-Up Pages

tools/sip.html
Fixes: #2753 
Adding an "SIP calculator" to the tools section Compounding @ 14%(average) 
Adding an "SIP calculator" to the tools section Compounding @ 14%(average) 
https://github.com/user-attachments/assets/b6ed20ea-e9d0-4150-9281-d262658196ff
=>  Adding an "SIP calculator" to the tools section Compounding @ 14%(average) 

a_loginPage.html
Fixes: #2784 
The login but was not working with it's functionality, as i have modified it now it's working.
=> Login button started working

assets/css/index.css, assets/css/style.css, blog.html
Fix issue no. #2761.
Make the blog page responsive.
=> Make blog page responsive . 

addBlog.html
Fixes: #2802 
I enhance the BLOG Page as before:-
- provide proper space allotment for section
- provide a comfy designing
- align all elements in proper way so that they are able to fully represent their self 
BEFORE:-
AFTER:-
=> ENHANCEMENT IN BLOG PAGE #2802

blog.html
Fixes: #2751
https://github.com/user-attachments/assets/e36a2400-3ece-47d6-9931-359c078c24fd
added play and pause button where it will read the following title and content of blog
smoothly in clear clean voice
Write modular and maintainable code
will i get level 3 for it , IT May look easy but its doesn't ?
- [ X] Make sure you have self-reviewed the …
=> Added text to speech feature in blog article

about.html, assets/css/about.css, contributors.html
Fixes: #2788 
Closes: #2788 
improved the Ui of Contributors Container on About Us Page  
=> improved ui of Contributors Container on About us Page

faq.html
Fixes: #2803
Added star rating to the feedback form.
https://github.com/user-attachments/assets/b65b74ae-39be-4163-8b5a-004c6908f9f6
=> Added star rating to the feedback form

index.html, newsletterpopup.js
Closes #2765 
This PR replaces the alert message shown on newsletter subscription with a custom modal, creating a more modern and user-friendly experience. The modal displays the user's email as a confirmation message upon successful subscription.
https://github.com/user-attachments/assets/d8a6b353-84f2-4110-a796-ebaf5b556dda
=> Replaced alert with Custom Modal for Newsletter Submission Confirmation

contributors.html
Fixes: #2792 
Closes: #2792 
fixing the theme button on Contributors page 
https://github.com/user-attachments/assets/84078694-9378-49b6-84e9-c64578667d38
after changes:
https://github.com/user-attachments/assets/63e8d8ee-1beb-4a09-9fa7-efa4f7bea1e0
=> update toggle button of Contributor page

Finveda/index.html, finance.html
Fixes: #2701 
the search bar on the top right section of navbar 
#2701
the following new feature added  that still requires backened functionality but as it is being added it will give a more of glorifying look to the homepage.
- [ X] I am a participant of GSSoC-ext.
- [X ] I have performed a self-review of my own code.
- [X ] I have added documentation to explain my changes.
- [X ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
- [X ] This PR is …
=> added search bar

blog.html, demo.html
Fixes: #2800 
Every blog will contain share blog option which shares user's blog on Instagram, twitter or Linkedin with help of javaScript.  
Previously image was not seen but it is also modifed with help of javaScript
=> Share Blogs Buttons added and modified blogs-page

Finveda/assets/css/contributors.css, Finveda/contributors.html
Fixes: #2744 
https://github.com/user-attachments/assets/4370a0c2-8f45-4eec-9f37-1dcdfbad7bf3
=> Added animation on scroll on contributors card

faq.html
Fixes: #2805 
Changing the css styling of the FAQ section by implementing more elegant styling elements 
https://github.com/user-attachments/assets/339f02e4-e62b-4423-8ddb-9879fec1da56
=> Changing the css styling of the FAQ section by implementing more elegant styling elements 

blog.html, demo.html, index.html
Fixes: #2801 
Search Bar is added in home-page by which user can go to any page of the website as it gives suggestions and redirects user to new page
=> Search Bar Added in Home page

tools/sip.html
fix: #2767
https://github.com/user-attachments/assets/e45a2946-b172-4c37-8606-61875b765013
=> ADD 4 more Calcullators to tools page  #2767

tools/sip.html
fix: #2767
https://github.com/user-attachments/assets/61f0518e-6dde-4baa-83e5-8854d96893ee
- Savings Goal Calculator
- Loan Amortization Calculator
- Budgeting Calculator
- Retirement Savings Calculator
=> ADD 4 more Calcullators to tools page 

addBlog.html
Fixes: #2811
BASICALLY I JUST ADD NAVBAR IN THIS PAGE SO THAT WE CAN NAVIGATE ON OTHER PAGES WITH EASE
=> NAVBAR NEEDED IN ADD BLOG PAGE. #2811

addBlog.html
Fixes: #2812 
BASICALLY I JUST ADD  FOOTER IN THIS PAGE SO THAT WE CAN NAVIGATE ON OTHER PAGES WITH EASE
=>  FOOTER NEEDED IN ADD BLOG PAGE #2812

index.html
Fixes: #2807 
Changing the css styling of the discussion forum section by implementing more elegant styling elements.
https://github.com/user-attachments/assets/b6b08b51-e4c7-4e21-8f5f-e9eafc6a5435
=> Changing the css styling of the discussion forum section by implementing more elegant styling elements 

about.html, index.html, navbar.css
Fixes: #2397 
I have corrected the theme toggle buttton on home page which was not toggling on dark theme, made consistent, and corrected the visibilty of next/prev button of about us page card.
Hii @sampadatiwari30, my assigned issue is already been done, So I solved other bugs of the pages as I described.
=> Solve Home and About us page bug

assets/css/blog.css, blog.html
Fixes: #2843 
closes: #2843 
improvement of blog page
before changes  : 
https://github.com/user-attachments/assets/b8e7e220-a0f4-4513-9099-172e88dfc7b4
=> Update Blog page

blog.html, server/controllers/addBlogController.js, server/routes/addBlogRoutes.js
Fixes: #2754
Social Media Integration: Implemented social media icons that, when clicked, render the following:
Blog title
Blog content
Link to the respective blog post
User Experience Improvement: Designed this feature to simplify the process of sharing blog posts, enhancing overall user experience.
API Development: Created an API to fetch blog posts by their unique ID, ensuring efficient retrieval of content.
https://github.com/user-attachments/assets/1866e0a7-41b5-4498-af9a-3ea51491c2dc
- [ X] My code follows the style …
=> Added social media icons dynamic rendering of blog content

assets/css/style.css, index.html
Fixes: #2808 
This update improves the layout of the "User Experience" section on the Home page, where elements were misaligned, causing a cluttered appearance. Adjustments have been made to ensure consistent spacing, alignment, and overall structure, creating a visually appealing and organized experience for users.
https://github.com/user-attachments/assets/94b398fd-bfce-4246-9df7-5274f309bf19
=> Fix disorganized layout in User Experience section on Home page

blogs/refund-policy.html
Fixes: #2882
I FIXED THE DESIGNING OF FOOTER WHICH IS PRESENT IN THE REFUND POLICY PAGE 
BEFORE:-
AFTER:-
=> ENHANCEMENT IN FOOTER IN REFUND POLICY #2882

tools/capitalGainsTaxCalculator.js, tools/sip.html
Fixes: #2846
Adding a "Capital Gains Tax Calculator" to the tools section. (Issue #2846)
https://github.com/user-attachments/assets/96b8ba14-fcea-4c69-a26b-22eacf9171b4
=> Adding a "Capital Gains Tax Calculator" to the tools section. (Issue #2846)

careers.css
Fixes: # 2531
added responsitiveness to the page and changed a bit of css
=> Done with changes updated carreer page #2531

blogs/privacy-policy.html
Fixes: #2878
I FIXED THE RUINED THE DESIGNING OF "PRIVACY POLICY PAGE" like 
- text visibility
- header enhancement
- bullet points
BEFORE:-
AFTER:-
=> TEXT IS NOT VISIBLE IN PRIVACY POLICY #2878

assets/css/style.css, index.html
Fixes: #2722
Now the We value your feedback section is responsive and user friendly in the small devices like mobile phone.
=> Issue #2722 is solved

Finveda/index.html
Fixes: #2869
Now the newsletter banner is responsive for all devices.I have added media queries for all devices.
=> Update index.html by making the pop-up responsive for all devices now the content is coming down for small devices

index.html, server/app.js, server/controllers/newsletterController.js, server/model/Newsletter.js, server/routes/newsletterRoutes.js, server/utils/sendNewsletter.js
Fixes: #2828 
https://github.com/user-attachments/assets/4f722ea4-f2d1-434b-bdce-900a02832337
This PR introduces the "Subscribe Us" feature to the backend, enabling users to subscribe to the platform by submitting their name and email
Once subscribed, users receive a welcome email with details about the platform and its offerings.
Also saved the details of the user in the database for future !!
- [ X] I have …
=>  Implement "Subscribe Us" Feature

assets/css/style.css
Fixes: #2904 
https://github.com/user-attachments/assets/a0810c66-de3e-4b42-a4e9-4879a7f538e3
=> corrected darkmode style on service page

assets/css/privacy-policy-dark-mode.css, assets/js/privacy-policy-dark-mode.js, blog.html, blogs/privacy-policy.html
Fixes: #2902
https://github.com/user-attachments/assets/7ebafc08-2db5-4956-8850-5969d1fca2bb
=> Added darkmode on privacy policy page

index.html, server/controllers/feedbackController.js
Fixes: #2827 
https://github.com/user-attachments/assets/e65c2e95-6424-43ec-a36d-dcc61b209361
Added backend for feedback form !!
after clicking on submit button the data get saved on database efficiently 
- [X ] I have performed a self-review of my own code.
- [X ] I have added documentation to explain my changes.
- [ X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
- [ X] This PR is submitted under the GSSoC …
=> added backend for feedback form

faq.html
Fixes: #2816
Corrected the FAQ container alignment, in the center, which visually balances the page.
The FAQ container is now centered horizontally on the page, providing a symmetrical and visually appealing layout. This will improve readability and make the section look more polished.
=> FAQ Container Alignment

assets/css/preloader.css
Fixes: #2868 
Now the loader ( PreLoader ) is responsive and looking good in the mobile phone
=> issue number #2868 is solved

trends.html
Implement in dark mode toggle in the Trends page
Before the bug fix:-
https://github.com/user-attachments/assets/3fa80a14-4e4e-49a1-8314-23772dc3af47
After Bug Fix:-
https://github.com/user-attachments/assets/030a5582-dcb9-4117-b83c-5ced9e7e2dfe
=> Implement in dark mode toggle in the Trends page

blogs/Pocketmoney.html, blogs/economic-trends-and-analysis.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/new.css, blogs/senior.html, blogs/starup.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Fixes: #2874 
This update addresses inconsistencies in the navbar and footer elements on the Blog Detail page. The navbar and footer now align with the rest of the website's design, providing a cohesive user experience. Additionally, I have ensured that all blog card pages now have consistent footers and navbars, matching the site’s overall layout and design standards.
Before : 
https://github.com/user-attachments/assets/e3aed83e-4f29-4dc3-9af3-21f4eb460d3a
After : 
https://github.com/user-attachments/assets/873bdc31-2b42-4d1e-89cc-bc9db02a84d0
=> Fix Navbar and Footer Inconsistencies on Blog Detail Page

index.html
Fixes: #2936
I FIXED THE DESIGNING OF FOOTER WHICH IS PRESENT IN THE HOME PAGE 
BEFORE:-
AFTER:-
=> ENHANCEMENT NEEDED IN FOOTER OF "HOME" #2936

index.html
Fixes: #2909
https://github.com/user-attachments/assets/4a69634b-4e9d-464e-a90f-3f0e6932ef5b
=> Added animation on scroll on home page

trends.html
Fixes: #2889 
bugs fixed in Trends page ,removed the glitch!!
there were too many errors in that code fixed those
=> bugs fixed in Trends page ,removed the glitch!!

Licensing.html, contributors.html
Fixes: #2896 
licensing page navbar ui fixed make it more decorated and professional
=> Licensing page navbar UI fixed

reviews.html
Fixes: #2893 
in this pr i am added logo in review page Navbar and Footer section  to make this review page look  profesional
=> Review page navbar and footer logo update

blogs/sitemap.html, blogs/terms-of-service.html
Fixes: #2881 
in this pr i am added navbar and hero section to this pages
https://github.com/user-attachments/assets/4a4dd3f3-17fc-47bd-a7e7-6d9a408b2df4
=> Terms and sevices page UI fixed

blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html
Fixes: #2900
in this pr i am implement in privacy policy page
1. logo 
2. all socil media icons
3. all footer icons
- [] New feature (non-breaking change which adds functionality)
https://github.com/user-attachments/assets/267f23d4-438d-4752-91c5-a327c1667a70
https://github.com/user-attachments/assets/973e1a18-dbc1-40f6-b461-66e4c2a5b1d2
=> UI improve of privacy plicy page footer

contact.html
Fixes: #2891
- Fixes the CSS issue that caused the "Contact Us" form layout to break when hovering over input fields or buttons.
- Adjusts the styling to ensure that elements remain aligned and visually consistent when the user hovers over the form.
- Enhances the user experience by maintaining a cohesive look and feel without layout shifts or unexpected styling changes on hover.
**Before Hover:**
**After Hover:**
=> Fixed Hover issue in Contact Us Form

about.html
Fixes: #2897 
in About Us page next cards button UI fixed
=> About us page next cards button UI fixed

assets/css/blog.css, assets/css/style.css, blog.html, index.html, maps.html
Fixes: #2928 
This update standardizes the 'Subscribe' container across all pages to match the style of the home page, ensuring visual consistency and improving user experience. Additionally, the subscribe container inconsistency on the home page was corrected, bringing it in line with the updated design across the website.
https://github.com/user-attachments/assets/50776a62-eac6-4b9f-88b5-c397f8ea6a77
=> Fix Inconsistent 'Subscribe' Container Across Pages

about.html, blog.html, contact.html, faq.html, finance.html, index.html, maps.html, quiz.html, tools/sip.html
Fixes: #2947
I correct the sun moon icon bug
https://github.com/user-attachments/assets/fca4dc27-65be-4767-9ff5-891acfd462af
=> icon bug fixed

index.html
Hello, PR
Add a pop up dialog box for Survey done ! #2865
=> Add a pop up dialog box for Survey done ! #2865

index.html
Fixes: #2976
I FIXED THE DESIGNING OF FOOTER WHICH IS PRESENT IN THE HOME PAGE 
BEFORE:-
AFTER:-
=> BUG IN FOOTER OF HOME PAGE #2976

termsOfUse.html
fixes: #2980 
BUG FIXES.
Earlier the content was not visible as it was blending with the background. Now i have fixed it. 
Kindly merge @deepeshmlgupta @Sampadatiwari @sampadatiwari30
=> TERMS OF USE PAGE - BUG FIXED

finance.html
Fixes: #2890
- Implements a search bar in the Courses section, allowing users to search for courses by name.
- The search functionality filters results dynamically as the user types, displaying only courses that match the search input.
- Enhances user experience by improving navigation, making it easier and faster for users to locate specific courses.
https://github.com/user-attachments/assets/79ce9a5f-a857-4c4e-bdb3-319fa097077a
=> Added Search Bar functionality in Courses

faq.html
Fixes: #2892
- Implements a search functionality in the FAQ section of the website.
- Allows users to search for specific keywords within the FAQ cards.
- Filters and displays only the relevant FAQ questions and answers based on the search term.
- Improves user experience by making it easier and faster for users to find specific information in the FAQ section.
Uploading FAQ SEARCH.mp4…
=> Implemented search functionality in the FAQ section

assets/css/trends.css, index.html, trends.html
Fixes: #2929 
Resolved a dark mode toggle inconsistency on the Trend page. Previously, the toggle button's indication was mismatched with the actual display mode, causing the Trend page to appear in light mode when dark mode was selected and vice versa. This update ensures that the Trend page correctly reflects the selected mode, improving user experience and interface consistency.
https://github.com/user-attachments/assets/920750c7-457b-488d-a9d7-a1f5010bccd9
=>  Fix Dark Mode Toggle Issue on Trend Page

faq.html
Fixes: #2989 
pls add hacktoberfest and gssoc labels @sampadatiwari30  @deepeshmlgupta 
Feature/Bug Fix: Implemented an enhancement for the FAQ section by adding icons next to each question, making the content more engaging and user-friendly.
Issue Fixed: Improved user experience by visually differentiating questions, enabling easier scanning and a modern interface.
Motivation & Context: Adding icons related to each question's topic makes the FAQ section more intuitive and visually appealing, which can aid user engagement.
Dependencies: Added Font Awesome for icons; no other dependencies were introduced.
- [y ] New feature (non-breaking change which adds functionality)
- [y ] I am a participant of GSSoC-ext.
- [y ] I have followed the contribution guidelines of this project.
- [ y] I have …
=> added icons to faq questions

Finveda/footer.html
Fixes: #2973 
fix the footer layout
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> fix the footer

about.html, assets/css/about.css
Fixes: #2964 
Closes: #2964 
improvement Ui and some color combination according to website theme 
=> update Ui of Subscribe Container

blogs/refund-policy.html
Fixes: #2927
https://github.com/user-attachments/assets/70f7a966-db9a-425b-af27-dc8ab68667e0
=> Corrected refund policy page

Games/Financial Goal Tracker Challenge.html
Fixes: #2998 
This PR introduces a "Back to Home" button at the top of the Financial Goal Tracker page for easier navigation to the index.html home page. Additionally, UI improvements were made by adding hover effects to input fields and buttons for a more polished and interactive user experience.
Changes Made:
- Back to Home Button: Added a button at the top of the page linked to index.html.
- Hover Effects: Updated CSS to include subtle hover effects for input fields and buttons, improving visual feedback and user experience.
=> Add "Back to Home" Button and UI Enhancements to Financial Goal Tracker

assets/css/index.css, index.html
Fixes: #2953 is solved.
Discussion form issue is solved.
=> Issue number #2953 is solved

blog.html, index.html
Fixes: #2958
https://github.com/user-attachments/assets/5d82e4af-630f-406e-a370-8481c1f88946
Added a animated auto scrollable testimonial page
where we show our user experience in good UI 
writed a modular and maintainable code 
- [ X] I am a participant of GSSoC-ext.
- [X ] I have taken help from some online resources.
- [X ] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [X ] I have added documentation to explain my changes.
- [X ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
- [ X] This PR is …
=> Added animated testimonial

Games/Games.html, Games/Retirment planning game.html, index.html
Fixes: #2944 
Adding a new page for the "GAMES" section and Adding a new game to the games page "Retirement Planning Game".
https://github.com/user-attachments/assets/cefbbb56-d40f-453e-b432-aba5b9351a14
=> Adding a new page for the "GAMES" section and Adding a new game to the games page "Retirement Planning Game" 

navbar.css
Fixed the vertical misalignment of the theme toggle button by adjusting its position to align properly with the login/register button.
Closes #2912
Fixes: #2912
- Applied a small vertical offset to match the login/register button height
Before: Theme toggle button was misaligned vertically
After: Theme toggle button is now properly aligned with other header elements
👋 @deepeshmlgupta  Please review these UI alignment changes when you have a moment.
=> 🎨 Fix: Theme Toggle Button Vertical Alignment

Games/Financial Goal Tracker Challenge.html
Add back to home button that redirect to home page
Before:-
[Uploading Screenshot (76).png…]()
After:-
https://github.com/user-attachments/assets/7fecf23b-c0c1-497c-b5da-0cc8b26da97c
=> Add back to home button 

addBlog.html, blog.html
Fixes: #2961 
https://github.com/user-attachments/assets/52557e73-21f5-4c0d-9809-35d864ed0a08
A full CRUD operation for blog data,
enabling users to create, update, read,
with dynamic rendering to seamlessly display updated content
, providing a smooth, 
interactive blog experience.
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] I have taken help from some online resources.
- [X ] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [X ] I have added documentation to explain my changes.
- [ X] Make …
=> CURD Operation on blog data and dynamically rendering the blog from backend API

index.html
Fixes: #2814 
I have corrected font size of home page main heading, corrected the footer gap, and testimonial section side arrow(next/prev) buttons.
=> Misaligned Testimonial Section and Slide Functionality Issues

Games/Games.html, Games/Investment Strategy Game.html
Fixes: #2943 
Adding a new game to the website - "Investment Strategy Game" 
https://github.com/user-attachments/assets/2045e0a5-1417-4e9c-b595-c9fffefffdbe
=> Adding a new game to the website - "Investment Strategy Game" (Issue #2943)

assets/css/about.css
Fixes: #3004 
Now the About.css file is made readable and understandable. about.css file updated.
=> Issue number #3004 is solved 

assets/js/contributors.js
All the contributors added instead of just 30
Before 
After
https://github.com/user-attachments/assets/3a9a0acd-2df9-494b-b68b-ec55373ca476
=> All contributors added

blogs/terms-of-service.html
fixes: #3038 
ADDED CURSOR TRAIL EFFECT TO TERMS OF SERVICE PAGE
=> ADDED CURSOR TRAIL EFFECT TO TERMS OF SERVICE PAGE 

Games/Games.html
Fixes: #3008
Adding "NAVBAR" to the games page for smoother navigation .
=> Adding "NAVBAR" to the games page for smoother navigation (Issue #3008)

contributors.html
Added a cursor trail effect to enhance the visual experience on the "Contributors" page, aligning with the existing theme. This effect subtly follows the cursor, adding an interactive and cohesive touch that complements the page's aesthetic.
fixes: #3030
@deepeshmlgupta @Sampadatiwari @sampadatiwari30
=> Added a cursor trail effect 

reviews.html
Fixes: #3060
Added a cursor trail effect to enhance the visual experience on the REVIEWS page, aligning with the existing theme.
This effect subtly follows the cursor, adding an interactive and cohesive touch that complements the page's aesthetic.
=> Added a cursor trail effect to REVIEWS page

faq.html
Fixes: #3062 
Added a cursor trail effect to enhance the visual experience on the FAQ page, aligning with the existing theme.
This effect subtly follows the cursor, adding an interactive and cohesive touch that complements the page's aesthetic.
=> Added a cursor trail effect to FAQ page

index.html
Fixes: #3049
IT LOOKS LIKE THIS CHANGE SARE PREETY SIMPLE BUT TRUST ME THERE ARE SOME PROBLEMS TO DO THIS DESIGNING , LIKE:-
- WHEN WE GIVE BACKGROUND COLOR OTHER CARDS GET DISAPPEARED
- GIVE BG COLOR TO CARD IS NOT ONLY CSS WORK IN IT YOU ALSO NEED TO DO SOME CHANGES IN JS FOR THAT DESIGN
- NEED TO MAKE RELATIONSHIP BETWEEN CSS AND JS
I ENHANCED THE "USER EXPERIENCE" SECTION-
- BACKGROUND COLORS CHNAGED WHENEVER CARDS GET IN FOUCUSED 
- EYE COMFORT BG COLORS
- HOVER EFFECTS
- CHANGE PADDING-MARGIN SO THAT IT DON'T LOOKS LENGHTY
BEFORE:-
AFTER:-
=> ENHANCEMENT NEEDED IN "USER EXPERIENCE" SECTION #3049

finance.html
#2732 
Added a Bottom to top Button.
by adding this feature , user can easily scroll or redirect to top by clicking on the arrow.
=> Bottom-top-button Add

loginPage.html
Fixes: #3068 
Closes: #3068 
added the sign-in button on sign-in page to get better user experience .
https://github.com/user-attachments/assets/730b26b6-671d-407a-ad51-cd984686c231
=> fixing bug on signin page

assets/css/index.css, index.html, loginPage.html
Fixes: #3069 
Closes: #3069 
I'm improve the Ui of Discussion Forum according to the website theme and same color combination and some CSS properties
before changes: 
after changes: 
https://github.com/user-attachments/assets/06724fbc-f2bc-4167-8537-c13606d5e19e
=> Update UI of Discussion forum 

blog.html
Fixes: #3023 
I have fixed the hamburger icon toggle issue in the blog page in mobile version, so user can navigate to other pages from the blogs page also..
https://github.com/user-attachments/assets/23ee8bff-4134-4c8d-b972-ae0f46f18ee4
=> Fixed hamburger icon toggle issue in blog page

README.md
Fixes: #3056 
Added back-to-top scroll up button in readme for easier navigation.
=> added back-to-top scroll up button in readme

finance.html
Fixes: #3073 
Added a cursor trail effect to enhance the visual experience on the FINANCE page, aligning with the existing theme.
This effect subtly follows the cursor, adding an interactive and cohesive touch that complements the page's aesthetic.
Kindly merge with level 2.
@deepeshmlgupta @Sampadatiwari @sampadatiwari30
=> Added a cursor trail effect to FINANCE page

Games/Games.html
=> Favicon added and cursor

Games/Financial Goal Tracker Challenge.html
Fixes: #3088
Added a cursor trail effect to FINANCIAL GOAL TRACKER page.
=> Added a cursor trail effect to FINANCIAL GOAL TRACKER page

Games/Investment Strategy Game.html
Fixes: #3093
IMPLEMENTED a cursor trail effect & Favicon to INVESTMENT STRATEGY GAME page
=> IMPLEMENTED a cursor trail effect & Favicon to INVESTMENT STRATEGY GAME page

Games/Retirment planning game.html
Fixes: #3091
Added a cursor trail effect & Favicon to RETIREMENT PLANNING PAGE
=> Added a cursor trail effect & Favicon to RETIREMENT PLANNING PAGE

blogs/terms-of-service.html, index.html
Fixes: #3095
basically i just resolve content in a of buttons in this section and also change its padding and margin so that it will look good an more responsive
BEFORE:-
AFTER:-
=>  UNNECESSARY CONTENT IN "USERS SHARING THEIR EXPERIENCE" #3095

blogs/terms-of-service.html
Fixes: #3097
BASICALLY I ADD CURSOR EFFECT IN "TERMS OF SERVICE"
=> add cursor trail effect in "terms of service" #3097

termsOfUse.html
Fixes: #3106 
Aligned the cursor trail effect on the Terms of Use page with the site's overall theme for a more consistent user experience.
=> Updated Cursor Trail Theme on Terms of Use Page 🌠

Games/Cryptocurrency Trading Game.html, Games/Games.html
Fixes: #3081 
Adding a new game - "Cryptocurrency Trading Game"
https://github.com/user-attachments/assets/52885c7f-2418-4772-bd9a-f052c6165edf
=> Adding a new game - "Cryptocurrency Trading Game"

blog.html, finance.html, quiz.html, tools/sip.html
Fixes: #3085
I have made the color of the newsletter consistent across all pages...Adjusted the color in four pages(blog,courses,tools, and quiz page) to make it consistent..
@deepeshmlgupta kindly review the PR
=> Added consistent newsletter color across all pages

index.html
Fixes: #3080 
fixing the scroll down button alignment and working.
https://github.com/user-attachments/assets/3e0e466a-bea3-41d1-b6fe-32acf2b19298
=> fixing the scroll down button alignment and working

Games/Financial Freedom Adventure.html, Games/Games.html
Fixes: #3078 
Add a new game - "Financial Freedom Adventure" 
https://github.com/user-attachments/assets/6bce64dd-9e75-4160-8dc1-1e2f261a05b5
=> Add a new game - "Financial Freedom Adventure" 

index.html
Fixes: #2994 
- Implements responsive design adjustments for the newsletter popup to enhance mobile usability.
- Hides the image section on screens smaller than 768px, allowing the popup content to stack vertically for better readability on mobile devices.
- Adjusts font sizes, button height, and padding within the popup to improve the user experience on smaller screens.
- Enhances the project by ensuring the popup is fully accessible and user-friendly across various device sizes without sacrificing readability or layout structure.
=> Solved #2994

contributors.html
Fixes: #3104
basicallly i added navbar and footer in this page
AS IT LOOKS LIKE A  VERY EASY JOB BUT IT'S NOT BEACAUSE WHEN WE TRY TO GIVE NAVBAR AND FOOTER ON THIS WITH SIMPLE BASIS IT CHANGE THE WHOLE CONTENT OF PAGE LIKE CHANGES THE COLOR OF CARDS SO AT HERE I NEED TO FIND THAT PARTICULAR ELEMENTS AND I NEED TO GIVE INLINE CSS .
before:-
after:-
=> NEED TO ADD NAVBAR AND FOOTER IN CONTRIBUTOR PAGE #3104

404.html
Fixes: #3124
CURSOR TRAIL EFFECT ADDED IN ERROR 404 PAGE.
=> NEED TO ADD CURSOR TRAIL EFFECT IN 404 PAGE #3124

about.html
Fixes: #3072 
The previous and next buttons in about page carousel were not visible on hover ..i have fixed that issue..
- [ +] Bug fix (non-breaking change which fixes an issue)
https://github.com/user-attachments/assets/24444e99-8d7a-4297-9dfe-5dd56b87b1aa
@deepeshmlgupta @sampadatiwari30 Kindly review the PR
=> Fixed navigation buttons visibility in hover

Games/Financial Freedom Adventure.html
Fixes: #3133 
Added a cursor trail effect & Favicon to FINANCIAL FREEDOM ADVENTURE page
=> Added a cursor trail effect & Favicon to FINANCIAL FREEDOM ADVENTURE page

Games/Financial Freedom Adventure.html, Games/Games.html, index.html
Fixes: #3079
Adding Enhanced scroll back button with a progress ring to the home page and making smooth slide.
https://github.com/user-attachments/assets/6dd9bb44-0c0a-43e3-be6d-3199a85fbedc
=> Adding Enhanced scroll back button with a progress ring to the home page and making smooth slide

Games/Financial Goal Tracker Challenge.html, Games/Investment Strategy Game.html
Fixes: #3136
Added NAVBAR in FINANCIAL GOAL TRACKER page
=> Added NAVBAR in FINANCIAL GOAL TRACKER page

Games/Games.html, Games/Tax Filing Game.html
Fixes: #3132 
Adding a new game - Tax Filing Game
https://github.com/user-attachments/assets/b7b22740-4b88-4ab2-9016-f0d5f4f3c7ec
=>  Adding a new game - Tax Filing Game

about.html, blog.html, contact.html, faq.html, index.html, maps.html, quiz.html, termsOfUse.html
every page has this footer alignment
Fixes: #2990 
changed footer section for all the pages
=> done with the changes #2990

index.html
=> issue number #3120 is solved

Games/Retirment planning game.html
Fixes: #3182 
Added NAVBAR in RETIREMENT PLANNING GAME page
=> Update Retirment planning game.html

blogs/Pocketmoney.html, blogs/real-estate-economics.html, blogs/saving-for-future.html, blogs/senior.html, blogs/sitemap.html
Fixes: #3170
as in this PR I  changed the designing of footer from 5 PAGES "POCKETMONEY, REAL-ESTATE, SAVING-FOR FUTURE, SENIOR , SITEMAP" PAGES.  and try to give them same designing which is present at home page.
WHAT I DO:-
- link important files
- delete designing which overwrites the css
- give proper margin-padding
Before:-
After:-
=>  FOOTER ENHAMENT NEEDED IN SOME PAGES #3170

blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html
Fixes: #3168
as in this PR I  changed the designing of footer from 5 PAGES " empowering, fintech, generational-wealth, unknown-risks , invest minimal page, mutual funds"  and try to give them same designing which is present at home page.
WHAT I DO:-
- link important files
- delete designing which overwrites the css
- give proper margin-padding
Before:-
After:-
=> FOOTER ENHANCEMENT IN SOME PAGES #3168

assets/css/contributors.css, contributors.html
Before
After
https://github.com/user-attachments/assets/09e73bfe-f1eb-48aa-9723-e4bdf4e09360
=> Broken Contributors page fixed

blogs/economic-trends-and-analysis.html
Fixes: #3165
BASICALLY I JUST ENHANCE FOOTER OF THAT PAGE AS IT IS NOT MATCHING WITH THE OTHER PAGES FOOTER.
BEFORE:-
AFTER:-
=> FOOTER ENHANCEMENT IN ECONOMIC TRENDS AND ANALYSIS PAGE #3165

Cookiepolicy.html, about.html, blog.html, contact.html, contributors.html, faq.html, finance.html, index.html, maps.html, quiz.html, tools/sip.html, trends.html
Fixes: #2908
This update ensures a consistent design for the "Back to Top" button on every page of the site. The button styling has been aligned with the "Back to Top" button found on the About page, as it offers an optimal user experience. This enhancement improves usability and visual uniformity across the website, making navigation smoother for users.
https://github.com/user-attachments/assets/83eba9b7-f628-48e4-aaf9-8818d976ce95
=> Standardize 'Back to Top' button design across all pages

Cookiepolicy.html, about.html, blog.html, contact.html, contributors.html, faq.html, finance.html, index.html, maps.html, quiz.html, trends.html
Fixes: #2907 
This update introduces a dedicated Cookie Policy page to provide users with clear information about cookie usage. The page has been linked in the footer for easy access across all pages, ensuring transparency and compliance with user expectations for privacy. The footer layout was also adjusted to accommodate this new link while maintaining a clean, organized design.
https://github.com/user-attachments/assets/e75fd348-e0cc-45bb-b941-4be87a1e0804
=> Added Cookie Policy page and link in footer

assets/js/quiz_modify.js, quiz.html
Fixes: #3075
In the quiz section, I have added a custom alert box which apears when user clicks submit button without selecting an option..
https://github.com/user-attachments/assets/6ee48dc7-13bc-4152-90fc-04d6f09cd291
=> Added custom alert popup on quiz section

contact.html
Fixes: #3158
so basically i just improve the cursor effect in contact page as it is not working properly first it showing delay and also older is so long that it was also hiding objects for long time.
BEFORE:-
https://github.com/user-attachments/assets/30a18f17-9b67-4865-adc3-66badab9204f
AFTER:-
https://github.com/user-attachments/assets/2ec3cd3a-7939-43fd-b819-fc44ff2d34e9
=> ENHANCEMENT IN CURSOR EFFECT IN CONTACT PAGE #3158

Cookiepolicy.html
Fixes: #3191
so basically i just improve the cursor effect in cookie page as it is not working properly first it showing delay and also older is so long that it was also hiding objects for long time.
=>  CURSOR EFFECT ENHANCEMENT IN OUR COOKIES PAGE #3191

blog.html
Adds all the blogs in the blogs page.
Before
After
https://github.com/user-attachments/assets/b3e783c9-f7c0-41e1-9c43-198c0e2615f7
=> Broken blog page fixed

Games/Games.html
Fixes: #3188 
Earlier, navbar links were not working. now the Navbar is WORKING PROPERLY on GAMES page. 
https://github.com/user-attachments/assets/e5efa3d1-e194-4d30-b557-1881095ae854
=> Navbar WORKING PROPERLY on GAMES page

Games/Tax Filing Game.html
Fixes: #3186 
Added a cursor trail effect & Favicon to TAX FILING GAME page
=> Added a cursor trail effect & Favicon to TAX FILING GAME page

assets/css/style.css
Improve text color done - #3175
Before - These text color blends with background color in both dark and light mode,
Now - Fixed
- [] I have taken prior approval for this feature/fix.
=> Improve text color done ! #3175

faq.html
Fixes: #3143 
Adding Enhanced scroll back button with a progress ring to the help page and giving a smooth slide. 
Uploading FAQ - FinVeda - Brave 2024-11-09 22-20-24.mp4…
=> Adding Enhanced scroll back button with a progress ring to the help page and giving a smooth slide. 

creditCard.html
Fixes #3193
ADD CURSOR TRAIL EFFECT IN CREDIT CARD PAGE
VIDEO PROOF:-
https://github.com/user-attachments/assets/082701b2-b53d-4ec4-86da-34bd9476c17f
=> ADD COURSOR EFFECT IN "CREDIT CARD" PAGE #3193

assets/css/contributors.css, assets/css/style.css, contributors.html
Fixes: #3148 
Closes: #3148 
improvement Code of toggle button on Contributors page 
Uploading Screen Recording 2024-11-09 214524.mp4…
https://github.com/user-attachments/assets/16960222-6b84-4f67-bbb6-e6e840e9741b
=> Fixing Scroll button on Contributors page 

about.html, assets/css/index.css, assets/css/style.css, blog.html, contact.html, contributors.html, faq.html, index.html, maps.html, quiz.html
Fixes: #3177 
Closes: #3177 
i'm improve the all footer's alignment and background colors and so on.
=> Fixing footer on all pages

events.html
Fixes #3199
ADD CURSOR TRAIL EFFECT IN EVENT PAGE
VIDEO PROOF:-
https://github.com/user-attachments/assets/4a105c8b-367f-4ea5-9b53-2ac190e9f7ed
=> NEED TO ADD COURSOR EFFECT IN "EVENTS" PAGE #3199

profile.html
Fixes #3202
ADD CURSOR TRAIL EFFECT IN PROFILE PAGE
VIDEO PROOF:-
https://github.com/user-attachments/assets/265f1937-2d4f-43bd-a015-fd0d75403526
=> NEED TO ADD COURSOR EFFECT IN "PROFILE" PAGE #3202

about.html
Fixes: #3100 is solved.
In the about page Now good card is responsive in the mobile version.
=> Good cards issue is solved, Issue number #3100 is solved

loginPage.css, loginPage.html
I fixed the bug in the sign up button i.e when the button was clicked it didnot changed to signup page and it  is fixed in this PR
Before
https://github.com/user-attachments/assets/9b4393cc-29d4-41c8-ab37-623135e3bbf0
After
https://github.com/user-attachments/assets/49d3b97e-a3d6-4642-834c-e8fb2f4851a3
=> Login page fixed

assets/css/blog.css, blog.html, blogs/terms-of-service.html, faq.html
Fixes: #3131 
This update improves the overall user interface of the Help Page to create a more intuitive and accessible support experience. Changes include:
Simplifying layout and navigation for easier access to information.
Enhancing button styles and font choices to ensure better readability.
Introducing a consistent color scheme that aligns with the site's design, providing visual clarity across light and dark modes.
Adding clearer headings and sections to help users quickly find the assistance they need.
https://github.com/user-attachments/assets/82f4c57d-2bd0-4fd7-8842-513ea2503447
=> Improve help page UI

blogs/terms-of-service.html
Fixes: #3129 
The Terms of Service page currently does not reflect dark mode settings, resulting in a poor user experience for those who prefer or need dark mode. This fix will:
Ensure the page styling dynamically responds to dark mode settings.
Align the Terms of Service page's dark mode styling with the rest of the site for a consistent user experience across all pages.
Improve accessibility and readability by adhering to the selected display mode preferences.
https://github.com/user-attachments/assets/ac022025-bc55-4b57-a0f4-68eb461677cd
=> Fix dark mode functionality on Terms of Service page

assets/css/blog.css, blog.html, blogs/terms-of-service.html
Fixes: #3130 
This update focuses on improving the UI of the blog post page to provide a cleaner, more engaging reading experience. Changes include:
Enhancing typography and spacing for better readability.
Updating the layout to include clearer sections for headings, body text, and images.
Adjusting color contrast to improve visibility, especially in dark mode.
Streamlining the design to ensure a more cohesive look with other pages across the website.
https://github.com/user-attachments/assets/499a185b-e478-4618-845b-4835a7769d30
=>  Revamp UI for blog post page to improve readability and user engagement

Testimonials.html, contact.html, faq.html, index.html, quiz.html, reviews.html, substainability.html, termsOfUse.html
Fixes: #3055 
In social media section the linkedin icon was not there, i have added that icon in each and every page of the website
=> Linkedin Icon added to every page of website

Testimonials.html
Fixes: #3054
The testimonials page was constantly buffering but now it's been modified.
here's the output
https://github.com/user-attachments/assets/639b4d46-bf4f-4b13-a2e5-21da4c5ba843
=> Testimonials Page modified

Testimonials.html
Fixes #3232
ADD CURSOR TRAIL EFFECT IN Testimonials PAGE
=> NEED TO ADD COURSOR EFFECT IN "TESTIMONIALS" PAGE #3232

Games/Tax Filing Game.html
Fixes: #3220 
Added NAVBAR to TAX FILING page
=> Added NAVBAR to TAX FILING page

Games/Investment Strategy Game.html
Fixes: #3214
Added NAVBAR to INVESTMENT STRATEGY page
@deepeshmlgupta kindly merge it
=> Added NAVBAR to INVESTMENT STRATEGY page

Games/Games.html
Added the missing button to the Games page dropdown ! 
Now -
Before -
=> Added the missing button to the Games page dropdown ! 🌟🌟

quiz.html
Added the missing button to the Quiz page dropdown ! 
Now -
Before -
=> Added the missing button to the Quiz page dropdown ! 🌟🌟

blog.html
Added the missing button to the Blogs page dropdown ! 🌟🌟
Now -
Before -
=> Added the missing button to the Blogs page dropdown ! 🌟🌟

contact.html
Added the missing button to the Contact page dropdown ! 
Before -
Now -
=> Added the missing button to the Contact page dropdown ! 🌟🌟

finance.html
Added the missing button to the Courses page dropdown ! 
Before -
Now -
=> Added the missing button to the Courses page dropdown ! 🌟🌟

pie.html
Fixes: #3053
https://github.com/user-attachments/assets/8ecf0360-8eeb-496b-ac4d-19c8ed946d5a
=> Pie - chart generator added

blogs/terms-of-service.html
Fixes #3243
ADD PRELOADER AND PROGRESS BAR IN TERMS OF SERVICE. AS THESE FEATURE IS AVAILABLE IN OTHER PAGES AS WELL.
=> ADD PRELOADER AND PROGRESS BAR IN TERMS OF SERVICE #3243

Games/Financial Freedom Adventure.html
Fixes: #3224
Enhance Financial Freedom Page with Navbar and Improved UI/UX Design
=> Enhance Financial Freedom Page with Navbar and Improved UI/UX Design

contributors.html
Fixes: #3218 
I have fixed the  newsletter misalignment in contributors page
Before:
After:
@sampadatiwari30 @deepeshmlgupta Please review the PR
=> Fixed newsletter misalignment in contributors page

substainability.html
Fixes #3206
ADD CURSOR TRAIL EFFECT IN SUSTAINABILITY PAGE
VIDEO PROOF:-
https://github.com/user-attachments/assets/b636694f-53a0-47bb-a561-aba751ea1748
=> NEED TO ADD COURSOR EFFECT IN "substainability" PAGE #3206

about.html, contributors.html, index.html
Fixes: #3263 
I have added a cute symbol before each making it look cool and more visually engaging
- [✅ ] New feature (non-breaking change which adds functionality)
- [ ✅] I am a participant of GSSoC-ext.
- [✅ ] I have followed the contribution guidelines of this project.
- [ ✅] I have made this change from my own.
- [✅ ] My code follows the style guidelines of this project.
- [ ✅] I have performed a self-review of my own code.
- [✅ ] I have added documentation to explain my changes.
- [✅ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
- [✅ ] This PR is submitted under the GSSoC program.
- [ ✅] I have taken prior approval for this feature/fix.
=> Enhancing project statistics section

about.html
Fixes: #3260
👨‍💻 Description
What does this PR do?
Implements animated flip cards with a glassmorphism effect on the homepage for enhanced user interaction.
Each card has a "front" and "back" face, providing additional details when flipped on hover.
Enhances the services section by making it more visually appealing and interactive.
📄 Type of Change
- [ ✅] New feature (non-breaking change which adds functionality)
- [ ✅] I am a participant of GSSoC-ext.
- [✅ ] I have followed the contribution guidelines of this project.
- [ ✅] I have taken help from some online resources.
- [ ✅] My code follows the style guidelines of this project.
- [ ✅] I have performed a self-review of my own code.
- [✅ ] I have added documentation to explain my …
=> animated cards
