ayush-that/FinVeda

assets/css/style.css
Fixed Issue #25
Change: Align the Navbar properly according to the website alignment. 
The Navbar of each web page is properly aligned.
All lines of code are
my original content and not plagiarized.
=> Fixed the navbar according to website alignment.

tools/emiCalculator.js, tools/sip.html, tools/sipcalculatorCss.css
Have added the EMI calculator in the tools page as proposed, maintaining the style of the FinVeda website. Please review the changes.
=> Added EMI Calculator to Tools page [Issue #21]

assets/css/style.css
I had added a customised scrollbar to the website , please review my pull request.
=> Added customised scrollbar

assets/css/style.css
Changed the width of text box and corner radius for subscription
=> Fix issue #23 

assets/css/quiz.css, index.html, login.html, quiz.html
add the hover effect to the cursor making it userfriendly
=> changed the effect of option click added the hower to curser

assets/css/style.css, index.html
Removed the bug from the navbar now u can see there is no color while it is scrolled down!!
=> Removed the bug from the navbar

assets/js/ajax-contact.js
Resolves #76 . 
This pull request improves the JavaScript code in contact-form.js by removing redundant jQuery wrapping and using the `$(function() { ... })` shorthand for `$(document).ready(function() { ... })`. The changes make the code more concise and efficient while ensuring it executes after the DOM is fully loaded.
=> Refactor ajax-contact.js

assets/css/style.css, index.html
=> Changed the logo of twitter to X

assets/css/style.css
> Added CSS rules to create a hover effect on navbar items.
> Utilized the ::after pseudo-element to animate the underline on hover.
> Adjusted transition duration for smooth animation.
> Tested hover effect on various screen sizes and browsers.
> Checked for compatibility with existing styles and responsiveness.
https://github.com/ayush-that/FinVeda/assets/71984091/6203e4ea-e972-4f9e-aea4-cc1671a42de2
=> Added hover effect to navbar items as per your requirement

blog.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html, index.html, login.html, quiz.html, trends.html
Fixed issue #121 
- Updated the footer to display the current year dynamically using JavaScript.
- Replaced the hardcoded year with a <script> tag that inserts the current year.
- Ensures the footer year is always up-to-date without manual changes.
=> Add dynamic current year to footer

assets/js/vanilla-tilt.js, index.html
I have added animation on the laptop image on the landing page
This PR fixes #33 
Animation details
If the cursor is not moved on the laptop, the laptop's image will float up and down. When the cursor is moved, it tilts the image with respect to the cursor
https://github.com/ayush-that/FinVeda/assets/115486960/7d90efe9-bf5d-4220-aafb-9d4b8fa4e757
=> Added Animation

assets/css/style.css, blog.html, index.html, login.html, quiz.html, tools/sip.html, tools/sipcalculatorCss.css, trends.html
#89 improved the ui of tools both calculators
feat #89 
merge pull request under gssoc'24
=> Feat/improve UI tools calculator

index.html
Reverts ayush-that/FinVeda#189
=> Revert "fixed small bugs in html code and corrected dynamic year"

assets/css/style.css
Resolves issue #204 
Description -> Added `ease` hover transition effect to "Our Recent Blog Posts" section
Resolved image ->
=> Added ease hover transition to "Our Recent Blog Posts" section

tools/npvCalculator.js, tools/sip.html, tools/sipcalculatorCss.css
I have added the NPV calculator in the tools page as proposed, maintaining the style of the FinVeda website.
Please review the changes.
Here is a photo for reference :-
Please check and merge the PR @ayush-that .
I have also added the description of NPV Calculator as you mentioned in PR #168
=> Added NPV Calculator [Issue No. #68]

assets/css/style.css
=> made the back-to-top and chat button aligned

assets/css/style.css
=> Fixes Scroll Bar #135

assets/js/quiz.js
@ayush-that I have resolved the issue successfully.
Now,explanations too are visible with every incorrect answer.
Please check and merge the PR.
=> Resolving issue Explanation is absent in quiz #262

assets/css/style.css, assets/js/quiz.js, blog.html, index.html, quiz.html, tools/sip.html, trends.html
@ayush-that 
Fixed issues: #202 #203
Thanks for assigning me for both these issues #202 and #203.
Here I created a single PR for both the issues #202 and #203. 
#202 resolved and now quiz result will not come until user doesn't select at least one answer for each question. Previously this functionality was missing in the project, you can compare my work with these screen videos:-
Video(before my work):
https://github.com/ayush-that/FinVeda/assets/135222259/37036e22-6b7d-498b-8f0d-8bef38bfb5db
Video(After my work):
https://github.com/ayush-that/FinVeda/assets/135222259/5328ac14-3471-4984-8ae4-55fd24b893ff
#203 resolved and now that particular page will get active which is visited. You can compare the changes in the following screen videos:-
Video(Before my work): …
=> Resolved both issues #202 and #203

assets/css/style.css, index.html
#310 closes as it is done by me assigned by @deepeshmlgupta under gssoc label.
Screenshot 1 (in desktop view)
Screenshot 2 (responsiveness)
=> Added icons in contact section 

assets/css/bootstrap.min.css
Enhancement done in the Login/Register page with borders in every text item, its have better UI.
closes issue no. #298  
with the label and level of GSSOC.
Screenshots:
=> Enhancement done in the Login/Register page with borders.

blog.html, index.html, login.html, quiz.html, tools/sip.html, trends.html
Fixes #286 
Added a link for "Don't have a account, Register" which will open the registration modal asking from email, username, password. 
Added this on all pages with the login button. (index.html, blog.html, login.html, sip.html, quiz.html, trends.html)
PLEASE ADD GSSOC AND LEVEL LABELS BOTH ON THE PR AND RELATED ISSUE.
=> Registration Modal added

blog.html, index.html, quiz.html, tools/sip.html, tools/sip_PPF_cAL.html, trends.html
Issue Closes #328
Hey @ayush-that and @deepeshmlgupta 
I have added the "Scroll Down Progress Bar" To All Pages.
https://github.com/ayush-that/FinVeda/assets/101971980/2f68f967-eb18-44d5-abbe-209e56f919d3
Please take a look and review it, Thank You!!
=> Added "Scroll Down Progress Bar" To All Pages

login.html
fixes #335 
Location : Sign in and register page
Issue resolved
=> Eye visibility icon

assets/css/style.css, index.html
=> Add hover effect on Login/Register btn

Licensing.html, index.html
Hey @ayush-that and @deepeshmlgupta  | Issue Closes #330
I have added  Dedicated "Licensing" Page Reflecting "GPL-3.0 License" matching to the website design theme
Please Take a look and review it, Thank You!!
https://github.com/ayush-that/FinVeda/assets/101971980/acca68e2-d3ac-4a22-a433-d4bb651dcbae
=> Added Dedicated "Licensing" Page Reflecting "GPL-3.0 License"

assets/css/style.css
changed the go to top button colour in match with the chat bot color.
closes issue #327
Kindly tell if any more changes required.
=> changed the go to top button colour

blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html
Hey @ayush-that, @deepeshmlgupta 
issue closes #341,
I have added the Scroll down progress bar to the missing pages in the footer section.
Here is the video - 
https://github.com/ayush-that/FinVeda/assets/131389695/03b3f2ab-a4b8-4908-b3a5-fb78ad8dadf1
=> Added Scroll down Progress Bar to Missing Pages

assets/css/style.css, index.html
Added social media links to the footer along with social media favicons
=> Added social media links  in the footer

assets/css/style.css, index.html
Reverts ayush-that/FinVeda#336
=> Revert "Added social media links  in the footer"

blog.html
Fixed the arrows alignment, according to issue #98
=> Fixed Arrows in blog posts section

tools/sipcalculatorCss.css
I have fixed the alignment of the button in NPV Calculator. Please merge it with the main branch
#216
=> Fixed the alignment of calculate btn in NPV calculator

Licensing.html, blog.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html, index.html, login.html, quiz.html, tools/sip.html, tools/smoothScroll.js, trends.html
- Scroll to top behaviour has been made smooth in all the html pages where the button exists.
- I have added a extra Javascript file for implementing smooth scroll to top in the tools folder and linked it in all html pages with back to top button
Fixes #280
=> smooth-scroll-to-top added in all pages:

assets/css/style.css, index.html
#361
double clicking the feedback icon modal feedback form shall pop out submitting the feedback of users successfully 
https://github.com/ayush-that/FinVeda/assets/158484284/114aab51-dd57-4f2b-911f-511af0ef81e8
=> modal feedback form

index.html
I've added the feature of sending mails to user when they subscribe to newsletter.
fixes #346 
success alert on clicking the subscribe button
email sent to the user
=> feat: Thankyou email on newsletter subscription

assets/css/preloader.css, assets/css/style.css, assets/js/preloader.js, index.html
fixes #334 
https://github.com/ayush-that/FinVeda/assets/146121869/68724bdd-761f-4e33-8932-6de6279d62ff
=> Added Preloader

blog.html
**Fixes #391** 
Properly added the properties, for user convenience
=> Added link properties on blog posts

blog.html, login.html, quiz.html, tools/sip.html, trends.html
Hey @ayush-that and @deepeshmlgupta issue closes #377 
I have added a Licensing Link in the Footer Across All The Pages 
=> Added Licensing Link in Footer Across All The Pages 

tools/sipcalculatorJs.js
Updated the code so that the calculator would not accept negative or invalid inputs
solved issue #382 .
Please merge my PR
=> Updated the sipcalculatorJs.js file

assets/css/style.css, index.html
Hey @ayush-that and @deepeshmlgupta 
issue closes #389 
1. **Changed "Complete UI" of the Feedback Form** with **Effective Wordings Used.**
2. **Styled the Form** to follow the **Color theme of the Website.**
3. I **Added "Custom Popup" Message** after feedback is submitted.
4. **Added "Star Rating" System** with Much Better Hovering Effects.
5. **Added "Reset Functionality" to the form** so that After submitting, **it will be available for new one.**
6. **Added "Back to Home" Button** to the **Custom Popup.**
7. Also **at the Top of Feedback** form **i added a "Close(x)" Button** to close the form
8. Overall, **Improved the Visibility** So that it will **keep enganging the Users** with the website.
**Here is the Custom Popup -**
**Here is the Overall Implementation** …
=> 💥 Improved "Complete UI and Functionality" Of the Feedback Form 

tools/roiCalculator.js, tools/sip.html
=> ROI calculator added

assets/css/style.css
issue no #336 
I have added new scrollbar with radius thumb , hover effects like cursor pointer and black shadow on thumb , make scrollbar thumb color more attractive use different shades of blue in scrollbar thumb.
**On hover**
=> Added new scrollbar with hover effects

assets/css/style.css, index.html, tools/smoothScroll.js
- Issue fixes #353
Hey @deepeshmlgupta and @ayush-that 
I have Re-Designed The "Scroll-to-Top" button Matching to "Website Design" Theme
**Changes I made:**
- Made the Back-to-top button circular in shape 
- Added Hover and the color. Base Color: `#666BEA` | Hover Color `#46498D`
- The button was not working properly I have fixed it
- The button will now only appear if we scroll down a bit from the buttons.
- Aligned it properly!
https://github.com/ayush-that/FinVeda/assets/101971980/e3423f64-928f-4ed9-915c-aa89212cadf4
Could you please take a look on this tasl?
=> Re-Designed The "Scroll-to-Top" button Matching to "Website Design" Theme

assets/css/style.css, blog.html, index.html, quiz.html, tools/sip.html, trends.html
ISSUE NO: #381
https://github.com/ayush-that/FinVeda/assets/121508628/ede1426f-d1a2-43f2-ad34-42b8dbb42409
**If it's not good, please assign me again I will do it better**
**Please add Level Labels for this PR**
=> Title: show and hide button near password input

assets/css/style.css, blog.html
Issue : #417 
In the blog page at single blog section i have added the hovering and border effects to make the blogs better user experience and user interface.
before:
The duplicate data also been removed.
After:
Looks good.
@ayush-that  and @deepeshmlgupta  , please check my changes and merge the changes to the project to make contribution to the project.
Thank you
=> Title : Hovering and border effects added to Blogs

assets/css/style.css
Hey @deepeshmlgupta 
- issue fixes #411 
I have Fixed Feedback button's Hiding Under Chatbot Container 
Please take a look and review it, thank you!
=> Fixed Feedback button's Hiding Under Chatbot Container 

index.html
issue no #401
Reset input in 3 sec.
Message shown under form not in alert form and hide after 3 sec.
=> Reset newslatter and message under form shown

assets/css/style.css, blog.html
Reverts ayush-that/FinVeda#424
=> Revert "Title : Hovering and border effects added to Blogs"

blog.html, quiz.html, tools/sip.html, trends.html
Issue : #407 
In the footer section at contact column there are icons are missing in many pages , I has added those icons to all the pages where they were required.
Before:
After:
@ayush-that  and @deepeshmlgupta  , Please check my changes and merge the changes to the project to make contribution to the project.
Thank you
=> Title: Icons is added to footer section in all pages

index.html
Made the mail link in the footer clickable for convenient contacts
Issue #418
=> Made mail link clickable

package-lock.json, tools/SavingsGoalCalculator.js, tools/sip.html, tools/sipcalculatorCss.css
Added a Savings Goal Calculator which helps to set and achieve savings goals by calculating the monthly savings needed.
Please check and merge the PR @ayush-that .
I would be really thankful if you assign me the appropriate level with this PR.
=> [Feature] Added Savings Goal Calculator.  [Issue No. #379]

login.html
=> Terms and conditions checkbox

blog.html
I changed the footer of the website by adding a new line to Made with love in India from built with love in India and also aligned the whole text in the middle .This is making the website really more impressive than before .Looking forward to more contributions .
=> A slight change in the footer of the website

blog.html, index.html, login.html, quiz.html, tools/sip.html, trends.html
Added form invalidation to it when someone enter wrong email or passwordd and also added a pop up when someone will login 
Register ⤵️
login⤵️
*It will also show a pop up `login successfully` on clicking on signin.
=> added form invalidation

blog.html, index.html, login.html, quiz.html, tools/sip.html, trends.html
Reverts ayush-that/FinVeda#464
=> Revert "added form invalidation"

tools/sip.html, tools/sipcalculatorCss.css
https://github.com/user-attachments/assets/c7db4b39-da35-48a9-ab5f-12ad26663491
=> Changed the outlook of insurance calculator.

assets/css/quiz.css, assets/js/quiz.js, assets/js/quiz_modify.js, quiz.html
I have modified the quiz section very well! It's more interactive and cool now with answers showing on clicking next button only...
**Before**
**After**
https://github.com/user-attachments/assets/c0ebdc32-d7a9-4e81-b8ff-7955b5066bd4
=> Quiz Section Modified!!

assets/js/arthsathi-style.js, index.html
- I have added 10px gap between Arthsathi chat bot button & go-to-top button using javascript.
- I created a js file `assets/js/arthsathi-style.js` in order to add gap between these buttons.
- Now, the buttons are having gap between each other which makes it easy to click.
_Please review & merge this pull-request under GSSoC'24._
=> Added gap between Arthsathi chat bot button & go-to-top button

assets/css/style.css, index.html
Fixes #457
Fix Overlap of Scroll to top button.
Added counter on Expert Investing Views/Like/Comment added Hover effects.
https://www.loom.com/share/6720c18034904a6582397a6c9d676b76
=> Fix overlapping of scroll to top added hover/counter on Investing Experts views/like/comment

blog.html, index.html
fixes #490 
The tools section is now opening in mobile view. It is responsive.
https://github.com/user-attachments/assets/c849c37f-13b6-400e-9ed5-f5c32ec382dd
=> Tools section responsiveness in mobile view fixed

assets/css/style.css, blog.html, index.html, tools/sip.html, trends.html
fixes #472 
Added proper links to correct headings and rechecked all the footer links and corrected the inconsistencies.
=> Footer links working now

tools/GSTcalc.js, tools/GSTstyle.css, tools/sip.html
Fixes #416 
Added a functional GST calculator which has two calculation modes, inclusive and exclusive of GST.
=> Added GST calculator

assets/css/contributors.css, contributors.html, index.html
Fixes #456
Added Contributor page link given in Quick Links in index.html.
Contributor page is Responsive have hover effects on cards.
=> Contributor page added with responsiveness

assets/css/style.css
Issue : #432 
In the PR I was added the border and hovering effects to the testimonial card, to make better user interface and user experience.
Before:
After:
@ayush-that and @Agarwalvidu , please check my changes and merge the changes to make contribution to the project.
Thank you
=> Title:- Hovering and border effect

blog.html, index.html, quiz.html, tools/sip.html, trends.html
Hey @ayush-that and @deepeshmlgupta issue closes #426 
I have added the feedback comment button to The All Pages.
Please take a look and review this PR
=> Added The Feedback Comment Button to The All Pages

assets/css/style.css
https://github.com/user-attachments/assets/0116fc9a-283f-4099-86e8-95f446ac7a11
I have corrected the error mentioned in issue number #498 . now ,  navbar showing in mobile view also.
=> navbar_mobile_view

blog.html, index.html, login.html, quiz.html, trends.html
This pull request addresses the issue of adding meta tags to enhance SEO performance. Specifically, it adds the author meta tag and updates the content of the description meta tag for several pages. 
Issue number: #501
=> Added author meta tag and content of description tag

assets/css/quiz.css
I corrected the problem of responsiveness coming in the quiz section...I made it responsive for Tablet screen size, (small, medium & large) mobile screens too!!
Fixes #511 
**BEFORE**
**AFTER**
=> Quiz Section got Responsive

tools/IncomeTax.js, tools/sip.html
Fixes #504
Added IncomeTax Calc That Finds Total Tax and Real Income.
Fix Calculate Submit Button responsiveness in GST/RTO Calc.
Make My IncomeTax Clc Responsive.
=> Add Responsive IncomeTax Calc and Made GST/RTO Sumbit Responsive

assets/css/style.css, index.html
Fixes #509 
Added Margin Left for Small screen in Contact section.
=> Added Margin for small screen in footer's contact section

tools/sip.html, tools/sipcalculatorCss.css
Issue #514 solved
Changed the styling of the calculate button. It is now consistent in all the tools.
[ConsistentCalculateButton.webm](https://github.com/user-attachments/assets/1fedfed2-316a-48e3-9b3b-a6f021ce881d)
=> Consistent calculate button

assets/css/bootstrap.min.css, index.html
tell me what type of testimonial you want 🙃
=> testimonial

assets/css/style.css
Change the color of button text on hovering
=> Change the color of button text on hovering

blog.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html, index.html, quiz.html, tools/sip.html, tools/sip_PPF_cAL.html, trends.html
Hey @Agarwalvidu 
I have added the custom cursor of yours in all the pages and also I have added a Ui friendly cursor trail effect across all the pages
- Added new cursor trail effect
- Effect has radial gradient color of `#49e8f7` and `#8d26ac`
-  The CSS and HTML files have been updated to support this change in `index.html`
- The **Trail effect** smoothly **synchronizes** with the cursor movement.
- The `mousemove` event listener adjusts for the vertical scroll position using `window.scrollY.`
- The circles' positions are updated in the `animateCircles` function, ensuring they follow the cursor with a trailing effect.
- It works fast and smoothly across all pages.
https://github.com/user-attachments/assets/d609ac74-b0af-47cb-bc2f-3a2ecd4afb1e
Please take a look and review it!
=> Added Cursor Trail effect Across all the pages

blog.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html, index.html, quiz.html, tools/sip.html, tools/sip_PPF_cAL.html, trends.html
Reverts ayush-that/FinVeda#542
=> Revert "Revert "Added Cursor Trail effect Across all the pages""

index.html
Added the Slider in the Testimonial Section and made the UI clear as of before
=> Added Slider in Testimonial

assets/css/style.css
#539 
completed UI improvement at homepage Button.
-> changed color dark to light color so it can be visible
=> color adjusted 

about.html, assets/js/popup.js, index.html, quiz.html, tools/sip.html, trends.html
Hey @Agarwalvidu 
- Issue fixes #538
I have added User validation and Email Validation to the login/register form
https://github.com/user-attachments/assets/3be0faf0-b9cc-4cb0-8b9c-bc13d134294c
Please take a look and review it!
Thank you.
=> Add Client Side User and Email Validation to Login/Register Page 

assets/css/style.css
Hey @ayush-that , @deepeshmlgupta and @Agarwalvidu issue closes #566 
I have fixed the position of scrolltop button in the body
=> Fixed the Position of ScrollTop Button in the Body 

about.html, assets/css/about.css
Fixes #537 
**NOW**
@Agarwalvidu Please review my PR!
=> About Page Updated

quiz.html
This tells the user about the no. of questions and marks per question in the quiz.
=> #532 issue resolved:-quiz description box added. 

about.html, assets/css/about.css
**NOW**
@Agarwalvidu Please review my PR!
Fixes #579
=> About Content Updation

blog.html, index.html
**NOW**
@Agarwalvidu Please review my PR!
Fixes #570
=> Blog Page Fixed

tools/sip.html, tools/sipcalculatorCss.css, tools/sipcalculatorJs.js
Fixes #513 
Added a know more button to improve the UI and reduce the amount of text.
=> Improved the UI of NPV calc text and changed the input settings of MFI calc

assets/css/contributors.css, contributors.html
Hey @Agarwalvidu and @deepeshmlgupta  
- issue fixes #550 
I have made the changes on the Contributors page:
- Added `Navbar` same as home page
- Added `Favicon`
- Added `Header Design` (To maintain consistency across all websites)
- Added `Footer`
- Changed page to match the website `design theme`
- Added missing `footer-links`
- Added `Particles` and `Preloader`
- Added `Responsiveness` to the website
- Added `Scroll-to-top` button (Which was absent earlier)
- Added Favicon
- Added Navbar
- Added Header Design
- Enhanced Contributors page
- Added Footer
- Added Scroll to top button 
- Page is Complete Responsive
https://github.com/user-attachments/assets/124456fc-10d5-4c33-acb1-d25b6c0e5d22
=> Added Our Contributors Page Changes: "Enhance UI" Added "Navbar and Footer", Match "Website to Design Theme"

about.html, assets/css/style.css, blog.html, index.html, quiz.html, tools/sip.html, trends.html
Issue #244 solved
Added the Login/Register Button in moblie screen of all the pages and made it responsive.
Added the about us page link in the navbar of the trends, blog and quiz pages.
=> Added Login/Register Button in moblie screen

Licensing.html, about.html, blog.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, index.html, quiz.html, tools/sip.html, trends.html
Hey @ayush-that, @deepeshmlgupta and @Agarwalvidu  issue closes #564 
On the website, I have added Navbar and Footer links on some pages  
- I have added the About Us page on Trends page, Tools page, Blogs page, Quiz page in the navbar and also added in the footer section.
- I added some links to the footer section that were missing on some pages
=> Added Navbar and Footer Links in Some Pages

assets/css/style.css, index.html
Fixes: #600 
Nov, when hovering over the Contact section, the color do change.
@Agarwalvidu @deepeshmlgupta please kindly check
=> Added hover color

assets/css/style.css
In the home blog section, I added hover and border effects to the cards to improve the user interface and experience.
Before:
After:
@ayush-that  and @Agarwalvidu , please check the changes and merge the changes to the project .
Thank you
=> Title:- Added hovering and border effects to the Blogs

assets/css/style.css, index.html
all the buttons text is initially of grey colour that is not clearly visible corrected
=> All the buttons text is initially of grey colour that is not clearly visible corrected

index.html
This PR addresses the issue of extra space in the footer. The following changes were made:
- Removed unnecessary margin/padding in the footer section.
- Updated the relevant CSS/HTML to ensure the footer aligns correctly.
Before:
After:
=> Removed Extra Space in Footer

Licensing.html
Hey @ayush-that, @deepeshmlgupta and @Agarwalvidu 
- issue closes #620 
I have added the trail effect to the licensing page
https://github.com/user-attachments/assets/729ca76c-e9ea-475e-97b8-902656876231
Please take a look and review it
=> Added The Trail Effect in Licensing Page

contributors.html
Added the About us Section in the contributors page so please review it and merge it under GSSOC'24
=> Added About Us section

about.html, contributors.html
The Contact Section links are now in the contributors page and the About us page
Close #640
=> Added link the contact section

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html
Made the link clickable in the footer  of the contact section
close #641
=> Update the link in Footer

tools/sipcalculatorCss.css
Hey @deepeshmlgupta and @Agarwalvidu 
- Issues closes  #582 
I have made the Tools page and its sip calculators responsive
- I have Ensured consistent formatting and removed unnecessary comments.
- Made some `Flexbox` Adjustments
- Adjusted button `widths` and `font-sizes` in `media` queries to make them fit better on smaller screens.
- Reduced margins for smaller screens to make better use of available space.
- Removed excessive `padding` where necessary to ensure elements fit well within different screen sizes.
https://github.com/user-attachments/assets/2a49676d-8b90-4bb7-b4da-6cceaae4b194
Please take a look and review it, thank you![
=> Made the "Sip calculators responsive" on Tools Page

Licensing.html, blog.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html, index.html, quiz.html, tools/sip.html, tools/sip_PPF_cAL.html, trends.html
Hey @deepeshmlgupta and @Agarwalvidu 
- issue closes #647 
The Trail Effect Hide in The Mobile View
https://github.com/user-attachments/assets/91e2c100-2169-48b8-b508-aca5ae0e09a5
=> The Trail Effect Hide in The Mobile View

about.html
Added the Tail Effect in the about Us page which make it and enhanced UI
#643
=> The Trail Effect in About Us page

assets/css/style.css
Hey @deepeshmlgupta  , @Agarwalvidu 
issue closes #415 
I have added the Smooth hovering effects for all the links in the footer section.
**Here's the Before :** 
https://github.com/user-attachments/assets/22b300ff-081c-4b91-bd75-835d415e721e
**Here's the Implementation :**
https://github.com/user-attachments/assets/14e36b36-4622-479e-9d9f-a46871328123
Please take a look and review it..
=> ✔️Added  Interactive Smooth "Hover Effects" to The Links in Footer

blog.html, index.html, quiz.html, trends.html
This pull request includes the following updates:
1.Clickable Links in Contact Section:
Added clickable links to the contact section in the footer of the quiz page. Now, email addresses, website URLs, and location addresses are clickable and direct users to the respective pages or applications.
2.Footer Corrections:
Corrected link alignments and made necessary adjustments to the footer on other pages for better consistency and visual appeal.
3.HTML Title Correction:
Updated the HTML title of the quiz page to better reflect the content of the page.
https://github.com/user-attachments/assets/5dbd7d2c-1950-470f-b5cd-a1dbdd7d9834
=> Add links in footer of quiz page and minor improvements

about.html, blog.html, index.html, quiz.html, tools/sip.html, trends.html
@Agarwalvidu Please merge this pr.
=> Eliminated double chat button #631

tools/cal.css, tools/insuranceCalculator.js, tools/sip.html
fixes #588
The results of the Insurance calculator are responsive now.
=> Made Insurance Calculator Responsive.

blogs/privacy-policy.html, blogs/refund-policy.html, blogs/starup.html, blogs/terms-of-service.html, contributors.html
Hey @deepeshmlgupta and @Agarwalvidu 
- Issue fixes #583 
i have Added Login/Register form in Footer Links Pages 
1. Privacy Policy
2. Terms and conditions
3. Refund Policy
4. Licensing
5. Our Contributors
please take a look and review it, thank you!
=> Added Login/Register form in Footer Links Pages 

index.html, login.html
Hey @deepeshmlgupta and @Agarwalvidu 
- Issue fixes #646 
I  have Added Dynamic Copyright Year Functionality to Footer
Please take a look and review it, Thank you!
=> Added Dynamic Copyright Year Functionality to Footer

blogs/Pocketmoney.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/senior.html, blogs/starup.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
@deepeshmlgupta and @Agarwalvidu 
I have update the outdated web components in the blogs related pages and ensure that they align with the website design theme and maintain consistency across all the pages
- Issue fixes #648 
https://github.com/user-attachments/assets/e9596550-56e2-433a-976a-bf08883f68f7
Please take a look and review it, thank you!
=> Updated Outdated Blogs Posts 

Licensing.html, about.html, blog.html, blogs/Pocketmoney.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/senior.html, blogs/starup.html, blogs/terms-of-service.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html, contributors.html, index.html, login.html, quiz.html, trends.html
Fixes #660 
Added **About Us 📖** In all pages.
=> Added About Us Icon

blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html
Fixes #152 
Enhanced the UI for all three pages, Improving the readability and matching the aesthetics of the website.
=> UI enhanced for Privacy Policy, Refund Policy and Terms of Service.

assets/js/quiz_modify.js
Fixing issue #674
Quiz image is removed when quiz is attempted again.
=> Quiz image

assets/css/style.css, assets/js/blogposts.js, blog.html, index.html
Made all cards uniform by adding some js in the title
Added proper responsivity and styles  
Properly indented the html files blog section
Issue #673
=> Blog cards

about.html, blog.html
There were extra padding in footer section of blog and about pages also there was a visibility problem for contact and incorrect alignment of Contacts.
Fixed all the bugs and errors.
This PR is linked with https://github.com/ayush-that/FinVeda/issues/265
Please merge this PR
Regards
Satyam
=> Blog and About pages extra padding and text visibility Fixed

assets/css/quiz.css, assets/css/style.css, assets/js/quiz.js, assets/js/quiz_modify.js, quiz.html
Added submit and pass buttons
Added animation to the play again button
Selected option must be submitted to see whether its correct or not Added text telling the marks obtained in the particular question after its submission
Issue #623
=> Quiz updates

index.html
Fixes #689 
I have added script of counter in this single-counter.
https://www.loom.com/share/b30e52a3a170439f877b8ddd6ae5820b
=> Added Counter code and make it working

assets/css/quiz.css, assets/js/quiz_modify.js, quiz.html
issue #623 
Added a progress bar for the quiz
=> Quiz progress bar

index.html, navbar.css, navbar.js
Resolves #670 
Width of the side-nav : 70% of the device screen width (70vw)
Height of the side-nav : 100% of the device screen height (100vh)
=> Changed Hamburger menu

blog.html, blogs/Pocketmoney.html, blogs/economic-trends-and-analysis.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/senior.html, blogs/starup.html, blogs/terms-of-service.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Fixed All Single Blog's Login Style Like Index.html .
=> Fix All Blog Page's Login Style

assets/css/style.css, index.html
=> Corrected typo and mis-alignment

Licensing.html
Fixes #707 
Fixed Login/Registration on the Licensing Page.
Before:
After:
=> Fixed Login/Registration on the licensing Page.

trends.html
Fixes #719 
Fixed Login/Register UI on Trends Page.
Before:
After:
=> Fixed Login/Register UI on Trends Page

about.html, blog.html, quiz.html, tools/sip.html, trends.html
Resolves #711 
I added hamburger menu for mobile devices for the following pages:
- About page(./about,html)
- Trends page(./trends,html)
- Tools page(./tools/sip,html)
- Blog page(./blog,html)
- Quiz page(./quiz,html)
In the same manner the navbar was in the Home page(index.html)
=> Added hamburger to all pages

index.html
Fixes #723
Fixed registration feature for new users on homepage.
Before:
After:
=> Fixed registration feature on homepage.

about.html, assets/css/style.css, blog.html, index.html, navbar.css, quiz.html, tools/sip.html, trends.html
Issue #710 
Added the Login/Register button in the navbar in mobile view for all the pages.
=> Added login/register button in mobile view

blogs/Pocketmoney.html, blogs/economic-trends-and-analysis.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/senior.html, blogs/starup.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Hey @ayush-that 
- issue closes #691 
I have added the scroll down progress bar in blog posts
https://github.com/user-attachments/assets/63a9225c-bc50-4854-bfb1-f2d5ca72c0d1
=> Added Scroll Down Progress Bar in all missing pages

assets/css/quiz.css, quiz.html
=>  Modified Welcome to the Quiz Challenge! container in Mobile view

tools/ProfitMargin.js, tools/sip.html
Fixes #731 
Added Profit Margin Calculator.
=> Added Profit Margin Claculator

assets/css/style.css, blog.html, index.html
Fixes #756
Style of Newslatter and Footer Fixed.
One Blog Is present in Blog section but not in index.html that i have added.
=> Fix Footer/Newslatter Style Fix Blogs

tools/expenditureandsaving.js, tools/sip.html
=> added expenditure and saving tool

navbar.css
closes #762 
Fixed Navbar content horizontally in Mobile view
Before
After
=> Fixed Navbar in Mobile view Horizontally

assets/js/arthsathi-style.js, index.html
Fixed the sizing for mobile screen
=> Fixed chatbot sizing for mobile screen

tools/sip.html, tools/sipcalculatorCss.css
=> Fixed NPV content in mobile view

tools/sip.html, tools/sipcalculatorCss.css
=> Fixed tool page container in mobile view

assets/css/quiz.css, assets/css/style.css, index.html
=> Added Feedback form

assets/css/contributors.css, contributors.html
Hey @deepeshmlgupta , @Agarwalvidu 
issue closes #740 
- I have **added the Diagonal Effect on Hovering** on each contributors card
- Also **Added Transitional Text Shadows to the `Contributors-name` and `Github-Contributions` info**
- **Followed the website theme for it.**
**please take a look -**
https://github.com/user-attachments/assets/b70c3c22-fc3f-4397-854f-53a413bf4d60
Please review it. thankyou!
=> ✔️Added Diagonal-Hovering Effect to Each Card!

index.html
Resolves #726 
Working Video:
https://github.com/user-attachments/assets/8f990503-0e65-4b60-a8ef-860da37ec01b
=> Made separate BG color for both halfs

assets/css/style.css, index.html
Closes #795  
I accidentally deleted the script for views and comments, so i added it back also
=> Fixed Feedback form in mobile view

assets/css/about.css
Closes #799 
https://github.com/user-attachments/assets/c7f11290-fe18-4959-9960-7ef2da9a4c90
=> Fixed About us Page in Mobile view

index.html
Added fade in effect to feedback container and elements inside it
Issue #788
=> Issue #788

assets/css/quiz.css, quiz.html
Issue #787 
The command "input:hover" on quiz.html was interfereing with the feedback form on main page
Added name for body in quiz page and edited css to prevent overwriting across pages
=> Issue #787 

assets/css/style.css, index.html
Issue #798
Fixed input field of subscribe email and made it required
=> Subscribe button

assets/css/style.css, index.html
Issue #786 
Added a timed popup which appears after submission of the feedback form.
=> Feedback form submission

Finveda/Finveda/src/components/footer.jsx, assets/css/style.css
Hey @deepeshmlgupta @Agarwalvidu 
issue closes #768
I have Fixed the Footer Section Alignment. 
- Adjusted the alignment of the links in the footer to ensure they are in a single line.
- Optimized the layout to make better use of the available space in the footer section.
please take a look - 
**BEFORE :**
**AFTER :**
Please review it.
Thankyou!
=> ✔️Fixed Footer Section Alignment 

index.html
Preventing feedback submission when fields are empty
Issue #786
=> Feedback submit

Licensing.html, about.html, assets/js/subscribe.js, blog.html, blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/economic-trends-and-analysis.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/terms-of-service.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html, contributors.html, index.html, login.html, quiz.html, tools/sip.html, trends.html
Added popup notifs for subscription as well as open modal behavior for all pages! 
Made a new file for the subscribe button js behavior
Issue #797
=> Submit behaviour for subscribe

assets/css/style.css
=> Fixed Footer In mobile view

quiz.html
=> Quiz fade in

tools/sip.html, tools/sipcalculatorCss.css, tools/sipcalculatorJs.js
Made sure that all the "Calculate" buttons have the same styles
Issue #835
=> Tools buttons

tools/gdp.js, tools/sip.html
=> added GDP calculator

index.html
After feedback form submit not reset 
Fixes #820
https://www.loom.com/share/d72c6833c3ca41d5a54d5f91f563fbcc
=> Fix Reset Feedback form

Licensing.html, about.html, assets/css/style.css, blog.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html, index.html, quiz.html, tools/sip.html, trends.html
Hey @Agarwalvidu 
- Issue closes #682
I have Added "Reset Functionality" and "Thank You for the subscription" pop messages after Clicking the Subscribe Button Across all the existing pages of the website to ensure consistency!
- Added `Client-side user validation` message
- Added `Email Validation`
- Added `Reset Functionality` 
- Added `Thank you a pop-up message` with a gradually decreasing timer broder
- The message hides after `3s`
- Implemented the functionality across all pages
https://github.com/user-attachments/assets/e369a221-fdfa-4a67-b494-149b6a3c261e
Please take a look and review it, thank you!
=> Added "Reset Functionality" and "Thank You for the subscription" Pop Up Message After Clicking Subscribe Button

tools/sip.html
=> Adding content to know more fields

about.html
Solved #838 
Removed the cursor trail effect on the 'About Us' page in mobile view, like on other pages.
=> Removed Cursor Trail Effect on 'About Us' Page in Mobile View

about.html, assets/css/style.css, blog.html, index.html, quiz.html, tools/sip.html, trends.html
Issue #858 solved
Fixed the footer alignment and made it responsive.|
=> Fixed Footer Alignment

assets/css/faq.css, assets/js/faq.js, index.html
Issue #832 
Added FAQ section with accordion type styling
=> Adding FAQ page

assets/css/cookiepopup.css, index.html
Hey @deepeshmlgupta @Agarwalvidu 
issue closes #863 
I **have implemented a "cookie consent popup"** for  FinVeda. 
- This popup **will inform users about the use of cookies and ask for their consent.** 
- The popup will appear **when the user first visits the website and refreshes it** and will include :
-  a brief **message link to the privacy policy,** 
- **an "Accept" button.**
- The Popup will is on the "Left-Bottom" Corner of the Website, which will not affect the user experience
Please take a look - 
https://github.com/user-attachments/assets/fd44ef6f-cb6e-4b74-8154-172c9b12bf8f
Thankyou!
=> ✔️Implemented "Cookie Consent Popup"

README.md
-> Added external guidance for newcomers 
-> This will help them save time and get them to start working on the issues at the earliest
=> minor updates in readme.md

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html
Hey @deepeshmlgupta @Agarwalvidu 
issue closes #851 
I have implemented **a dynamic "Last Updated" date feature** for the legal pages on the website, including the Terms and Conditions and Privacy Policy pages.
The **date format** is set to **"Month Day, Year"** and will update dynamically to reflect the current date. 
**Additionally, "each page has a specific update frequency" to ensure the date remains accurate.**
**Changes Made :** 
- Added a script to dynamically update the "Last Updated" date for the Terms and Conditions, Privacy Policy, and Licensing pages.
- The **date format** is **"Month Day, Year" for a professional appearance.**
**Here -**
**Terms and conditions**
**Privacy policy :**
**Refund Policy :**
**Licensing :**
=> 🗓️ Implemented Dynamic "Last Updated" Functionality to All Legal Pages !

index.html
=> Added Faqs

assets/css/bootstrap.min.css
Fidded invisible lable issue in login/register page
Fixes: #878
=> fixed login label issue

tools/SWPCalculator.js, tools/sip.html, tools/sipcalculatorCss.css
Issue Fixed:
Fixes #822 
Description:
Added SWP Calculator.
Screenshot:
https://github.com/user-attachments/assets/bccf81c0-24cb-47bd-83ad-3408f722b1d2
=> Added SWP Calculator

blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/economic-trends-and-analysis.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/real-estate-economics.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Issue #867 solved
Added Icons in 'Contact Us' Section in Footer of Blogs
=> Added Icons in 'Contact Us' Section in Footer of Blogs

tools/creditcardpayoff.js, tools/sip.html
=> added credit  card payoff calculator

assets/css/cookiepopup.css, assets/css/style.css, index.html
Fixes #882
Visibility of cookie model in small screens and give margin left in footers content in small screen.
=> Cookie small screen visibility fix and margin left in footer

assets/css/style.css, tools/GSTcalc.js, tools/IncomeTax.js, tools/ProfitMargin.js, tools/SWPCalculator.js, tools/SavingsGoalCalculator.js, tools/creditcardpayoff.js, tools/emiCalculator.js, tools/expenditureandsaving.js, tools/insuranceCalculator.js, tools/npvCalculator.js, tools/roiCalculator.js, tools/sip.html, tools/sipcalculatorJs.js
=> added functional clear button on every calculator

blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/economic-trends-and-analysis.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/real-estate-economics.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Issue #900 solved
Added the new hamburger navbar in mobile view in the blogs.
=> Added Hamburger Navbar in Mobile View in Blogs

.github/workflows/auto-comment-pr-merge.yml
Fixes #184 
Autocommenting feature added after a pull request is merged.
Please merge this pull request and add the necessary labels as per gssoc guidelines.
=> Created auto-comment-pr-merge.yml

.github/ISSUE_TEMPLATE/documentation.yml
Fixes #185 
Added issue template for documentation issues
Please merge this pull request and add the necessary labels for gssoc.
=> Added issue template for documentation issues

index.html, navbar.css
#916
I made the Register button in the side nav-bar work same as the main nav-bar
https://github.com/user-attachments/assets/f0410181-31c0-4a45-b352-3425e56cf020
=> Corrected the Register button

tools/Billsplit.js, tools/sip.html
issue no:- #918 
ADDED WORKING FUNCTIONAL BILL SPLIT CALCULtor
=> added bill split calculator

blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/economic-trends-and-analysis.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/real-estate-economics.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Issue #901 solved
Removed the cursor trail effect in mobile view in all of the blogs.
[removedTrailEffectBlogs.webm](https://github.com/user-attachments/assets/485cd6f9-1f23-4bd5-a935-8a7ac010a765)
=> Removed Cursor Trail Effect in Mobile View in Blogs

assets/css/style.css
fixes:  #905 
Fixed Card hover bug present in landing page
resolved card hover bug
=> Feat: Resolved Card Hover bug in Landing Page

assets/css/style.css, index.html
fixed @734
Alignment of read more button
Before: 
after
=> Alignment of read more Buttons

Licensing.html, blog.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html, quiz.html, tools/sip.html, trends.html
Issue #912 solved
Updated the new favicon in all the pages.
=> Consistent Favicon Across All Pages

Licensing.html, about.html, blog.html, contributors.html, login.html, quiz.html, tools/sip.html, trends.html
Fixes #921
In other page's footer not have social icons like in home page.
=> Added Footer's social icons

tools/FDCalculator.js, tools/sip.html
Fixes #893
Added FD Calculator.
https://github.com/user-attachments/assets/32bc6270-c616-4b60-b260-d6889b2b015c
=> Added FD Calculator

.github/auto-comment-on-issue.yml, .github/workflows/greetings.yaml
Fixes #186 
Feature for auto commenting on a new issue creation added.
Please merge this pull request and add the necessary labels for gssoc.
=> Feature for auto commenting on a new issue creation

tools/RDCalculator.js, tools/sip.html
Fixes #894
Added RD Calculator.
https://github.com/user-attachments/assets/fa6c0d14-8bcd-4b13-86e6-ae97dd43ec6d
=> Added RD Calculator

tools/EPFCalculator.js, tools/sip.html
Fixes #895 
Added EPF Calculator.
https://github.com/user-attachments/assets/0a4aa287-6aa4-4469-8dcb-5b982ae52007
=> Added EPF Calculator

tools/creditcardpayoff.js
issue no :- #940 
it working perfectly 
video⤵️
https://github.com/user-attachments/assets/80a2ed5e-a0d6-4a31-8ad2-87a6130d2bb5
=> fixed credit card calculator 

index.html, navbar.css
Hello Project Admin
I Alligned Navbar icons - Solved #860
Kindly please go through this PR @Agarwalvidu
=> Alligned Navbar

index.html, navbar.css
Reverts ayush-that/FinVeda#948
=> Revert "Alligned Navbar"

assets/css/faq.css, index.html
issue #832 
Added fadein in the faq section and improved the responsivity
=> Update: faq section

tools/Billsplit.js, tools/GSTcalc.js, tools/SWPCalculator.js, tools/cal.css, tools/creditcardpayoff.js, tools/gdp.js, tools/insuranceCalculator.js, tools/sip.html
Fixes #961
Fixed Split Bill Calculator and Credit Card Payoff Calculator, also made all calculator clear button in a row, fixed swp, Insurance, GDP Calculator also.
=> Fixed Bugs in Calculators

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html
Issue #947 solved
Fixed the Login/Register modal in the 'Privacy Policy', 'Refund Policy', 'Licencing', 'Terms of Service' and 'Our Contributors' Page. 
[showPassword.webm](https://github.com/user-attachments/assets/34ebb8f9-ce4b-452a-bb9b-109b18fa1339)
=> Fixed Login/Register Modal

index.html
=> added icons to login signup

tools/sip.html
=> added icons inside input text

about.html, assets/css/style.css, assets/js/botpress.js, blog.html, index.html, quiz.html, tools/sip.html, trends.html
I have enhanced the conversation flow of the chatbot to ensure it does not greet users repeatedly after each query. This improvement allows the bot to maintain context and provide relevant responses, creating a more natural and engaging experience.
Additionally, I implemented a reset button, enabling users to easily restart the conversation at any time. This feature gives them greater control and improves the overall user experience.
Before:
[before.webm](https://github.com/user-attachments/assets/a128d9ac-0444-4b41-b26d-8d7880c2139a)
After:
[after.webm](https://github.com/user-attachments/assets/72d43f9d-beee-4541-a76f-ca9e602a25a0)
=> Chatbot Fails to Maintain Conversation Flow (#980)

about.html, assets/css/style.css, assets/js/botpress.js, blog.html, index.html, quiz.html, tools/sip.html, trends.html
Reverts ayush-that/FinVeda#982
=> Revert "Chatbot Fails to Maintain Conversation Flow (#980)"

CONTRIBUTING.md, LICENSE
=> its was so longb so need to change

about.html
#828 
None
The alignment of footer section in about page is done and added few hover effects as well.
=> Alignment issue of footer section( In About Us page)

index.html, navbar.css, navbar.js
This pull request adds styling improvements to the footer section and navbar updating the padding, and applying a consistent black background with rounded corners and subtle shadows to enhance the overall UI/UX. These changes help reduce excess space and improve the layout's visual appeal.
https://github.com/user-attachments/assets/f94c8e3d-cdd8-4130-a3d7-16b192ab376f
These changes were made to ensure the page's visual hierarchy and reduce the excessive vertical spacing in smaller screen sizes, providing a better user experience for responsive designs.
@ayush-that Please review the code and merge it under gssoc-ext'24 and hacktoberfest labels.
=> Enhanced the navbar and footer section of the website 

index.html
=> solved issue #970

Finveda/google585d479acf355cc6 (1).html, about.html, blog.html, careers.html, contact.html, google585d479acf355cc6 (1).html, google585d479acf355cc6.html, index.html, login.html, quiz.html, tools/sip.html, trends.html
No career guidance in finance and no contact us page
=> created contact us careers page is added

index.html
#1031
improved the navbar UI. align the options icons along with options.
=> solved issue #1031

assets/css/bootstrap.min.css, assets/css/popup.css, assets/css/register.css, index.html, login.html
Issue: #1019 
The register page is added and it's UI is modified
The register page is added now new people can be able to register themselves.
=> Register Page is Added

assets/css/popup.css, assets/css/style.css
Before
https://github.com/user-attachments/assets/8216ea9a-da08-426a-aa06-3a39f6cfe110
After
https://github.com/user-attachments/assets/9db69e84-2885-45c1-a611-ff4249c719bc
=> Hovering effect added on chat with ArthaSathi and width of the button reduced

assets/css/style.css
Issue #1014 fixed
I have resolved the issue where the eye icon was appearing outside the password field in both the login and sign-up sections. The icon is now correctly aligned within the password input field, ensuring a clean and professional look.
https://github.com/user-attachments/assets/5a02d365-6c62-49d5-a8cc-8c1928d39ddd
NA
=> Fixed Eye Icon Alignment in Login and Sign-Up Password Fields

assets/css/contributors.css, assets/css/style.css, index.html, navbar.css
- Fixes #1045 
- Nav bar position fixed.
- Nav bar styling fixed. [ Responsiveness Added ]
- Nav bar hover effect fixed [ refer the before video ]
https://github.com/user-attachments/assets/9cdc0deb-83d8-408c-8ac9-1d4969b9ada9
https://github.com/user-attachments/assets/b8712fd8-8c49-48e9-a099-cdc5f94c4461
Please label this PR as level2 or level3 as so many additional changes have been made. It's a small request.
=> [FIX] Nav bar Position, Styling and Hover effect fixed

index.html
#1028 
I have added a responsive password strength level meter in registration page which enhances user experience.
Before
After
=> Added responsive password strength level meter

index.html
Pr No: #1029 issue 
Pr Name:Add social icon link in the footer section
Added social media links in the footer section and also add hover effect to it
Before:
After:
here's are hover effect video:
Before:
https://github.com/user-attachments/assets/982daa57-4874-48dd-837a-f7d0c1b61cea
After:
https://github.com/user-attachments/assets/821ae183-b55c-4dfb-9d2d-7b6b7718fcf4
=> updated footer and add hover effect

index.html
None
I've added a line of statement in the sachin's card so that it is aligned to all other remaining cards
- [ X] Bug fix
- [X ] I have read and followed the Contribution Guidelines.
=>  Alignment issue of cards in the user sharing section in home page

index.html
fixed #1012 
Added the social media icons and enhanced the icon styles also in the footer
@ayush-848 Check this PR and merge it and assign this to me and put relevant labels like gssoc 2024 ext, hacktoberfest and level.
=> Added the social media icons and enhanced the icon styles also in the footer #1047

assets/css/index.css, index.html
issue #1043 fixed
This update introduces Google, Facebook, and Twitter icons to the login and sign-up pages, allowing users to easily sign in or register through their social media accounts. Additionally, a 'Forgot Password' button has been included to help users quickly recover their accounts. These changes improve the functionality and accessibility of the login and sign-up process, providing a smoother and more flexible user experience.
https://github.com/user-attachments/assets/0e117558-f41b-46e4-8ec1-bfbcde2fba6a
=> Add social media icons to login and sign-up pages

faq.html, index.html
I have added a button (help) when we click on it ,faq section open up ,as required ,faq added in   a new page and remove it from the index page
- [ done] Bug fix
- [  done ] Feature enhancement
- [ .] I have performed a self-review of my code
- [ .] I have read and followed the Contribution Guidelines.
- [ .] I have tested the changes thoroughly before submitting this pull request.
- [ .] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ .
] I have commented my code, particularly in hard-to-understand areas.
[Include any …
=> [style]: FAQ Section #969

assets/css/card.css, contact.html, index.html, navbar.css
=> added a contact form to contact page

assets/css/about(inlines).css, assets/css/about.css, assets/css/blog.css, assets/css/login.css, assets/css/quiz.css, assets/css/trends.css, index.html, navbar.css
Made the  changes in css properties #1034 
Made the changes in font size, transition, colour , and other changes in the css file as well as html file 
- [ no] Bug fix
- [ yes] Feature enhancement
- [ no] Documentation update
- [yes ] Other (specify): _____Necessary changes__________
- [yes ] I have performed a self-review of my code
- [ yes] I have read and followed the Contribution Guidelines.
- [yes ] I have tested the changes thoroughly before submitting this pull request.
- [ no] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ no] I have commented my code, particularly in hard-to-understand areas.
Thank you for giving chance.
Please review and label me
=> I had made css changes whenever required

index.html
fixed the header and aligned all tabs
=> fixed the header and aligned all tab

README.md
#990  Related Issue
Updated Readme with Changes
=> Update contributing guideline in Readme.md

about.html
fixed navbar of about us section
=> Fixed Navbar of about us page #1092

assets/css/slick.css, index.html
Issue #1097
Custom Button Functionality for Testimonial Slider
1. Implemented Button Functionality: Added JavaScript code to enable the custom navigation buttons (prevButton and nextButton) for the testimonial slider.
2. Slick Slider Integration: Leveraged the Slick slider's API to allow users to navigate between slides using the custom buttons without modifying the core Slick library.
3. Event Binding: Used jQuery's .click() method to bind the button click events to their respective slider actions (previous and next).
https://github.com/user-attachments/assets/d81559af-e906-41da-aab7-926f59861844
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ …
=> [Fix] : Carousel button fix

assets/css/style.css
- Fixes #1042 
Blog section scroll and link fix
=> blog link and scroll fix

contact.html
Issue #1104 Solved
1) Added the missing form submit script to handle the form submission correctly.
2) Added a toast notification which will appear on successful submission of the form . 
https://github.com/user-attachments/assets/53132217-fe90-4bbd-8a45-0a2c728c37f0
https://github.com/user-attachments/assets/9a051805-33a9-46ab-90ff-376d73fb3090
=> [ISSUE #1104]On submitting issue solve in contact form

blog.html, careers.html
fixed navbar of both Blog and careers page 
@Sampadatiwari please review it
=> Fixed Navbar of Blog and Careers page #1096

assets/css/style.css
Subscribe form background color changed and hovering effect added over subscribe button.
Before
https://github.com/user-attachments/assets/5f2c07b7-186c-4a54-b117-35ce8c749269
After
https://github.com/user-attachments/assets/c0f03a67-3001-4295-9cc1-ed61f513c6fe
=> Subscribe form enhanced

ContactUs.html, assets/css/ContactUs.css, index.html
The contact page is added and a video of the page is attached below.
https://github.com/user-attachments/assets/7316147b-3c92-43ac-968e-bea39077e61c
=> Added contact page: Issue no. #1018

index.html
the code has been updated.and the conflicts are removed from PR#1094
=> issue #999 solved.

ContactUs.html, Licensing.html, about.html, blog.html, careers.html, contact.html, contributors.html, footer.html, login.html, quiz.html, tools/sip.html, trends.html
Closes #1091 
Added social media links to all the pages in the footer section
=> Adding social media links in the footer to all the pages

assets/js/quiz_modify.js
The quiz section now generates a random selection of 10 questions from a larger question bank every time a user begins the quiz
The feature ensures that the quiz remains challenging and educational
=> Fixed issue #1024

faq.html, login.html
Add chatbot to the login and faq pages.
Before:
After:
=> Add chatbot

contact.html
issue #1113 
This pull request introduces a new contact page design featuring a clean layout with a contact form for users to send messages. The page also includes an info section with essential contact details, such as email, website, and LinkedIn links. A responsive map is integrated to help visitors locate the business address. The design is optimized for accessibility and responsiveness across various devices. This update aims to enhance user experience and provide a seamless way for visitors to get in touch.
Before :
https://github.com/user-attachments/assets/f27caeae-d106-4bbe-88a3-b29168f3c590
After :
https://github.com/user-attachments/assets/4a0f7ca1-edf9-453a-8726-1bf7d223fbb2
=> contact page with map 

about.html, assets/css/bootstrap.min.css, assets/css/style.css, blog.html, login.html
Hello PR,
Fixed issue number - #1124
Issue Fixed -
[The eye button in both Login & Register page is not aligned properly, but now i properly fixed these issue]
=> Fixed misalignment of eye button issue in both Login & Register page ! #1124

index.html
hey @ayush-that I have resolved the issue under #1132 
I have changed the position of the social icons and updated the styling of the quick links
Before
After
=> Issue #1132 resolved 

assets/css/index.css, index.html
@ayush-that 
@Sampadatiwari 
I have added scroll progress bar successfully
https://github.com/user-attachments/assets/661af58d-9577-4b4b-b4b6-7b26bd11e8cb
=> added scroll progress bar

navbar.css
navbar is improportion 
navbar is improportion so i allign the navbar so the login and regester button can be easily visible
issue no: #1179
=> navbar fix

index.html
=> Footer column fixed.

assets/js/quiz_modify.js, quiz.html
Closes #1008 
I have updated the quiz mechanism to a better understandability.
This PR enhances the quiz mechanism by improving the scoring system and user feedback. The changes ensure that users receive clearer indications of their performance after each question, and the score reflects a more accurate tally based on correct answers.
The changes made include:
- Scoring system now awards 1 point for correct answers.
-Updated the Total Score to be 10 points.
-Improved messaging for correct and incorrect answers.
-Adjustments to the HTML structure for clearer feedback.
=> Update quiz scoring mechanism and modify quiz HTML#1008

contact.html
issue #1166 completeted
@ayush-that can you please review this , the branch is up to date.
https://github.com/user-attachments/assets/23939655-278c-4631-ac24-36540c335b2f
=> forms improved ✨ issue #1166 

index.html, navbar.css, navbar.js
None
in the navbar on hovering there was a issue reading the contents
issue number- #1120 
- [✔️] Feature enhancement
https://github.com/user-attachments/assets/4dd65ff9-ccbe-4a70-9c37-4d1bdcecec8d
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
[Include any …
=> changes in navbar

assets/css/style.css, index.html
This pull request addresses the issue of misaligned testimonial cards. The alignment of all five testimonials has been corrected to ensure a consistent and professional appearance.
- Adjusted CSS styles for the testimonial cards.
- Ensured all cards maintain a uniform size and alignment across different screen sizes.
- This change improves user experience by providing a cleaner layout.
=> #1125:Align Cards in Testimonials Section

assets/css/style.css
subscribe button fix 
subscribe button fix and now it is placed in center
=> Fix: #1196 subscribe button fix

about.html, assets/css/about.css
None
This update introduces a new Contributor page to the website, which highlights and acknowledges the efforts of those who have contributed to the project. The page aligns with the website’s overall theme, ensuring a seamless and visually appealing experience for users. This feature enhances transparency and encourages community engagement by providing real-time updates about contributions.
https://github.com/user-attachments/assets/b208e959-3a70-4b9f-b3a9-223b46fc1e2f
- 
- [x ] I have performed a self-review of my code
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my …
=> Fix #1151 Adding contribution Page

index.html
Make footer of Home page same as other pages for better user experience
=> Fixed issue #1238 - Update UI of footer in homepage

faq.html
added back to home button in faq page 
@Sampadatiwari please merge it
=> fixed issue -#1237 - added back to home button 

assets/css/index.css, assets/css/style.css, index.html, navbar.css
#1235 
The background colo of nav bar and login button changed and the hovering effects are also changed
Before
https://github.com/user-attachments/assets/0854190f-46e2-40ce-abb4-8f49e4a72917
After
https://github.com/user-attachments/assets/8589ae0f-66b4-4bbd-8745-40c06d3f3c0d
@Sampadatiwari Check my PR and add the level2 tag while merging
=> Nav bar hover effect enhanced

contact.html
Hello PR,
Fixed issue number - #1122 
Issue Fixed -
=> Fixed text alignment & text box size issue ! #1122

assets/css/style.css
#1243 
Cards Designs changed and hovering effects enhanced
Before
After
https://github.com/user-attachments/assets/8cfced0d-1a3a-4504-847a-a9677c1eeec3
@Sampadatiwari Please review my PR and assign level2 tag.
=> Blog cards design enhanced

contact.html
**Summary of Changes:**
- Hover Effects Added: Enhanced the visual appearance of the contact form and map section by implementing hover effects for better user interaction.
- Info Frame: Added background color change and scale effect on hover.
- Map Frame: Incorporated a scale effect on hover to make it visually responsive.
- **Corrected Duplicacy**: Identified and corrected duplicacy in the form elements to ensure the contact section is streamlined and free of repetition.
**Details of Changes:**
- Added IDs to the info-frame and map-frame elements for more precise CSS targeting.
- Updated CSS styles to include transitions and hover effects specifically for the new IDs.
These changes aim to improve user experience on the contact page, providing clearer visual cues during interactions. …
=> Refactor Contact Section

contact.html
#1247  
Extra name and email section removed
=> Extra name and email section removed #1247

contact.html, tools/sip.html
#1248 
Tool page UI/ux enhancement
https://github.com/user-attachments/assets/1cda8bd6-e609-454a-b5d8-629da90b8d80
=> Tool page UI/ux enhancement #1248

tools/sip.html
fixed the nav bar of tool , now all links are working and alignment is correct
@Sampadatiwari @deepeshmlgupta please review and merge it
=> fixed issue #1266 - fixedd navbar of tools page

about.html, blog.html, careers.html, contact.html, index.html, navbar.css, quiz.html, tools/sip.html
ISSUE #1156 solved
PR #1215 merge conflicts solved
**Earlier ,When navigating between different pages of the website, the active state of the navbar links is not properly updating. It has been fixed now .**
https://github.com/user-attachments/assets/462acc73-4430-4d1d-bd83-e5d779b06b83
=> Navbar active link added 

index.html, trends.html
#1260 
Courser effect now working properly in trends section
=> Courser effect now working properly in trends section #1260

index.html
#1263 
emoji position corrected
=> emoji position #1263

index.html, navbar.css
#1241 
I have changed the z index of the menu button 
- [ Yes] Bug fix
=> Corrected Menu Button Overlaying on text

index.html
solved #1210 
https://github.com/user-attachments/assets/011583df-865a-4257-929c-82118e53f95a
#1210 
=> added language translator

about.html, blog.html, contact.html, index.html, quiz.html, trends.html
Hello, PR
Fixed issue - #1236
Add new feature - Translation Tool
https://github.com/user-attachments/assets/fb8363a0-a114-4bc1-bdd3-3cc962215855
[I add new feature - Translation Tool]
=> Add Translation Tool done ! #1236

about.html, assets/css/about.css, blog.html, contact.html, index.html, tools/sip.html
…niform functionality across all pages.
#1258 Solved
Fixed the issue where the login and sign-up pages were opening differently on the home page compared to other pages. This update ensures that both the login and sign-up pages now have consistent behavior and are properly aligned across all sections of the website. This fix enhances the overall user experience by providing uniform functionality throughout the site.
https://github.com/user-attachments/assets/0a328a21-319b-40a8-88c0-4c9f32fb3e18
NA
=> Inconsistent Behavior of Login and Sign-Up Pages Across Different Pages - Fix

navbar.css
Matched the color of button with site theme
just changed the color code in css file
=> Login/Register button color matched with theme fixed issue #1021

about.html, assets/css/index.css, index.html
#1251 solved
This update fixes the issue where the progress bar (also referred to as the top scroll animation) was not working properly on the Home and About pages. The progress bar is now fully operational across all pages, ensuring a consistent and smooth user experience throughout the site.
- [X ] Documentation update
- [X ] Other (specify): _______________
https://github.com/user-attachments/assets/fdb86fce-c598-4f43-830a-d2d78b2a4862
=> Fix Progress Bar (Top Scroll Animation) on Home and About Pages

about.html
=> Fixed connect with us in footer of about page

about.html, assets/js/main.js, index.html
#1250 
This commit addresses the bug where the cursor trail effect was not visible on the Home page while functioning correctly on other pages. The issue has been fixed, and the effect now consistently appears on the Home page as well. Additionally, I suggest keeping the cursor trail effect only on the Home page to maintain a more professional look across the site.
- [ X] Feature enhancement
- [ X] Documentation update
- [X ] Other (specify): _______________
https://github.com/user-attachments/assets/88354cef-4bd1-4c48-8689-ae69f8cb0151
=> Fix Cursor Trail Effect Not Working on Home Page

about.html
@Sampadatiwari fixed the issue
=> fixed Duplicate Contact us

index.html
#1301
Improve text  visibility on homepage
=> solved issue #1301

assets/css/style.css
Button allinged in center issue #1278
=> Button allinged in center issue #1278

assets/css/style.css
#1275 
Blog posts cards background color changed and hovering effects enhanced
https://github.com/user-attachments/assets/8e924cc6-11bc-4825-8b2c-9d10bb1ede5d
@Sampadatiwari Please review my PR
=> Blog posts cards color and hovering effects enhanced

about.html, contact.html
=> Fix the Title of Contact/your feature

careers.html
=> Update careers title.html

contact.html
issue #1302
Improve submit button functionality on contact us page . Now on clicking submit button an alert stating that your message has been submitted successfully will pop out and text fields will be cleared.
https://github.com/user-attachments/assets/ecd83981-3bfa-47f4-9f78-86ae3e04524f
=> solved issue #1302

assets/css/about(inlines).css, assets/css/about.css, index.html
Close button not working in FAQ  already fixed #1184
=> Close button not working in FAQ  already fixed #1184

assets/css/about(inlines).css, assets/css/about.css, index.html
The Button is large in Tool section and was already fixed 
=> The Button is large in Tool section and was already fixed #1298

contact.html
Fix:#1299 contact information fix
Fix:#1299 contact information fix
=> Fix:#1299 contact information fix

auth.css, auth.html, auth.js, index.html
i add a login page with good designing login/signup page in which i use AUTHENTICATION(VALIDATION) ,authentication means the feature of a backend which help old users to login which help users to start their project from where they quit .i used this feature with the help of "firebase ":- a google tool which helps to deal with the  backend .
- [ x] Feature enhancement
AUTHENTICATION WORKS PROPERLY , AND IF YOU LIKE THIS CONTRIBUTION THEN PLEASE MAEK IT AS "LEVEL3" LABEL BEACUSE I USED CONCEPTS OF BACKEND IN IT 
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos …
=> Title: Authentication in login page #1147

tools/sipcalculatorCss.css
The size of the button fix
The size of the button fix by changing the width of the box
=> Fix: #1298 size of the button fix

assets/css/style.css, index.html
#1319 
Redesigned the entire form from scratch and added hovering effects over it.
https://github.com/user-attachments/assets/cbe84ac8-6567-4184-9c72-e1c7d6d75fb9
@Sampadatiwari Please check my PR and add it to level 2 as i have to design the form from beginning.
=> Feedback form enhanced

assets/css/style.css
None
#1244 Have been done, alignment of Feedback form 
Before:
After: 
=> Alignment of Feedback form

careers.css, careers.html, careers.js, contact.html
created a pull request for issue#1262 
=> Added search bar for jobs functionality for the issue #1262

about.html
#1338 
ABOUT US page footer problem solved
=> ABOUT US page footer problem solved#1338

footer.html
none
added linkedin on footer (footer.html)
NA
=> #1224 footer socials updated 

quiz.html
=> Fixed Login button in Quiz Section

about.html, blog.html, careers.html, contact.html, quiz.html, tools/sip.html
None
Replaced icons of twitter on all pages to X
Issue number- #1311
=> Replaced icons of twitter on all pages to X

assets/css/style.css, index.html
Hey @ayush-848  I have resolve issue with #1356 
None
In home page every heading UI is fixed now that is now heading is visible.
- [🗸] Feature enhancement
- [🗸] I have performed a self-review of my code
- [🗸] I have read and followed the Contribution Guidelines.
- [🗸] I have tested the changes thoroughly before submitting this pull request.
- [🗸] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [🗸] I have commented my code, particularly in hard-to-understand areas.
=> Headings UI change fix issue #1356

about.html, assets/css/style.css, blog.html, careers.html, contact.html, quiz.html
#1276 
The nav bar design is made same for every page.
=> Nav bar style applies in every page

quiz.html
=> Extra button removed

assets/css/style.css, index.html, navbar.css
the navbar now fits in the screen with perfect alignment along with hovering over the elements of navbar.
TITLE'S COLOR CHANGED for 2,3 lines as it was not visible .
=> NAVBAR ALIGNMENT AND TITLE'S COLOR CHANGE

index.html
now heading text will be visible in light mode
=> Fixed Heading texts in Light mode

index.html
#1284 
- added radio buttons for emoji ratings with corresponding labels.
- included a div to display the description of the selected emoji.
- added validation to ensure an emoji rating is selected before submission.
-  added event listeners to update the emoji description when a rating is selected.
- form submission now includes the emoji rating in the feedback object stored in localStorage.
- l reset the entire form after a successful submission, including clearing the selected emoji rating and resetting the emoji description to its default state
https://github.com/user-attachments/assets/00650545-7073-4da3-b007-87bc17f69f0e
=> Added Emoji Rating with Labels, Validation, and Form Reset Functionality

assets/css/style.css
Change in background linear gradient color.
Choose appropriate color for Blog Card so look good and match the theme of website.
- [style]: Change color of blog cards #1275
https://github.com/user-attachments/assets/1ba51871-d5b6-44d7-ab82-c1707509e8ef
=> update in Blog card Background color

tools/sip.html, tools/sipcalculatorJs.js
EMI Calculator "Clear" Button Not Functioning on the Tools Page
This pull request resolves the issue where the "Clear" button on the EMI calculator was not functioning correctly. After clicking the button, it now properly resets all the input fields and clears the calculated values, allowing users to start fresh with new inputs. This update enhances the functionality and usability of the EMI calculator by ensuring it operates as expected.
https://github.com/user-attachments/assets/07cdca70-aca2-4f4c-b0a8-fff03832a0fc
The fix ensures that the "Clear" button fully resets all input fields and calculations. This functionality has been tested across different browsers for consistency.
=> Fixed the Clear button functionality on the EMI calculator

assets/css/style.css, blog.html, navbar.css
Improved blog post title color contrast and fixed the login button layout
This pull request resolves the issue of the blog post titles being difficult to read due to insufficient color contrast. Additionally, it fixes the layout problem where the login button appeared half-cut. The changes include improving the color contrast for the blog titles to make them more legible and adjusting the login button's position to ensure it is fully visible, enhancing the overall user experience and design of the page.
These changes improve the readability of the blog section and address layout issues affecting the login button. It enhances the user interface and aligns with the overall theme of the website. The adjustments have been tested across multiple browsers for consistency.
=> Improved Blog Post Title Visibility and Fix Login Button Layout

assets/css/style.css
#1388 
The entire layout has been fixed
@Sampadatiwari Please check my PR i have fixed the entire layout
=> Layout Fixed

contact.html
…he overall user experience.
#1349 solved
The Contact page layout was misaligned, causing elements like the form and map to appear uneven. This misalignment was negatively affecting the user experience by making the page look unstructured and less professional. The issue has been resolved by adjusting the layout and aligning all elements properly to ensure a cleaner, more user-friendly design. This fix improves the overall aesthetic of the page and enhances usability.
https://github.com/user-attachments/assets/81716833-4b8f-4867-8693-b855f92b74c6
=> Fixed the misalignment issue on the Contact page that was impacting the overall user experience.

quiz.html
the login button of quiz page was again changed 
=> Fixed the login button of quiz page

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html
=> fixed navbar of licensing page 

blogs/privacy-policy.html
=> Fixed navbar of privacy policy

blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html
@Sampadatiwari please review and merge
=> fixed navbar of contributors page

blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html
@Sampadatiwari please review and merge
=> Fixed navbar of terms-of-service and refund policy

assets/css/index.css, assets/css/popup.css
=> Button color changed

quiz.html
solved #1392
Aligned Social media icons properly on Quiz page's footer section.
=> solved issue #1392

about.html
@Sampadatiwari please review and merge it please consider it as higher level
before -
https://github.com/user-attachments/assets/af3dec23-f5c1-467b-882f-94188c970011
after-
https://github.com/user-attachments/assets/1520749e-cbd7-4c16-99a2-faa9b275a935
=> Fixed issue #1420- fixed Whole About us page with footer 

contact.html
solved #1396 
https://github.com/user-attachments/assets/e3b4ab3a-f54a-4bdb-98b1-1e290a12f413
=> Enhanced User Experience by Replacing Alert Confirmation with Toast Notifications

index.html
=> implemented "Accept Necessary Cookies Only" option

loginPage.html
Hide/show button not working on sign-in page  https://github.com/ayush-that/FinVeda/issues/1405
https://github.com/user-attachments/assets/05efeb9b-6eae-4560-ae04-0de506d952ba
The bug has been resolved.
=> fixed password eye's show and hide feature.

blogs/Types-of-Stock-Investments-A-Quick-Guide.html
[1422 : Footer unaligned in a blog]
[Updated the footer section of this blog only by changing css and html]
-  Bug fix
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
=> Removed a design bug and alligned the footer UI

CONTRIBUTING.md
Fixes:[#1400 ]
Changes I have made :-
1) Updated overall structure.
2) Added a project structure section
3) Added the help and support section 
4) Added alternate way to contribute through GitHub desktop section
5) Added good coding practices section
6) Added thank you for contributing section
=> Enhanced the current structure and also added some more new sections

careers.html, quiz.html
#1359 
Subscribe forms of both about us and careers fixed
@Sampadatiwari Please review my PR
=> Subscribe form of about us and carrers fixed

about.html
@Sampadatiwari please review it
https://github.com/user-attachments/assets/7ecc6bd8-d128-4b53-b5cf-9c7718ad554b
=> Fixed the about us page

about.html
=> Fixed about us and added contributor 

ContactUs.html, blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/Types-of-Stock-Investments-A-Quick-Guide.html, blogs/economic-trends-and-analysis.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/real-estate-economics.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html, index.html
1454 - Inconsistent footer
Coded up consistent footer across homepage , blogs,contacts us
=> 1454 - Inconsistent footer

assets/css/style.css
Fixed #1326 
I have fixed the text color, made changes in the box shadow and bg color
Kindly add the relevant tags while merging PR
=> Text and bgColor fixed

about.html, contact.html
#1404  solved
The Contact page had a severely misaligned and broken UI, which was affecting the user experience. I have corrected the layout issues and restored the visual design to ensure the page is functional and aesthetically consistent with the rest of the website.
https://github.com/user-attachments/assets/a4fdcfb7-fdd8-47e0-939d-8c2a96b1196c
=> Fixed the broken layout and UI of the Contact page for improved user experience.

assets/css/cookiepopup.css, index.html
#1457 solved
- Corrected the misaligned layout of the cookies consent section to ensure it fits within the design.
- Fixed the duplication of the hero section and blog page, which were being displayed twice on the home page.
- The overall layout and user experience are now consistent and error-free.
https://github.com/user-attachments/assets/9e84da44-5c8d-4fe4-a3bb-043a0583602b
=> Fix Home Page Cookies Consent Layout and Content Duplication Issues

tools/sip.html
@Sampadatiwari fixed all the requirement
=> fixed tools page 

faq.html
#1339 
This pull request focuses on improving the FAQ section’s user interface and enhancing the scrolling experience across the page. The changes include:
**FAQ Section UI Update:**
-> Refined the layout to ensure a clean, responsive, and user-friendly experience.
-> Improved text alignment and spacing for better readability.
-> Enhanced the toggle animation to provide smoother transitions when expanding or collapsing the FAQ items.
**Smooth Scrolling Enhancement:**
->Addressed an issue where the page would experience vibration-like jitter when scrolling.
->Implemented smoother scroll behavior throughout the page for a more consistent and visually pleasing user experience.
These changes ensure that users can navigate and interact with the FAQ section and other page elements without any …
=> Improve FAQ UI and Enhance Smooth Scrolling Experience

assets/css/style.css
Background color fix
Background color fix by adding white background color
=> Fix: #1481 Background color fix

index.html
solved #1337 
made the single login/signup page 
https://github.com/user-attachments/assets/d4782ef0-2915-400d-8aec-194e70b2f813
=> solved #1337

quiz.html
The submit and quiz button fix
The submit and quiz button fix by adding margin to it
=> Fix: #1482 The submit and quiz button fix

about.html
#1403 solved additional #1456 
I have resolved the misalignment issue with the navbar on the About page, ensuring a more structured and visually appealing layout. Additionally, I have made significant fixes throughout the About page to enhance the overall design and user experience. Given the extensive work involved, I kindly request that the issue's difficulty level be increased from level 2 to level 3.
https://github.com/user-attachments/assets/668ed0cc-0d82-4a86-85f7-bbcda203386d
=> Fix About Page Navbar Layout and Overall Page Structure

assets/css/style.css
The comment section of feedback form fix
The comment section of feedback form fix by adding the minimum height property
=> Fix: #1486 The comment section of feedback form fix

ContactUs.html, about.html, blog.html, careers.html, contact.html, contributors.html, footer.html, index.html, login.html, quiz.html, substainability.html, trends.html
**Fix**: **Update "All rights reserved" to "All rights are reserved"**  
Issue No. #1455
This PR resolves the issue where the copyright text "All rights reserved" needed to be updated to "All rights are reserved."
I have individually updated the copyright text in each of the following files:
- List of files changed with their paths  
Since I had to manually modify each file, please consider adding a `level-3` label.
---
---
---
---
=>  "All rights reserved" to"All rights are reserved"

about.html, assets/css/style.css, blog.html, careers.html, contact.html, quiz.html
#1501 solved
The navbar has changed across all pages, resulting in text visibility issues and misalignment. I have reverted the design back to the previous navbar, which was more functional and user-friendly. If this change was unintended, it may be a bug, and I've worked on redesigning the navbar to resolve these issues while maintaining the consistency of the original layout.
https://github.com/user-attachments/assets/3e04d184-0ba9-490d-b105-45d7016be54b
=> Redesigned navbar to fix visibility and layout issues across all pages.

about.html, login.html, navbar.css, navbar.js
Reverts ayush-that/FinVeda#1512
changed the nav bar of the homepage
=> Revert "Fix the navbar visblity issue"

about.html, faq.html, quiz.html
#1508 solved
The preloader was not functioning on the About, Quiz, and Help pages, leading to a blank screen while the pages loaded. This issue has been resolved, ensuring that the preloader works as intended on these pages, providing a seamless user experience.
https://github.com/user-attachments/assets/bf788b9b-5789-4793-893c-e850dd11c98a
=> Fixed the preloader issue on the About, Quiz, and Help pages to ensure smooth page loading.

assets/css/index.css, index.html
to center the cards
I added the div element with class center-cards and then in index.css i add css for it
issue no. #1442
=> Centered cards

assets/css/about.css, index.html
#1474
I have changed the contributors section's background color, cards background, improved the hovering effects, added smooth transitions.
before
After
https://github.com/user-attachments/assets/1954b7ca-0542-45d5-a43c-1f09be70f2e5
@deepeshmlgupta @Sampadatiwari Check if this design looks good. Please mark level 2 if merging and check the deployment for better preview.
=> Contributors section enhanced

assets/css/style.css, careers.html, navbar.css
=> I have fixed it (recommended books section, navbar alignment issue)

assets/css/about.css, contact.html
#1520 
Subscribe btn hovering effect fixed and contributors hovering effect colour changed.
https://github.com/user-attachments/assets/3e814add-01f0-495b-beee-a333742ffad1
@deepeshmlgupta Please review my PR
=> Subscribe button fixed

assets/css/cookiepopup.css
fixed the styling issue
Before:
After:
=> fix the issue cookiepopup buttons

index.html
=> Fixed Blog Section in Home page

index.html
=> Fixed Footer of Homepage

quiz.html
=> Fixed navbar of quiz page

contact.html, navbar.css
#1552 solved
This update addresses the misalignment of the navbar and the overflowing login button that was appearing outside of the navbar structure. By adjusting the layout, the login button now remains correctly aligned within the navbar on all pages. This improvement enhances the overall user experience (UX) by creating a more organized and visually consistent navigation bar, making it easier for users to navigate the website.
https://github.com/user-attachments/assets/cb3f51ce-de66-442b-8974-d2a3df2b01b8
=> Fix Navbar Alignment and Login Button Overflow Issue

index.html
#1537
I added a scroll to top button in the home page which when clicked automatically takes us to the topo of the webpage
https://github.com/user-attachments/assets/6d333875-5e43-4f8a-8fff-2a24a75aba59
@Sampadatiwari Please check my PR i have added the button on the home page.
=> Scroll to top button made

assets/css/trends.css
I made enhancements to the "Top Stories" section by adding a hover effect that creates a more interactive and visually engaging experience for users. Here's a breakdown of the changes:
Before the Change:
The .tradingview-widget-container element had no hover effect or dynamic behavior when the user hovered over it.
The section appeared static, with no transitions or effects to highlight it.
After the Change:
Smooth Transitions:
The element now has a transition property applied with 0.3s ease, allowing for a smooth animation when hovering. This ensures both the transform and box-shadow properties change smoothly over 0.3 seconds.
Hover Transformation:
When hovering, the container grows slightly (scale(1.05)), giving a zoom-in effect that grabs attention and provides a sense of depth.
Box …
=> Added hover effect to top stories section on trends.html page

index.html, tools/contributor.css, tools/contributor.html, tools/contributor.js
Hello, PR
Add new feature - #1547
#1570 
Add Contributors page done -
https://github.com/user-attachments/assets/87a81c6f-e3da-4299-961b-ecef51d4cae3
Page link -
=> Add a new contributors page done ! 

blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/Types-of-Stock-Investments-A-Quick-Guide.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/privacy-policy.html, blogs/real-estate-economics.html, blogs/refund-policy.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/terms-of-service.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Styled the website having issue
After updating
=> updated the issue #1566 by changing the style of header text

about.html, assets/css/about.css, assets/css/style.css, blog.html, careers.html, contact.html, index.html, quiz.html, tools/sip.html
#1320 
I added a theme toggle button that allows users to switch between day (light) and night (dark) modes. The button has been implemented across all pages to ensure a consistent experience.
Additionally, a bug in the navbar was fixed: two instances of the "Help" page were appearing. This issue has been resolved by removing the duplicate link.
The theme change functionality improves user accessibility, providing a better experience for both day and night use cases.
=> Add Theme Toggle Button and Fix Navbar Bug

index.html
The color of Upward arrow is  visible
The color of Upward arrow is  visible
=> Fix: #1582 The color of Upward arrow is  visible

index.html
hover color in scroll button correct
[hover color in scroll button correct
=> Fix #1599 hover color in scroll button correct

about.html, index.html
Created a PR for issue #1532 
added a scroll up button with matching theme of website
=> added scroll up button to about page with matching theme of website

registerpage.html
solved #1542
Added a sign-up page with features like  text field check , password matching .
https://github.com/user-attachments/assets/bf65a23f-7381-4d55-ae74-9c16f5936339
=> solved issue #1542

README.md
This pull request adds a troubleshooting section to the README file to help users resolve common issues when using FinVeda.
Not applicable, as this pull request involves documentation changes only.
=> Add Troubleshooting Section to README

faq.html
[Bug Title here] Add Footer section on Help Page #1578
Issue no:  #1578 
Currently the footer on help/FAQ page is not match with footer of other pages of website.
Before:
After:
https://github.com/user-attachments/assets/7787e263-a0e7-4c06-a14a-08f558d2dd3c
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
=> Add correct footer section on help page

tools/sip.html
#1575 
The code was too complex to understand, thats why couldnt have them as a grid but reduced length vertically for better UI.
=> Updated tools section

blog.html, careers.html, faq.html, quiz.html, tools/sip.html, trends.html
Hello, PR
Fixed issue - #1549 
Add Translation Tool Done(All page) done ✅
Before - #1549
After -
https://github.com/user-attachments/assets/1edca2bb-00e1-4393-9662-6e43b794d215
=> Add Translation Tool Done ! #1549

faq.html, trends.html
Missing Navigation Bar for the FAQ Section #1530
I have added the new uniform navigation bar to the trends section without taking away the Finlogix Widget
Feature enhancement
=> added the nav bar to the trends section

index.html
[Bug Title here] Text is not visible on dark mode #1633
Issue no: #1633 
On some places on home page the text is not visible in dark mode. Due to which user will face problem to read the text.
I've solved the problem by changing the text color and design.
Before:
After:
Before:
After;
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
=> Enhance the text-visibility in dark-mode

ContactUs.html, about.html, blog.html, careers.html, contact.html, faq.html, quiz.html, trends.html
logo is missing in tool page. Covered in screen recording.
link every page logo with home page. issue resolves- #1581 
- [✔️] Feature enhancement
https://github.com/user-attachments/assets/f3be11ee-36a2-41e9-8497-5c939be0bdb3
- [✔️] I have performed a self-review of my code
- [✔️] I have read and followed the Contribution Guidelines.
- [✔️] I have tested the changes thoroughly before submitting this pull request.
- [✔️] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> link every page logo with home page

tools/sip.html
@Sampadatiwari please review and merge it at higher level
before
after
=> Fixed Whole Tools page

faq.html
=> Fixed Footer of Help page

faq.html, trends.html
@Sampadatiwari please review and merge
before
after
=> Fixed Trends page nave bar (active link and darkmode)

faq.html
=> Fixed the size of feeback section and text are now visible

faq.html
Hello, PR
Fixed issue number - #1631 #1630
=> Fixed Text color issue ! 

about.html, assets/css/about.css, assets/css/blog.css, assets/css/index.css, assets/css/quiz.css, assets/css/trends.css, blog.html, careers.html, contact.html, index.html, quiz.html, tools/sip.html, trends.html
**before**
https://github.com/user-attachments/assets/fbf6fb87-3bad-431c-a2d7-b8a29c34042a
**after**
https://github.com/user-attachments/assets/49843915-a6ac-47ea-9bd8-b2c6fe7007a8
** Issue ##1583**
=> To adding animation effect to social media icons

index.html
@Sampadatiwari please review and merge it higher level
before
after
=> Fixed the broken Navbar of home page

index.html
@Sampadatiwari please review and merge
before
after
=> Fixed Whole Footer of Homepage

security.md
Creating a security.md file for security review  #1688 
=> Creating security.md file   

faq.html
Fixes #1627 
This pull request addresses the issue where the image on the FAQ page was misaligned and partially hidden on the left side. The changes ensure the image is properly aligned with the FAQ heading and is fully visible across different screen sizes. The layout has been adjusted to maintain a balanced appearance, improving the overall user experience.
The misalignment was primarily due to the absence of proper padding and margin settings for the FAQ section's image. Adding appropriate responsive styling resolved the issue. 
@sampadatiwari30 @ayush-that , please assign me labels for gssoc-ext level2 and hactoberfest-accepted, once the PR is merged.
=> Fixed Alignment of FAQ Page Image and Ensure Full Visibility

about.html, blog.html, careers.html, contact.html, contributors.html, faq.html, index.html, navbar.css, quiz.html, trends.html
Issue - #1628 
- This PR addresses the issue of an overloaded navigation bar on the website, which contained numerous links and made the interface cluttered. 
- To enhance the overall user experience and visual appeal, I have refactored the navbar by introducing a dropdown for several sections. 
- This change simplifies the layout, reduces visual clutter, and improves the navigation flow.
- Responsiveness
- Appearance
- Performance
- Accessibility
=> Refactored Navbar by Introducing Dropdown for Better UI/UX

assets/css/style.css
Overflowing divs on blog page
Earlier the divs were overflowing , giving a bad UI , so I have fixed this issue.
- [] Feature enhancement
=> Issue: #1345 fixed Overflowing Blog page divs 

careers.html
#1646
Improve the styling of the  Recommended Books section for dark mode.
- [x ] Feature enhancement
screenshots
before:
after:
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> improve the Recommended Books section

assets/css/index.css, index.html
The footer section of home page was broken and i fixed that.
Before
https://github.com/user-attachments/assets/208c9c33-1a13-437f-a332-84ff6b1f81b8
After
=> Broken footer fixed

faq.html
#1568 solved
- Modified the search bar to change to a black background when clicked, creating a more focused and engaging interaction for users.
- Enhanced the hover effects on the FAQ section for improved visual clarity and consistency.
- These updates aim to provide a more polished and user-friendly experience, enhancing the overall design and usability of the Help Page.
https://github.com/user-attachments/assets/6ae6fe9f-45f8-46c6-939c-7a742810223a
=> UI Enhancement for Help Page - fix

index.html
Issue #1684 
Unwanted text was appearing in the landing page (index.html)
Removed the unwanted text.
BEFORE:
AFTER:
=> Removed the unwanted text in index.html

assets/css/style.css
#1354
Originally the contact us portion was at extreme left . I updated it's left margin.
=> Update Margins of contact us portion

index.html
Icon symbols #1645
The issue I raised was for changing icons for home, tools, quiz,etc. and I have done the needful changes respectively. @ayush-that @sanjay-kv @https://github.com/SampadatiwariI have made the changes and also uploaded ss. Please review the top icons that I have made and the pictures below. I request you to the do merge it into the main branch please
##Checklist:
I have performed a self-review of my code
Original one
=> The nescessary icons for Home has added

tools/Billsplit.js, tools/EPFCalculator.js, tools/FDCalculator.js, tools/GSTcalc.js, tools/IncomeTax.js, tools/RDCalculator.js, tools/SavingsGoalCalculator.js, tools/cal.js, tools/emiCalculator.js, tools/insuranceCalculator.js, tools/roiCalculator.js, tools/sipcalculatorJs.js
The current implementation of the calculator does not perform sufficient input validation. Users can enter invalid data (e.g., negative numbers, non-numeric characters) without receiving appropriate feedback. This could lead to incorrect calculations or application crashes.
The application now validate all user inputs before performing calculations.
Users should receive clear error messages when inputs are invalid.
All input fields should restrict invalid characters and provide default values where applicable.
PS-Have considered as features, since I worked in error exception and handling for all EPF, FD, GST etc calculators
How can I show this, there are error messages and popups if you want to see....
=> [Bug] Inadequate Input Validation and Error Handling in Calculator #1563

careers.html
Career Page was not responsive for all screen sizes.
issue: #1710 
I've modified the css styling to made it responsive in this PR.
https://github.com/user-attachments/assets/79452c74-3bc4-4ca0-987d-a0c37e989570
=> Made Career Page Responsive

registerpage.html
close #1569 **this issue was originally to aded link to registerPage in loginpage but that was done by someone else still the button redirecting to loginPage in registerPage was still non-functional so i added link to loginPage in registerPage so merging this pr will should close my issue**
please assign this to me under gssoc-ext
=> added link to loginPage in registerPage

careers.html
#1678
Improve the UI of the  carrer page Carrers roadmap section.
- [x ] Feature enhancement
before
after
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> Improve the UI of the Carrers roadmap section

blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/Types-of-Stock-Investments-A-Quick-Guide.html, blogs/economic-trends-and-analysis.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/privacy-policy.html, blogs/real-estate-economics.html, blogs/refund-policy.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/terms-of-service.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
##Issue #1644 
When we enabled dark mode in home page it was not applying for blogs sections
I have updated all the blog section with dark mode feature
=> Issue #1644 resolved by adding dark mode feature to all blogs section

contact.html
Header mismatching color fixed 
Before
After
=> Header fixed of contact page

assets/css/preloader.css, assets/js/preloader.js, index.html
This pull request addresses issue #1706
This pull request adds a Lottie animation as a loader to improve the loading experience on the web page. The loader has been styled to appear smaller and fit neatly within the center of the page with a blank background.
**Screenshot:**
=> Added an animated lottie loader

assets/css/style.css
I changed the design of blog cards
https://github.com/user-attachments/assets/91ef4f91-bfc7-4b92-b298-d5c5490695a0
=> Design of blog cards changed

about.html, index.html
=> Fixed footer in home page

index.html
@Sampadatiwari please review merge it
=> Fixed Navbar in home page

about.html, index.html
=> Fixed image position in about us page

loginPage.html
I have added the forogot password feature sir
Before:
After:
=> forgot password added successfully : Forgot password implementation in login page #1725

index.html, navbar.css
#1722 
@ayush-that 
None
added side icons to the website 
https://github.com/user-attachments/assets/c75becde-a8ea-464a-83fb-997551bef701
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> added side icons

faq.html, index.html, tools/sip.html
#1724 solved
The footer on the Help page is completely misaligned, creating a visually jarring effect. Additionally, the Home page footer differs from the footers on other pages, leading to inconsistency in the overall site design. On the Tool page, the footer elements are not properly aligned, which affects readability and user navigation. This update resolves these issues by standardizing the footer design across all pages, ensuring proper alignment and a consistent look and feel for better user experience.
=> Fix footer misalignment and ensure consistent design across Help, Home, and Tool pages.

README.md
#1671 
Added a **Table of Contents** to the README for easier navigation and better structure, enhancing the user experience.
Adding a Table of Contents improves the readability of the README and helps users navigate the document more efficiently.
=> ADD TABLE OF CONTENT ON README

index.html
ISSUE #1770 
The buttons were not in order and unwanted text was appearing in the homepage.
Fixed the CSS of the the buttons in navbar and removed the unwanted text.
BEFORE:
AFTER:
=> Fixed navbar of homepage and removed unwanted text.

assets/css/style.css, blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html, blogs/Pocketmoney.html, blogs/Types-of-Stock-Investments-A-Quick-Guide.html, blogs/economic-trends-and-analysis.html, blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html, blogs/how-fintech-is-revolutionizing-small-business-lending.html, blogs/how-to-10x-your-generational-wealth.html, blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html, blogs/invest-minimal.html, blogs/privacy-policy.html, blogs/real-estate-economics.html, blogs/refund-policy.html, blogs/saving-for-future.html, blogs/senior.html, blogs/starup.html, blogs/terms-of-service.html, blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html, index.html
now card missalign issue is solve for all device users
in the blog's html file icon of finveda is not included in all html file after added
in the card learnmore btn is collapsed with the text in all card for mobile,mac's,ipad and some card for laptop users after solved
my issue no. is #1720
=> card and blogs icon fixed

blogs/privacy-policy.html, blogs/terms-of-service.html
- issue - #1746 
This pull request addresses issues related to navigation from the Privacy Policy and Terms of Service pages to the Login page. The following changes were made:
- Updated the anchor tags in privacy.html and terms.html to correctly link to the loginPage.html.
- Ensured that the links use proper relative paths for better maintainability.
These changes enhance user experience by ensuring that users can easily navigate to the Login page from these important policy documents.
- Terms of Service 
https://github.com/user-attachments/assets/755ad508-3094-4206-805c-d189ce2d9397
- Privacy Policy
https://github.com/user-attachments/assets/de635354-1f60-4fff-a41b-78d1ff4c9c71
changes have been made in both privacy-policy.html and terms-of-service.html
=> [ FIX ] : Navigation from Privacy Page and Terms of Service Page to Login Page

contact.html, index.html, navbar.css
issue: #1779 
Update the placeholder style resize it added some border animation and hover to it also improve the button style.
https://github.com/user-attachments/assets/1bb579a9-e606-4a33-9720-2992b240ceac
=> Enhanced the placeholder style and button

index.html
#1789 
remove extra text from footer
=> remove extra text from footer

about.html, blog.html, careers.html, contact.html, index.html, maps.html, quiz.html, tools/sip.html, trends.html
added map located low ,high,medium finanancal literacy states in india
https://github.com/user-attachments/assets/d41612d2-0f7d-4919-b41d-12b3a853a1be
https://github.com/user-attachments/assets/4a8046f4-bed6-4cd8-865f-e64f1d2d48c2
=> Solved #1790  added map located low ,high,medium finanancal literacy states in india

faq.html
issue #1787 fixed
This pull request addresses the issue of a duplicate footer being visible on the help page. The issue was caused by an unintended rendering of the footer component multiple times. Changes include:
- Identified and removed the redundant footer code.
- Ensured that only a single instance of the footer is rendered.
- Tested across various screen sizes and devices to confirm the fix.
This update improves the user experience by preventing UI inconsistencies and reducing page clutter.
https://github.com/user-attachments/assets/17b46ed0-fc41-4840-8393-8334e41d5c0d
<!-- [X] - put a cross/X inside [] to check the box --
=> Fix Duplicate Footer Issue on Help Page

index.html
=> Remove extra footer from bottom

loginPage.css, loginPage.html, registerpage.html
login page added icon facebook and X and also added hover 
fixes #1768 
- [ X] Bug fix
- [X ] Documentation update
- [ X] Other (specify): _______________
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
=> add icon  facebook and X   and  hover sign up and login 

index.html
#1764 
Fix the theme toggle button click functionality and remove unnecessary elements causing bugs.
Removed redundant code, including duplicate navbars, to improve structure and functionality.
=> Update Theme Button on Homepage

maps.html
Fixes:  #(#1815)
so basically i just recreate the  "Financial Literacy Dashboard" PAGE   which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- redesign the  whole section
- change border colors
- change the shape of pictures 
--BEFORE:-
---AFTER:-
=>  UI IMPROVEMENT IN "Financial Literacy Dashboard" PAGE #1815

faq.html
Issue resolved: #1818
- [x ] I have tested the changes thoroughly before submitting this pull request.
=> removed unnecessary content

index.html
#1767 
Corrected functionality for the "Next" and "Previous" buttons in the testimonial section, ensuring seamless navigation through user testimonials. The buttons now correctly cycle through testimonials, enhancing user experience and engagement.
=>  Correct Next and Prev button functionality 

about.html
@deepeshmlgupta and @Sampadatiwari please review and merge it 
before 
after
=> Removed Extra Login from navbar of about us page

assets/css/quiz.css, quiz.html
now quiz section is responsive for all device 
resolve the issue of navbar 
before
after
my issue no. is #1806
=> fix the responsivness of quiz + fix the navbar of quiz

about.html
Fixes:  #(#1814)
so basically i just recreate the  "OUR CONTRIBUTORS" SECTION   which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- redesign the  whole section
- change the SIZE of pictures so that easy to read 
- and also unessential white color div
--BEFORE:-
---AFTER:-
=> UI IMPROVEMENT IN CARDS OF CONTRIBUTORS SECTION #1814

about.html, blog.html, loginPage.css, loginPage.html
#1732 solved
The animation for both the login and sign-up pages is currently not functioning as expected, which negatively affects the user experience by making the transition between states feel less smooth. Additionally, I will enhance the overall UI for both pages to align with modern design standards, making the user interface more appealing and intuitive. This will improve not only the visual appeal but also the usability, providing a more cohesive and seamless experience for users navigating the login and sign-up processes.
Before:
https://github.com/user-attachments/assets/aef3df48-5ae5-40bb-8f43-8e541c7dd2f4
After:
https://github.com/user-attachments/assets/c8995fae-b3e6-4447-b638-61532aea264a
=> Fix Login and Sign-Up Page Animations, UI Enhancement

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html
The animation on home page is added on every footer-linked pages
https://github.com/user-attachments/assets/50ac9950-6fdd-4c7f-aad6-daa05c2e308c
=> Animation added on every page

assets/css/index.css, index.html
#1765 
Make "Back to Top" and "Top to Down" buttons consistent.
=> Update Scroll Down button

about.html
Fixes:  #(#1798)
so basically i just recreate the   "ABOUT US " SECTION  which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .
AS I ADDED:-
- redesign the  whole section
- change the SIZE of pictures so that easy to read 
- add border 
--BEFORE:-
---AFTER:-
=> UI IMPROVEMENT IN "ABOUT US PAGE" #1798

assets/css/style.css, index.html
The feedback form is fixed for all screen resolution now
=> Feedback form fixed

about.html
Reverts ayush-that/FinVeda#1831 
see.
=> Revert "Removed Extra Login from navbar of about us page"
