ayush-that/FinVeda

assets/js/main.js
fixed #34 
There was some issue with `$(this.hash)` which is fixed by `$(this)` ( hash removed )
`var sectionOffset = $(this).offset().top - 73;`
This was returning float values due to which no operation can be performed thats y i use `var sectionOffset = Math.floor($(this).offset().top - 73);` which gives floor values 
and there is not conflict in file
**no error is showing while scrolling the window**
[Screencast from 11-05-24 06:32:56 PM IST.webm](https://github.com/ayush-that/FinVeda/assets/112775332/2bb20db0-9755-4f6a-aecc-477f9bf2f333)
=> fixed issue #34

assets/css/style.css
This pull request addresses a bug where multiple review cards were being highlighted at the same time. This fix ensures that only one review card can be highlighted at a time.
- Modified the highlight logic to ensure only one card is highlighted at a time.
- Verified that only one review card is highlighted when it is hovered over.
- Ensured that other cards are not affected by the highlight state.
Please review the changes and let me know if there are any further adjustments needed.
=> Fixed issue of multiple reviews being highlighted simultaneously

assets/css/slick.css, assets/css/style.css
This pull request addresses the issue where the testimonial boxes on the _Home Page_ of "_Users Sharing their Experiences_" section had different heights due to varying content lengths. Now all the boxes have same height which gives a clean and consistent layout.
**_(Before)_**
(**After**)
=> Fixed the unequal height issue of Testimonial Boxes in the User Experience Section!

index.html
The Typing error in footer has been fixed.
The _Quick Link_ has been changed to _Quick Links_.
Here's how it looked before,
And here's how it looks now,
Issue Number:
#337 Fixed 
Thank You for assigning me this issue. Please add suitable labels to this PR.
=> Fixed Typo in Footer

index.html
It is a simple 2 line change that is being done but i feel it is much needed. The main problem was while clicking on the Chat with Artha Sathi which is in the top of the home page, it was generating a popup which it shouldn't it should directly take the user to the chatbot. Making this change i have successfully managed to redirect it.
=> Direct link to chatbot from home page added

assets/css/style.css
- I have fixed the responsiveness issue that was previously coming.
- Fixed the Home page, Blog page & Tools page responsiveness issue.
- Now the blank space is gone from the right side of the webpages.
https://github.com/user-attachments/assets/351577c6-a36c-40cf-ad8c-e809e22e8465
_Please review & merge this pull-request under GSSoC'24._
=> Fixed the right side responsiveness issue of 3 pages.

tools/sip.html
Fixes #491 
made the following calculators responsive in mobile view.
=> made MFI and EMI calculators on tools page responsive at mobile view.

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, tools/sip.html
Hey @ayush-that  @deepeshmlgupta and @Agarwalvidu  issue closes #425 
I have added resource section footer links in missing pages footer
- Tools Page
- Privacy Policy Page
- Terms and Conditions Page
- Licensing Page
- Cookies Policy Page
Take a look and review this PR
=> Added Resource Section Footer Links in Missing Pages Footer 

assets/css/style.css
Hey @ayush-that, @deepeshmlgupta and @Agarwalvidu  issue closes #535 
I have fixed the overlapping of the feedback button behind the footer
=> Fixed The Feedback Button is not Overlapping Behind The Footer #535

assets/css/style.css
Issue : #574 
In the home page at Savy team section border and  hovering effects added to the cards to make better user experience and interface. 
Before:
After:
@ayush-that and @Agarwalvidu , please check the changes and merge the changes to the project to make contribution.
Thank you
=> Title:-Hovering and border effects added to the savy team cards

blog.html, quiz.html, tools/sip.html, trends.html
Issue #611 solved
Removed the redundant 'About Us' button instances in the blogs, trends and tools page.
=> Fixed repetition of the 'About Us' button in the navbar

Licensing.html, about.html, assets/css/style.css, blog.html, index.html, quiz.html, tools/sip.html, trends.html
Fixes #629
Removed the underline on hover for the login/register button on the following pages:
1. Home
2. About
3. Trends
4. Tools
5. Blogs
6. Quiz
7. Licensing...also, made the login/register button same as other pages.
https://github.com/user-attachments/assets/a34a30a1-f0f4-4786-8074-7830f0bbb202
=> Fixed Underline on Hover for Login/Register Button

Licensing.html, assets/css/style.css
Fixes #718
Fixed double underline on Navbar Hover on Licensing Page.
Before:
After:
https://github.com/user-attachments/assets/3e82ca2a-92b2-48a8-8f1c-21703282a4ee
=> Fixed double underline on Navbar Hover on Licensing Page 

quiz.html
It will now take the wole available area to look better
=> Fixed the quiz section for mobile screen

Licensing.html, blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html, navbar.css
Issue #789 solved 
Implemented the new hamburger menu in mobile view for 'Privacy Policy', 'Refend Policy', 'Terms of Service', Licensing' and 'Our Contributers' pages. 
Privacy Policy Page: 
Refund policy Page:
Licensing Page: 
Terms of Service Page: 
Our Contributers Page:
=> Fixed Inconsistent Hamburger Navbar Across Pages

assets/css/style.css
Fixes  #817 
Fixed Unwanted Bullet Points in the Footer on Licensing Page.
**Before:**
**After:**
=> Fixed Unwanted Bullet Points in Footer on Licensing Page

blogs/privacy-policy.html, blogs/refund-policy.html, blogs/terms-of-service.html, contributors.html
Issue #792 solved
Added the location icon in the footer of 'Privacy Policy', 'Refund Policy', 'Terms of Service' and 'Our Contributers' page to make it consistent with other pages.
Before: 
After:
=> Added Location Icon in Footer

assets/css/about.css
Issue #837 solved
Made the about us page mobile responsive and fixed the overlapping cards problem.
=> Fixed Overlapping Cards on About Us Page in Mobile View

contributors.html
=> Added Github Icon

contributors.html
Hey @KomalMaurya @Agarwalvidu 
- issue closes #890 
I have fixed the bug in contributors data fetching in the contributors page
The GitHub API Key was fetching the data by default only 30 contributors per page so I have made the changes in the script.
https://github.com/user-attachments/assets/646f36e4-62fd-4ccb-991b-94d401e6da4e
=> Fixed the Bug in Contributors Data Fetching in Contributors Page

about.html, assets/css/style.css
=> Fixed about page for mobile screen size

tools/sip.html
issue no :- #942 
fixed know more button option and heading of bill split calcualtor
=> fixed bill split calculatr heading& knowmore

about.html, blog.html, contributors.html, index.html, quiz.html, tools/sip.html, trends.html
Title Update Feature for Login/Register Modal
I have successfully enhanced the user experience by implementing functionality that changes the browser title to "Login/Register - FinVeda" whenever the login modal is triggered. This improvement ensures consistency across the application, as the title now updates not only when accessing the modal from the home page but also from various other pages, including:
About Us Page
Quiz Page
Tools Page
Trends Page
Blogs Page
This feature provides clarity to users, indicating that they are in the login/register context regardless of their current page, enhancing overall navigation and usability. …
=> title of login/register-FinVeda

assets/css/popup.css, index.html
Fixes #963
the login button was not displaying the login/register pop-up on mobile screen having width less than 575px and was not responsive
Initally: Login/Register button clicked , pop-up not visible
After Fix: Pop fixed and responsive for all-screens
=> fixed login page not visible on mobile screen

about.html, blog.html, careers.html, quiz.html, tools/sip.html, trends.html
Fixed issue #1023 
The problem of the redundant intro section is being solved. Now the other sections of the website(About, Blogs, Tools, etc.) display only their respective content
=> Restricted the intro section to home page

assets/css/cookiepopup.css
#1246  
Description
This pull request addresses the alignment of the cookie consent banner, ensuring that it is positioned correctly at the bottom of the viewport and slightly elevated for better visibility.
Type of PR
Bug fix
Feature enhancement
Screenshots / videos (if applicable)
https://github.com/user-attachments/assets/9aa141cf-64f4-4b5a-867d-9e4ce9907499
Checklist:
I have performed a self-review of my code
I have read and followed the Contribution Guidelines.
I have tested the changes thoroughly before submitting this pull request.
I have provided relevant issue numbers, screenshots, and videos after making the changes.
I have commented my code, particularly in hard-to-understand areas.
=> cookies content is now set properly #1246

careers.html, contact.html
I have created a pull request for issue #1259 which was assigned to me.
In the footer section of the Career page and Contact page, under the "Contact Us" section, there is an unusually large gap between the icons and their corresponding text labels. This affects the layout's visual appeal and may impact readability for users.
=> Removed excessive space between icons and related text for contact and career pages

assets/css/trends.css, faq.html, trends.html
#1346 solved
To improve the user interface and make navigation more seamless, the 'Back to Home' text link has been replaced with a home icon on both the Trend and Help pages. This adjustment aligns with modern design practices, making the website more user-friendly and visually consistent. This update also helps in reducing text clutter while maintaining the functionality of redirecting users to the home page.
https://github.com/user-attachments/assets/4545c7a8-ed5e-4127-b04e-aeed4b40e034
=> Replace 'Back to Home' Text with Home Icon on Trend and Help Pages

tools/sip.html
EMI Calculator Renders Twice on the Tools Page
This pull request addresses the issue of the EMI calculator rendering twice on the Tools page. The duplicate instance has been removed, ensuring that only one EMI calculator is displayed to maintain a clean and functional layout. The changes will help improve the user interface and user experience on the Tools page by eliminating redundancy.
https://github.com/user-attachments/assets/4e575a89-c069-4c75-b7bf-bfcde50cd5ea
The fix ensures a streamlined user interface by keeping only one EMI calculator visible on the Tools page. This change has been tested across various browsers for consistency to ensure that the update works as expected.
=> Removed duplicate EMI calculator on the Tools page

assets/css/cookiepopup.css
[Bug]: Cookies Consent and Language Change option are collapsing each other #1382
The Cookies Consent and Language change options are collapsing each other.
Due to which we can't see the language change option and also unable to change the language.
The language change option is behind the cookies consent.
I've fixed it at correct postion.
Before:
After:
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
]
=> Fixed the Cookies Consent

assets/css/market-time.css, assets/js/market-time.js, trends.html
#1334 
integrated a real-time global market status feature on the trends.html page. This feature will display the open/close status of various markets (e.g., equities in the US, UK, Asia, etc.). The data will be presented in responsive, scrollable cards to ensure efficient use of page space. The section will auto-update every minute to keep the information current.
=> add market time with open and close status

about.html, careers.html, contact.html, faq.html
#1565 solved
Resolved the issue where two "Help" buttons were appearing on the navbar of the Contact and Career pages, which was impacting the clarity and overall user experience. Additionally, corrected the logo alignment on the About and Help pages to maintain design consistency throughout the website.
=> Fix Duplicate Help Button on Navbar for Contact and Career Pages

faq.html
Fixes #1541
This pull request addresses the issue of double scrollbars appearing in the FAQ section when accessed through the "Help" link in the navbar. The changes ensure that only a single scrollbar is displayed, providing a smoother and more consistent user interface. Adjustments were made to the CSS to prevent multiple scrollbars from appearing and to maintain the intended layout.
The issue was reproducible in multiple browsers (Chrome, Firefox, Safari) on Windows 11. Fixing this will enhance the user experience by ensuring a clean and uncluttered interface in the FAQ section.
=> [Bug Fix] Resolve Double Scrollbars Issue in FAQ Section

index.html
Closes: #1609 
The scroll up button was overlapping with the chat suport button onthe homepage.
https://github.com/user-attachments/assets/0f4c43f4-b2a2-45f6-a1e1-274542be0850
=> Fixed the scroll up button overlapping on home page

assets/css/index.css, index.html
Fixes #1543
This pull request resolves the incorrect positioning of the "Go Down" button on the home page. The button is currently appearing vertically in the middle of the screen, disrupting the layout. The changes made ensure that the "Go Down" button is now placed to the left of the "ChatBot" button, creating a balanced and visually appealing layout that improves user navigation.
This fix addresses a layout issue that affected multiple browsers (Chrome, Firefox, Microsoft Edge) on Windows 11. By correctly positioning the "Go Down" button, the home page layout will now be more intuitive, enhancing the overall user experience.
=> [Bug Fix] Correct Positioning of "Go Down" Button on Home Page

faq.html
Fixes #1612
This pull request implements a real-time search functionality for the FAQ section. The new feature dynamically updates the search results as the user types in the search bar, allowing for a seamless and efficient search experience. It highlights relevant keywords and displays the most closely related results first, improving the ease of finding specific information. The functionality enhances user experience by making it easier to access frequently sought information without navigating through multiple pages.
https://github.com/user-attachments/assets/2c6aa0c7-76a5-4435-90d4-375e231219a6
The search feature has been tested on various browsers (Chrome, Firefox, Brave) to ensure consistency and performance. It significantly improves the FAQ section by making information easily …
=> [Feature] Add Real-Time Search Functionality for FAQs

quiz.html
#1618 
The allignment of list in the footer section of Quiz page was messed.
I have added the required CSS in (quiz.html) so that the list looks properly alligned.
BEFORE:
AFTER:
=> Fixed the allignment of list (Quiz Links & Resources) in footer of QUIZ PAGE

index.html, tools/sip.html, tools/sipcalculatorCss.css
[Bug ] Expand the size of calculators on tools page. #1579
Issue: [Bug Title here] Expand the size of calculators on tools page. #1579
Issue no: #1579 
The size of calculators on tools page is very small as the options inside it are colliding each other.
I've solved the issue by expanding the width of calculators.
Before: (Options are colliding each other.
After:
Before: (Text not visible inside the input box)
After:
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
=> Expand the width of calculators for better visibility

faq.html
Fixes #1610
This pull request addresses the issue of the FAQ section rendering multiple times on the Help page. The issue caused inconsistent behavior in the user interface, where additional duplicate FAQ sections appeared after the first one. The fix ensures that the FAQ section is displayed only once, thereby maintaining a consistent and clean UI.
https://github.com/user-attachments/assets/f54e6440-715d-4f64-9774-786af5ff9432
The fix has been tested across different browsers (Chrome, Firefox, Brave) on Windows 11 to ensure consistency and improved user experience on the Help page. The changes now prevent multiple instances of the FAQ section from rendering, aligning the page with the expected behavior.
@sampadatiwari30 @ayush-that , please assign me labels for gssoc-ext level2 and …
=> Fixed Multiple Rendering of FAQ Section on Help Page

index.html
`issue: #1548`
Solve overlapping scroll down button to Chat close button
Before:
After:
=> Fix Overlap Between Scroll Button and Chat Close Button

assets/css/style.css
`issue: #1572 `
solving overlapping of service icon from service box.
Before:
After:
=> solve overlapping service icon

index.html
#1677 solved
The issue where the Tool button was being incorrectly highlighted as the active link while the user was on the Home Page has been resolved. Now, the active link will correctly reflect the current page, ensuring accurate navigation feedback and improving the user experience across the site. This fix ensures that only the appropriate navbar button is highlighted when navigating the site.
=> Fixed active link highlighting issue on Tool button when on Home Page

tools/sip.html
fixed the logo which was not visible earlier on the tools page
fixes #1708 
close #1708 
**before
**
**after**
- [#1708  ] Bug fix
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
please add hacktober fest and level 2 label
=> fixed logo on tools page

contact.html
Issue #1713 
The lists were not alligned properly in the footer section of Contacts page.
I fixed the CSS of both the lists, and added an extra class (resources-link) in ul tag of Resources.
BEFORE:
AFTER:
=> Fixed the entire CSS of the lists in footer section of Contact page.

tools/sip.html
Tool page logo was missing and also linked with it home page.
Resolve issue- #1641 
- [✓] Bug fix
https://github.com/user-attachments/assets/2d6ccab2-31dc-4da6-ab5b-1e12322940a4
- [✓] I have performed a self-review of my code
- [✓] I have read and followed the Contribution Guidelines.
- [✓] I have tested the changes thoroughly before submitting this pull request.
- [✓] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> link logo with home page and tool page logo correction

index.html, tools/sip.html
---
- **Issue No**: #1782 
I have removed the redundant "HeaderFooter" text that was being displayed at the bottom of the footer. This unnecessary text cluttered the UI, and removing it improves the design.
- Identified the root cause of the issue in the footer component.
- Removed the "HeaderFooter" text from the HTML structure.
- Ensured that there were no dependencies or styling conflicts after the removal.
- Tested the footer to confirm it displays correctly across different pages.
- **Before**: 
- **After**: 
- HTML
- CSS
- ReactJS
=> Removed Unnecessary "HeaderFooter" Text from Footer and Enhanced Styling for "Know More" Section in Footer

index.html, quiz.html
Reverts ayush-that/FinVeda#1954
=> Revert "Revert "Animation added in quiz and contact page""

README.md
- **Fixed**: Resolved the issue with the Hacktober Fest image that was not displaying in the README.
- **Added**: Implemented a contributors scroller that updates automatically.
- The README now properly displays the Hacktober Fest image, enhancing visibility for the event.
- The contributors scroller has been added to showcase all contributors dynamically, ensuring it reflects the latest contributions without manual updates.
Thank you for considering this pull request! Kindly merge it and assign me labels.
fixes: #1990 
https://github.com/user-attachments/assets/437cc74c-14eb-4d3a-bad2-521420806bfa
=> Add Automatic Contributors Scroller & Fix Hacktober Fest Image

index.html
issue_number: #2011 
Extra space fix in the bottom of home page footer
Before:
After:
=> Extra space fix in footer of home page

faq.html
https://github.com/user-attachments/assets/ae4775ad-a379-4bb5-8fa6-8febf96c6bc3
None.
This update addresses a visibility issue in the FAQ section when using dark mode. Previously, the text within the FAQ items was difficult to read against the dark background. This fix adjusts the CSS styles to ensure that the text color contrasts appropriately with the dark mode background, enhancing readability and overall user experience. The adjustments made ensure that the FAQ items remain accessible and visually appealing in both light and dark modes.
=> Fixed FAQ progress text which  were not visible in Dark mode

index.html
#1995 
I've noticed that the "Help" option is currently absent from the website's navbar. This omission could potentially hinder user experience and support. 
So, added the help page reference in the navbar to redirect.
Added the missing "Help" option in navbar, additionally added "Tools".
=> Help option added

careers.html
#2040 
Improved the design of the roadmap and books sections by adding curved borders, matching colors, and subtle hover animations. Enhanced visual consistency with a soft gradient background and pop effects for emojis, ensuring both sections are aligned and responsive.
=> Improved Hover Effect on Career Page 

faq.html
#2061 solved
Enhanced the progress bar’s visibility on the FAQ page to improve user experience. Previously, the progress bar was difficult to see, especially when interacting with FAQ items. The updates adjust its styling and color scheme for better contrast and clarity, ensuring a smoother navigation experience across the FAQ section.
https://github.com/user-attachments/assets/41ec4d33-97df-4342-9ee8-787fadc313f7
=> Improve visibility of progress bar during FAQ selection

tools/sip.html
issue_number: #2107 
Placeholder overlapping fix in tools page Income tax calculator section
Before:
After:
=> Placeholder overlapping fix

blogs/privacy-policy.html
This pull request introduces a card layout for the Privacy Policy sections to enhance readability and user experience. Each section is now wrapped in a card-like design, making it visually distinct and easier to navigate.
- Implemented card structure for all points in the Privacy Policy.
- Added CSS styles for card design and hover effects to improve interactivity.
This update improves the overall aesthetic and organization of the Privacy Policy, providing a clearer structure for users.
Kindly merge it and assign me level 2 for this task.
fixes: #2006 
https://github.com/user-attachments/assets/5a7d7bf0-ba51-4a1f-b892-838066851171
https://github.com/user-attachments/assets/e0e14dca-2120-42bf-907e-6fea41c6db13
=> Add Card Layout for Privacy Policy Sections

README.md
In reviewing the contributors scroller on the README, I discovered that the code responsible for displaying the contributors was implemented twice. This redundancy was causing the contributors to appear twice on the page, which led to confusion for users.
- Removed the duplicated code for the contributors scroller to ensure that contributors are displayed only once.
- Verified that the scroller now appears correctly and enhances the overall user experience.
The contributors scroller now functions as intended, displaying each contributor only once, which improves the clarity and appearance of the page.
**Thank you for considering this fix!**
Kindly merge it and assign me the level 1.
fixes: #2146
=> Fix Redundant Contributors Scroller in README

trends.html
#2227 fixed
The trend page currently shows the active link indicator on the home button rather than the trend button, which disrupts navigational clarity for users. This update ensures that the active link correctly highlights the trend button when on the trend page, providing a consistent user experience and clear indication of the user’s current location within the website.
=>  Fix Active Link Displaying Correctly on Trend Page

assets/css/index.css
Fixes: #2319 
in suscribe to newsleter section the placeholde and button are overlapped with rach other it makes ugly to your website i fix this
Before:
After:
=> Overlapping Fix of placeholder with button

careers.css, careers.html
Fixes: #2265
- Adds a salary-based filtering feature in the "Jobs in Finance" section to enable users to filter jobs by specific salary ranges.
- Implements a filter dropdown that allows users to select a salary range, such as jobs above $80,000.
- Improves user experience by enabling targeted job searches based on salary expectations.
https://github.com/user-attachments/assets/25c388d4-336a-47a8-936d-d8d61b3884f6
@ayush-that @sampadatiwari30 Please consider assigning me this issue under gssoc-ext level3 and hacktoberfest-accepted, as I have implemented a new feature.
=> [Feature] Added Salary-Based Filtering to Finance Jobs Section

careers.html
Fixes: #2481 
We resolved an issue where table text became difficult to read when switching to dark mode due to font color automatically changing to white. By implementing a `.dark-mode` class in the HTML and adjusting the CSS, we ensured that text inside the table elements (`<th>` and `<td>`) remains black in dark mode, improving readability and maintaining visual consistency. This approach leverages a toggle function that applies the `.dark-mode` class to the `<body>` element, allowing dark mode styling without impacting overall usability. 
.
Bug fix
https://github.com/user-attachments/assets/1b742886-70e3-4437-a4e0-2729ffd0ac96
=> Fixed the table contents that were not showing in light mode in career page

contributors.html
This pull request addresses the text color of the main `<h1>` heading in the FinVeda Contributors section of the webpage. The objective is to enhance readability and maintain a consistent user experience across different display modes (light and dark).
- **Updated `<h1>` Text Color in Light Mode:**
- The text color for the `<h1>` heading has been set to `black` when light mode is enabled. This adjustment ensures that the heading is clear and easily readable against lighter backgrounds.
- **Retained Dark Mode Styling:**
- The existing dark mode styling has been preserved by keeping the `dark:text-gray-200` class. This ensures that the text appears in a suitable gray shade when the dark mode is activated, maintaining visual coherence.
=> Update <h1> Text Color for Light and Dark Modes

index.html
- Previously, the text within `<li>` elements in the "features" section became white on a white background when the dark theme was enabled, making it unreadable.
- Updated styles for `<li>` elements to ensure the text color remains black, maintaining visibility in both light and dark themes.
- Text was white on a white background in dark theme, making it invisible.
- Text color is now black, ensuring readability across all themes.
=>  Fix text color visibility on dark theme in features section

contributors.html
Hello, PR
Add Project Statistics in Contributors page Done -
https://github.com/user-attachments/assets/81b638bf-699a-4f33-952e-5048db1a6821
=> Add Project Statistics in Contributors page done ! 

quiz.html
Fixes: #2511
The Home Page Hero section is incorrectly rendering at the top of the Quiz page, which disrupts the intended flow and focus of the page. Only the quiz content should appear on this page to provide users with a straightforward quiz experience without unnecessary elements like the Hero section.
BEFORE:-
AFTER:-
GSSOC EXT.
=>  Unintended Hero Section Display in Quiz Page

contact.html
Fixes: #(#2511)
The Home Page Hero section is incorrectly rendering at the top of the Contact page, which disrupts the intended flow and focus of the page. Only the quiz content should appear on this page to provide users with a straightforward quiz experience without unnecessary elements like the Hero section.
BEFORE:-
AFTER:-
GSSOC EXT.
=> Unintended Hero Section Display in Contact Page

tools/sip.html
🛠️ Fixes Issue
Fixes: #2492 
👨‍💻 Description
What does this PR do?
This PR addresses an alignment issue on the "Tools" page where the containers for the Total Cost of Ownership (TCO) Calculator and the Income Tax Calculator differ in size. This inconsistency affects the visual layout and user experience.
Summary of Changes:
Adjusted the CSS styles of the TCO Calculator and Income Tax Calculator containers to ensure they have matching sizes.
Improved the overall aesthetic and usability of the "Tools" page.
Motivation and Context:
Maintaining a uniform layout enhances user experience and visual consistency across the page, making it more user-friendly.
Dependencies:
No additional dependencies are required for this change.
📄 Type of Change
Bug fix (non-breaking change which fixes an issue) …
=> Ensured consistent sizing of tco and income containers

about.html, assets/css/style.css, contact.html, finance.html, navbar.css
Fixes: #2537 
This PR addresses an issue with the navbar where the active link is not correctly displaying, causing user confusion about the current page. The active state functionality has been fixed, ensuring that the correct navbar link is highlighted based on the user's current page. This enhancement improves navigation clarity and user experience across the platform.
https://github.com/user-attachments/assets/2a1a4bed-d6d9-4c7b-bb03-77f4762acb1d
=> Fix active link functionality in navbar for accurate page indication

tools/sip.html
This pull request includes significant updates to enhance the user interface and accessibility of the TCO Calculator and Income Tax Calculator forms. The following changes have been made:
1. **Background Color Update**: Reduced the color intensity of the background for better visibility.
2. **Button Style Update**: Changed button colors to a whitish background with blue text for improved contrast.
3. **Input Field Hover Effect**: Added a white glow effect to input fields on hover for better visibility.
4. **Button Hover Effect**: Implemented a size increase on hover for buttons, enhancing interactivity and user experience.
5. **Form Hover Effect**: Enabled the forms to grow in size on hover, making them more dynamic and engaging.
6. **Increased Padding**: Added padding between form fields …
=> UI Enhancements and Accessibility Improvements

faq.html
Fixes: #2552 
I have removed the extra sections in the FAQ page and made the image visible again.
=> Changes in the FAQ section

maps.html
Fixes: #2517
This PR corrects the misalignment between the Financial Literacy Quiz card and the Share Your Feedback card on the Map Page. By aligning both cards in a visually balanced layout, it improves the overall user experience and aesthetic consistency of the page.
- Ensures **side-by-side or consistent alignment** of the two cards.
=> Fix: Align Financial Literacy Quiz Card with Feedback Card on Map Page

blog.html
Fixes: #2516
This PR addresses the misalignment issue between the blog post heading and its corresponding image, ensuring both elements are centrally aligned. This update enhances the visual consistency of the blog post section, improving readability and overall layout quality.
- **Centers the alignment** of the blog post heading with its image.
=> Fix: Center Align Blog Post Heading with Corresponding Image

index.html
Fixes: #2510
This PR addresses the inconsistent UI of blog post cards, ensuring a uniform and cohesive appearance. The issue was impacting readability and uniformity, which has now been resolved by standardizing styling, alignment, and font styling within the blog post cards.
=> Fix: Ensure Consistent UI for Blog Post Cards

assets/css/index.css
Fixes: #2585 
the changes follow an enchancement in discussion form
this pr will not make the discussion form look heavy as well has added functionality compared to previous one
- [ ✅ ] New feature (non-breaking change which adds functionality)
- [* ] I am a participant of GSSoC-ext.
- [ *] I have followed the contribution guidelines of this project.
- [* ] I have made this change from my own.
- [ *] I have taken help from some online resources.
- [* ] My code follows the style guidelines of this project.
- [ *] I have performed a self-review of my own code.
- [ *] I have added documentation to explain my changes.
- [ *] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
- [ *] This PR is submitted under the GSSoC program.
- [ *] I have …
=> enhancement of discussion form

about.html, assets/css/about.css
Fixes: #2563 
The About Us now updates correctly when dark mode is activated. The styling changes appropriately in dark mode to match the rest of the theme.
The "Next" and "Previous" buttons are clearly visible in both modes.
=> Update Dark Mode Functionality, and Visibility of Next/Prev Buttons on About page✨

trends.html
Hello, PR
Trends page heading text glitch issue fixed - 
https://github.com/user-attachments/assets/17ccf3ff-ee66-45e9-a341-83646b2e613c
Before -
https://github.com/user-attachments/assets/18d0c1f7-f0cc-4bde-bad9-bea78ed38137
=> Fix Trends page heading text issue !

newsletterpopup.js
Fix #2748 
This PR resolves the issue of the newsletter popup reappearing after clicking **"No Thanks"** by implementing a dismissal flag in cookies/local storage. The popup now checks this flag before displaying, enhancing the user experience by preventing unnecessary prompts.
@ayush-that @Sampadatiwari 
Pls assign me this, Give me label, level.
=> Fix Newsletter Popup Reappearance After User Dismissal

newsletterpopup.js
#Title : Fixed homepage visitor counter to track unique visits only once per user session
Fix #2657 
This PR addresses the issue where the visitor count increments each time a user returns to the homepage, even if they have already been counted. The visitor count now only increments on the first visit per user session, ensuring each visitor is counted only once.
@ayush-that Pls assign me this issue, give me labels, level.
=> Fixed homepage visitor counter to track unique visits only once per user session

contributors.html, index.html
Fixes: #2743 
This update addresses the inconsistent appearance of the 'Subscribe' container on the Contributor page, bringing it into alignment with other pages for a cohesive design.
**Additionally, the subscribe container on the Home page has been adjusted to correct inconsistencies, ensuring a uniform look and feel across the site.**
Before :
https://github.com/user-attachments/assets/1f6fb24d-6264-4002-ae4a-59ad9dab0328
After : 
https://github.com/user-attachments/assets/b45c1345-f119-4ca6-9181-b274514a19b5
=> Fix inconsistent Subscribe container on Contributor Page and Home Page

index.html, server/controllers/feedbackController.js, server/routes/feedbackRoutes.js
This PR implements the connection between the feedback backend and the frontend of our application. The following changes have been made:
1. **API Creation**: 
- Developed a new API endpoint to fetch feedback data from the backend. This API is designed to provide structured feedback entries that can be used throughout the application.
2. **Frontend Integration**:
- Integrated the newly created feedback API with the frontend on the homepage. 
- Implemented functionality to retrieve and display feedback data dynamically, ensuring that users can see the latest feedback without needing to refresh the page.
- **Backend**:
- Created an API endpoint at `/api/feedback/getfeedback` that returns feedback data in JSON format.
- Ensured that the API adheres to our existing data structure and includes …
=> Connected Feedback Frontend with Backend

assets/css/style.css
Fixed the inconsistency in the centering of the iPad mini dimensionality
Fixes: #2766
Fixed the inconsistency in the centering of the iPad mini dimensionality.
=> Fixed issue #2766

assets/css/style.css, index.html
Fixes: #2721 issue is solved
Now the card is looking good in the navbar and **Blog Posts** text is in center.
=> issue number #2721 is solved

termsOfUse.html
Fixes: #2883 
In this PR, I have resolved the issue of the overlapping subscribe placeholder and button to ensure the 'Subscribe to Newsletter' section looks good.
=> Overlap fix of placeholder and button

Games/Financial Goal Tracker Challenge.html
I've added the favicon to "Financial Goal Tracker Challenge Page".
fixes: #2996
=> FAVICON added to Financial Goal Tracker Challenge Page

assets/css/contributors.css
Fixes: #2855 
The contributors page is not responsive on mobile view, leading to poor layout and readability issues.
This update makes the contributors' page fully responsive on mobile, improving layout and readability. Adjustments include scaling contributor cards and text for optimal display on smaller screens.
Major changes include resizing contributor cards, adjusting font sizes, and spacing to ensure a clean, accessible display on smaller screens.
Key Improvements:
- Icons resize and align more compactly on smaller screens.
- Text font scales down for better readability on mobile.
- Responsive gap adjustments create a visually clean layout across device sizes.
=> Solved issue#2855

about.html, assets/css/about.css, assets/css/contributors.css, contributors.html
Fixes: #3001 
Closes: #3001 
Improvement of Toggle button on Contributors page 
https://github.com/user-attachments/assets/f3763a68-6c93-4a56-80fd-d2ea6edeefd9
https://github.com/user-attachments/assets/7917f3ab-1787-49b2-9fe5-fd5f87712cee
=> Fixing bug on Toggle button on Contributors Page 

contributors.html
fixes: #3034 
I've added the favicon to "CONTRIBUTORS" page
=> FAVICON added to CONTRIBUTORS page

blogs/sitemap.html
fixes: #3036 
I've added the favicon to "sitemap" page. A favicon helps users quickly recognize the app among multiple open tabs, providing a smoother user experience.
=> Added favicon to  "sitemap" page

index.html
Reverts ayush-that/FinVeda#2972
=> Revert "Add a pop up dialog box for Survey done ! #2865"

assets/css/ContactUs.css, assets/css/blog.css, assets/css/card.css, assets/css/market-time.css, assets/css/trends.css
Fixes: #2992 
responsiveness with all pages for better usuability
=> done with #2992 

contributors.html
Fixes: #3134 
Adding Enhanced scroll back button with a progress ring to the contributors page and giving a smooth slide.
https://github.com/user-attachments/assets/79b40fa2-f0da-4158-b94a-4ca4119c4e8e
=> Adding Enhanced scroll back button with a progress ring to the contributors page and giving a smooth slide.

navbar.js
Added the debounce function and then wrapped the scroll event handler with it.
When applied to scroll events, debouncing ensures the event handler is only executed after the user has stopped scrolling for a specified delay (e.g., 20 milliseconds). This prevents the event from firing continuously, which can be costly in terms of performance, especially when the page has visual updates during scrolling.
=> Updated navbar.js

Licensing.html
Fixes: #3144
Adding Enhanced scroll back button with a progress ring to the help page and giving a smooth slide. 
https://github.com/user-attachments/assets/53a3be84-3442-45ed-ac1c-1bca39943c24
=> Adding Enhanced scroll back button with a progress ring to the help page and giving a smooth slide. 

Finveda/blog.html, assets/css/style.css, index.html
Fixes: ##2851
As I have change the background color of blog-post card so that its color get match with the overall website color and also 
change the text style color for better UI according to background color. HoverEffect of color is also modified according to the color change. Thus, this enhance the UI and UX of blog-post section. 
The selection of color is done based on website theme color that give its look better and more attractive and professional feel.
- [✅ ] New feature (non-breaking change which adds functionality)
- [ ✅] I am a participant of GSSoC-ext.
- [ ✅] I have followed the contribution guidelines of this project.
- [✅ ] I have made this change from my own.
- [ ✅] I have taken help from some online resources.
- [✅ ] My code follows the style guidelines of this project.
- …
=> update blog-post card color and design

assets/js/contributors.js
Fixes: #3163 
I have added counting animation to numbers in stats section of contributions page..
https://github.com/user-attachments/assets/c8738154-c81f-4893-8e32-94ef67d1d2fa
@sampadatiwari30 @deepeshmlgupta Please review the PR
=> Added counting animation to numbers in contributors section

maps.html
Added the missing button to the Maps page dropdown ! 🌟🌟 
Before -
Now -
=> Added the missing button to the Maps page dropdown ! 🌟🌟 

tools/sip.html
Added the missing button to the Tools page dropdown ! 
Before -
Now -
=> Added the missing button to the Tools page dropdown ! 🌟🌟 

trends.html
Added the missing button to the Trends page dropdown ! 
Before -
Now -
=> Added the missing button to the Trends page dropdown ! 🌟🌟

faq.html
Added the missing button to the Help page dropdown ! 
Before -
Now -
=> Added the missing button to the Help page dropdown ! 🌟🌟

contributors.html
Added the missing button to the Contributors page dropdown ! 
Before -
Now -
=> Added the missing button to the Contributors page dropdown ! 🌟🌟

about.html
Added the missing button to the About Us page dropdown !
Before -
Now -
=> Added the missing button to the About Us page dropdown ! 🌟🌟

tools/sip.html
Fixes: #3275 
- Corrected the "Games" page link on `/tools/sip.html` by fixing the relative path issue.
- Changed `href="./Games/Games.html"` to `href="/Games/Games.html"` to resolve the 404 error.
- Ensures users are redirected to the correct page.
- [✅] Bug fix (non-breaking change which fixes an issue)
- [  ] Documentation update (adds or updates related documentation)
- [✅] I have followed the contribution guidelines of this project.
- [✅] I have made this change from my own.
- [✅] My code follows the style guidelines of this project.
- [✅] I have performed a self-review of my own code.
- [] I have added documentation to explain my changes.
- [✅] Make sure you have self-reviewed the code. A decent size PR without self-review …
=> BUG: "Games" link redirects to 404 error on /tools/sip.html
